import type { DevotionalDay } from "../types";

/**
 * Week 16 — Friendship (Amicitia).
 *
 * Co-counsel, the colleague you trust, the friend who is also a lawyer.
 * Cicero on amicitia as the soul's other self; Aquinas on charity as
 * friendship with God; the bar as a small civilization within which the
 * adversary system can survive at all.
 */
export const week16: DevotionalDay[] = [
  {
    day: 106,
    date: "04-16",
    weekNumber: 16,
    weekArc: "Friendship",
    weekArcLatin: "Amicitia",
    title: "Cicero, On Friendship",
    scripture: {
      reference: "Ecclesiasticus 6:14-17 (DR)",
      text: "A faithful friend is a strong defence: and he that hath found him, hath found a treasure. Nothing can be compared to a faithful friend, and no weight of gold and silver is able to countervail the goodness of his fidelity. A faithful friend is the medicine of life and immortality: and they that fear the Lord, shall find him. He that feareth God, shall likewise have good friendship: because according to him shall his friend be.",
    },
    excerpt: {
      author: "Marcus Tullius Cicero",
      citation: "De Amicitia, VI.20 (W. A. Falconer trans., Loeb 1923)",
      text: "For friendship is nothing else than an accord in all things, human and divine, conjoined with mutual goodwill and affection, and I am inclined to think that, with the exception of wisdom, no better thing has been given to man by the immortal gods. Some prefer riches, some good health, some power, some public honours, and many even prefer sensual pleasures. This last is the highest aim of brutes; the others are fleeting and unstable things, dependent less upon our own wise choice than upon the fickle whims of fortune. But those who place the chief good in virtue are entirely in the right, and this very virtue is the parent and preserver of friendship, and without it friendship cannot exist at all.",
    },
    meditation: `The first treatise on friendship in the Western tradition was written by a lawyer. Cicero composed De Amicitia in 44 BC, the year of Caesar's assassination, in a republic visibly dying around him. He set the dialogue in the mouth of Laelius, the great jurist and friend of Scipio Africanus the Younger, just after Scipio's death. The frame is a working lawyer asking an old advocate, between cases, how to think about the friend he has just lost. The book is short. You can read it in an evening. It has been read for two thousand years because nothing better on the subject has been written outside the Gospels.

Cicero defines friendship, in a sentence the Latin Mass tradition has half-remembered ever since, as omnium divinarum humanarumque rerum cum benevolentia et caritate consensio — an accord in all things, divine and human, joined with goodwill and affection. The definition is wider than ours. We use the word friend now for the man we play tennis with on Saturday and for the woman we have known since law school and would call from the side of a highway at 2 AM; the same word does both jobs, and it has been hollowed out by being asked to do so much. Cicero is reserving the word. A friend is one with whom you agree about what matters. The agreement is not on opinions; it is on the divinarum humanarumque rerum, the things divine and human — on what the good is, on what God is owed, on what a human life is for. Without that, you have an alliance, a colleagueship, a useful acquaintance. You do not have a friend.

A lawyer's life is full of useful acquaintances. The bar association mixer; the firm dinner where everyone is on a phone; the lunches kept on calendar because someone might refer a case someday. None of it is contemptible. Most of it is necessary. But it is not friendship in Cicero's sense, and you would die of loneliness if it were all you had. The professional life specializes in producing high volumes of cordial transaction. The danger is not that you will hate the people you work with. The danger is that you will mistake cordiality for friendship and stop looking for the thing itself.

Cicero is clear about what makes friendship possible. The chief good must be virtue. Two people who are friends in his sense are not chiefly bound by shared interests, shared schooling, shared ambition. They are bound by a shared sense of what is actually worth wanting. If your shared good is the next promotion, your friendship will not survive the day one of you gets it and the other does not. If your shared good is the firm's billing target, your friendship will not survive the slow year. The friendships that survive are the ones rooted in something that does not shift when fortune shifts — a common conviction about justice, a common debt to a particular faith, a common refusal to do something cheap. Cicero says this is rare. He is right. Most people you meet at the bar are not candidates for this. A few are. Pay attention to which few.

Notice the order in his definition. Goodwill and affection come after the consensio in things divine and human. Cicero does not deny that affection matters; he refuses to put it first. Modern friendship inverts the order — we feel an affinity and call it friendship and then are surprised when the affinity does not survive a hard disagreement. Cicero's old Roman wisdom holds the disagreement does not break the friendship; the agreement on the underlying things is what makes it possible to disagree without breaking. You can argue with such a friend about a Supreme Court case for an hour, take opposite sides at a moot, file briefs against each other in a real one, and walk out to dinner unchanged, because the argument was inside a wider accord.

There is a particular kind of legal friendship that approaches this. You know the man because you tried a case against him five years ago. He impressed you by being honest in a moment he could have hidden something. You impressed him similarly. Slowly, over years, in chance encounters at the bar association and at depositions in other matters, the relation deepened. You discovered you shared a faith, or near enough. You discovered you both read history. You discovered you both, in your private hours, despised the same cheap moves in the profession. The friendship is real and you would not have predicted it from the first introduction. It is, in fact, exactly the kind of friendship Cicero describes — an accord in the things that matter, slow to form, durable when formed.

The Ecclesiasticus passage you read this morning was written some centuries before Cicero, in a different tongue, in a different city, and it says the same thing more compactly. A faithful friend is a strong defence: he that hath found him, hath found a treasure. The Wisdom tradition and the Roman tradition meet on this point, and the Church, when she received both, did not hesitate to combine them. Aquinas will read Cicero on friendship and then say that the highest friendship is charity itself, friendship between God and man. That is tomorrow. Today, sit with the foundation. Friendship is rare. It is not the same as the network you have built. It is given, when it is given, by God, and it is held in place by a shared sense of what is divine and what is human. Without that agreement, you have something else, and the something else is fine, but you should not lean on it as if it were friendship.

If you can name one such friend tonight, name him. Pray for him before you sleep. Tomorrow, write to him. The accord that holds you together is not visible on the firm's org chart, but it is, in Cicero's sober Roman judgment, the second-best thing the immortal gods have given to man. The first is wisdom, and you may notice that the friend in question is generally also the one with whom you most readily share that.`,
    prayer: `Lord, you have given me the gift of a few true friends in this profession, and I have been a poor steward of the gift. Help me to see them clearly, to keep them, to write to them, to pray for them. Where I have settled for cordiality, give me the patience to wait for the thing itself. Amen.`,
    prompt: `Who is one friend at the bar with whom you share an accord in things divine and human — and when did you last say so to him?`,
    situationalTags: ["gratitude-for-the-bar", "sole-practice-loneliness"],
  },
  {
    day: 107,
    date: "04-17",
    weekNumber: 16,
    weekArc: "Friendship",
    weekArcLatin: "Amicitia",
    title: "Aquinas — Charity is Friendship",
    scripture: {
      reference: "John 15:13-15 (DR)",
      text: "Greater love than this no man hath, that a man lay down his life for his friends. You are my friends, if you do the things that I command you. I will not now call you servants: for the servant knoweth not what his lord doth. But I have called you friends: because all things whatsoever I have heard of my Father, I have made known to you.",
    },
    excerpt: {
      author: "St. Thomas Aquinas",
      citation: "Summa Theologiae, II-II, Q. 23, art. 1 (and art. 3 ad 1)",
      text: "Charity signifies not only the love of God, but also a certain friendship with him; which implies, besides love, a mutual return of love, together with a certain mutual communion. That this belongs to charity is evident from 1 John 4:16, 'He that abideth in charity, abideth in God, and God in him,' and from 1 Cor. 1:9, 'God is faithful, by whom you are called unto the fellowship of his Son.' Now this fellowship of man with God, which consists in a certain familiar conversation with him, is begun here in this life by grace, and will be perfected in the future life by glory. . . . And consequently charity is friendship of man for God.",
      workId: "aquinas-summa",
    },
    meditation: `Aquinas opens the treatise on charity in the Secunda Secundae with what reads, at first, as an almost shocking proposal. Charity, he says — the queen of the theological virtues, the gift poured into the soul at baptism, the thing without which all the rest is a clanging cymbal — is friendship. Caritas amicitia quaedam est. He cites Aristotle. He cites the gospel of John. He builds the argument carefully, as he always does, and at the end of the first article he has done something the average reader does not expect a thirteenth-century theologian to do: he has made friendship, of all things, the inner form of the highest virtue.

This matters for the lawyer who has spent a lifetime thinking of charity as something other than friendship. Charity, for most of us, is alms — the check written to the diocese appeal, the food drive at Thanksgiving, the pro bono case taken on at the bar association's request. None of that is wrong. None of it captures what Aquinas means. Charity in his sense is the disposition by which the soul lives in fellowship with God, knows herself loved by God, and loves God back. The alms flow from it; they are not the thing itself. The thing itself is closer to what you feel when you call your oldest friend and within thirty seconds you are talking about what matters, because you have not stopped where you left off the last time.

The premise Aquinas works from is that friendship, in its high Aristotelian sense, has three elements: mutual love, mutual willing of the good, and a sharing of life — what the medievals called communicatio. You cannot have friendship with someone you do not love; you cannot have friendship if your love is only an interior sentiment that wills the other no actual good; and you cannot have friendship without some shared life, some common ground that the two of you stand on together. Apply each element to the relationship between God and the soul. God loves us; he wills our good, even more than we will it ourselves; and — the decisive third element — he has made his life shareable with ours. The Incarnation, the Eucharist, the indwelling of the Spirit: these are the communicatio. God did not stay at a distance from which mere benevolence could reach. He came near enough that friendship became, scandalously, possible.

The gospel passage you read this morning is the New Testament's own statement of this. I will not now call you servants. The hinge of the sentence is the word now. There was a time when servant was the appropriate word; the change is recent and gracious. The mark of the new relation, Christ says, is that he has told them what he has heard from the Father. A servant does not know the master's business. A friend does. The disciples, the Lord says, are friends because he has confided in them. That is what God has done with the human race in Christ: confided in us. Aquinas is reading that passage and saying — calmly, in numbered articles — yes; this is friendship; this is what charity is.

This should reorder how you think about prayer. Prayer is not the petition of a servant to a master. It is, in its highest form, the conversation of friends. You can pray as a servant; the Lord does not mind. He minds, in fact, less than we suppose. But the gift offered is more than that. You are offered familiar conversation with God — and the Latin Aquinas uses, familiaris conversatio, is the same word a Roman would use of two old friends talking in the evening. The Mass, in the older theology, is the friend's table — the meal at which the friendship is renewed, the communicatio enacted in bread and wine.

The article that follows in the Summa — q. 23 a. 3 ad 1, also excerpted today — clarifies a possible objection. Surely, the objector says, we cannot really be friends with God; there is no equality. Aquinas answers that friendship does not require strict equality; it requires that the inequality be bridged by communication. The lord and the soldier are not equals, but if the lord shares his counsel with the soldier, a friendship of a real if unequal sort can exist between them. God has done more than share counsel; he has shared flesh. The inequality remains, and is infinite, but the bridge is built from the other side. Friendship with God is possible because God chose to make it possible.

For the lawyer, this has a practical force that runs in two directions. First, it gives you a category for your most important relation. You are not God's employee. You are not, despite the bar-roll vocabulary you live inside, even God's advocate in the technical sense — he is yours, not the other way around. You are God's friend, or are being formed into one. The whole purpose of the formation is to make the friendship real on your side, since it is already real on his. Every Mass, every prayer, every confession is the resumption of a familiar conversation that you keep walking out of.

Second, the human friendships you have are not in competition with this one. They are participations in it. Cicero said yesterday that friendship requires consensio in things divine and human. Aquinas adds that the highest things divine are themselves friendship — that the inner life of the Trinity is itself, in a sense beyond what we can articulate, the eternal friendship of three Persons who love each other in one substance. When two lawyers find that they share an accord in things divine and human, they are not building a relation out of nothing. They are tapping into a relation that is older than they are, and that God himself is. The friendship between you and the colleague you trust is not a small mortal thing. It is a small participation in something eternal.

So a question for tonight. The friendship with God — is it, in fact, familiar conversation, or is it stiff, formal, the speech of a servant who has not noticed that the master has called him friend? The relation has already been changed on God's side. He spoke the change at the Last Supper. Your job, in the prayer you say before sleep, is to receive the change and to speak back as one who has been called friend. The Latin Mass tradition has a phrase the priest mutters at the altar before communion: ad amicitiam tuam — into your friendship. Pray your way into that phrase tonight.`,
    prayer: `Lord Jesus, you have not called me servant; you have called me friend. Forgive me the days I have answered as a servant, formal and afraid. Make my prayer this evening the conversation of a friend who knows he is welcome at the table. Teach me to share with my colleagues at the bar the friendship you have first shared with me. Amen.`,
    prompt: `When you prayed last, did you speak as a servant or as a friend — and what would change in tomorrow morning's prayer if you took Christ's word in John 15 at full value?`,
    situationalTags: ["before-mass", "gratitude-for-the-bar"],
  },
  {
    day: 108,
    date: "04-18",
    weekNumber: 16,
    weekArc: "Friendship",
    weekArcLatin: "Amicitia",
    title: "Co-Counsel at Eleven O'Clock",
    scripture: {
      reference: "Ecclesiastes 4:9-12 (DR)",
      text: "It is better therefore that two should be together, than one: for they have the advantage of their society. If one fall he shall be supported by the other: woe to him that is alone, for when he falleth, he hath none to lift him up. And if two lie together, they shall warm one another: how shall one alone be warmed? And if a man prevail against one, two shall withstand him: a threefold cord is not easily broken.",
    },
    excerpt: {
      author: "Aristotle",
      citation: "Nicomachean Ethics VIII.1 (W. D. Ross trans., Oxford 1908)",
      text: "Friendship is most necessary with a view to living. Without friends no one would choose to live, though he had all other goods. For even rich men and those in possession of office and of dominating power are thought to need friends most of all; for what is the use of such prosperity without the opportunity of beneficence, which is exercised chiefly and in its most laudable form towards friends? Or how can prosperity be guarded and preserved without friends? . . . And in poverty and in other misfortunes men think friends are the only refuge.",
    },
    meditation: `The brief is due at midnight. It is 10:43 PM. You have been at this all day, and most of the previous day, and the argument is not working — you can feel it not working — and you cannot tell whether you are too tired to see it clearly or whether the structure is actually wrong. Your associate left at nine. Your spouse is asleep. The client expects to read this in the morning and to like it.

You pick up the phone. There is one number you would dial at 10:43 PM, and only one. You dial it.

He answers on the third ring. You can hear that he has put his book down. You apologize for the hour. He waves it off with the same phrase he has used for fifteen years — don't be ridiculous — and asks what is going on. You read him the heading of section III. He says, hmm. You read him the first paragraph. He says, that's fine. You read him the third paragraph and he stops you. Wait, he says. Why are you arguing it that way? You are arguing this on equitable grounds when the real argument is jurisdictional. You will lose if you make this look like a fairness case. The bench is going to think you don't have the law. Move section III before section II. Cut paragraph two entirely. You'll have the brief done by midnight.

He is right. You knew he was going to be right. That is why you called him.

This is what Ecclesiastes is talking about. It is better therefore that two should be together, than one. If one fall he shall be supported by the other. The Preacher is not being sentimental; he is being practical, in the unsentimental Hebrew way. The man alone in the field falls and there is no one to help him up. The man alone in a brief at 10:43 PM cannot see his own argument because he has lived inside it too long. He needs a second pair of eyes — not a colleague who will flatter him, not a researcher who will check his citations, but a friend whose judgment he trusts more than he trusts his own at that hour.

There is a name for that person in your profession. He is called co-counsel, even when he is not formally on the case. He is the lawyer you would call at 11 PM and would not feel guilty about the hour. The relation is built up over years, mostly outside any particular file. You worked together once on a small matter. You both showed up. You both did what you said you would do. He took the messier piece without complaining. You took the messier piece next time. Slowly, you became the person each other could call.

Aristotle, in Book VIII of the Nicomachean Ethics, says that friendship is necessary not chiefly for prosperity but for adversity. The friend is the refuge in misfortune. You know this from your own practice. The friend at the bar is not the man you celebrate the win with — though you do, and the celebration is sweeter for being shared. The friend at the bar is the man you call when the wheels are coming off, when the witness collapsed on cross, when the client is suing you, when you are not sure whether the brief due tonight is good or terrible and you cannot tell anymore. He is the refuge.

This is in part why the gospel makes friendship the highest analogy for the soul's relation to God. The dimension of friendship that the Hebrew Preacher and the Greek philosopher both notice — the friend is for adversity — is the dimension on which our most fundamental need rests. We do not, finally, need a God who is good to us in our prosperity, although we have one. We need a God we can call at 10:43 PM on the worst day. The fact that Christ in John 15 calls his disciples friends, the night before he is arrested and they are scattered, is significant. He is not naming a fair-weather relation. He is naming a relation strong enough to hold what is about to happen.

A young lawyer reading this should pay particular attention. The relations you are forming in your first decade at the bar will be the ones you call at 11 PM in your fifth decade. Build them slowly and well. The man you cut corners with in your second year will be the man who cuts corners with you in your tenth. The man you took the boring piece for, and who took the boring piece for you, will be the man you can call at any hour for the rest of your working life. These things compound. They compound the wrong way too. Reputation among your peers is not a marketing problem; it is the slow construction, or the slow demolition, of the network of trust that you will live inside for forty years.

A practical word. Be the person who picks up. The friendship is reciprocal or it dies. If you are willing to be called at 11 PM, you must also be willing to take the call at 11 PM. This requires that you not resent the call. The man on the other end is not interrupting your evening; he is honoring you by trusting you with the moment of his greatest professional doubt. Honor him back. Put the book down. Listen. Give him the answer, or tell him you do not know but you will think about it for ten minutes and call back, and then call back.

The phone call ends. You hang up. You move section III before section II, cut paragraph two of the new section III, and the structure comes clear. The brief is done at 11:48 PM. You file it. You will sleep. The client will read it in the morning and find it improved by an argument that was not yours alone — that was, in its quiet way, the joint work of two friends who have been at this together for long enough that one of them could pick up his phone at 10:43 PM and not have to explain anything.

Thank him in the morning. Tell him the brief was better because of him. Friendships, like virtues, atrophy if they are not exercised, and the exercise is mostly small acknowledgments after the fact. The threefold cord is not easily broken, but it is woven by small motions, and you have to keep weaving.`,
    prayer: `Lord, thank you for the friend whose phone I can dial at eleven at night without apology. Keep him faithful in his own work; keep me a faithful friend to him in mine. When my own phone rings late, let me put the book down and answer with the patience he has shown me. Amen.`,
    prompt: `Who is your eleven-o'clock friend at the bar — and when did you last thank him, by name, for being so?`,
    situationalTags: ["11pm-still-at-office", "gratitude-for-the-bar"],
  },
  {
    day: 109,
    date: "04-19",
    weekNumber: 16,
    weekArc: "Friendship",
    weekArcLatin: "Amicitia",
    title: "The Colleague You Cannot Trust",
    scripture: {
      reference: "Proverbs 25:19 (DR); Psalm 54:13-15 (DR)",
      text: "To trust to an unfaithful man in the time of trouble, is like a rotten tooth, and weary foot. . . . For if my enemy had reviled me, I would verily have borne with it. And if he that hated me had spoken great things against me, I would perhaps have hidden myself from him. But thou a man of one mind, my guide, and my familiar, who didst take sweetmeats together with me: in the house of God we walked with consent.",
    },
    excerpt: {
      author: "Marcus Tullius Cicero",
      citation: "De Amicitia, XVIII.65 (W. A. Falconer trans., Loeb 1923)",
      text: "It is necessary, therefore, that there should be loyalty in friendship; for without it friendship cannot exist. Moreover, it is fitting that the friend be agreeable in word and manner, since these are no slight seasonings of friendship. Gloom and severity of disposition are by all means austere, but friendship ought to be more easy and free and pleasant, and more inclined to all courtesy and complaisance. But here arises a difficult question — whether new friends, who are worthy of friendship, are at any time to be preferred to old ones, as we are wont to prefer young horses to old ones. The doubt is unworthy of a man.",
    },
    meditation: `Yesterday's meditation was about the lawyer you call at 11 PM. Today's is harder. It is about the lawyer you used to call at 11 PM, and have stopped calling, because somewhere along the way the relation went bad.

Every working bar has these stories. They are rarely told, because no one comes out of them looking well. You were close. You shared cases. You shared a year of legal practice and several of life. Then something happened. He took the credit for a brief that was mostly your work. He repeated to a partner the thing you said to him at lunch, which he had been told in confidence. He left the firm and took a client you had brought in, and did not tell you he was going to. Or — the more common variant — nothing dramatic happened at all. The relation just slowly went cold, and you found yourself less and less willing to be in the room with him, until one day you realized you had stopped trusting him and could not remember the moment it had happened.

The psalm you read this morning is one of the most painful in the psalter, and it is not about an enemy. The psalmist could have borne an enemy's reviling — he could have hidden from him, as one hides from any other danger. The wound he names is the wound of the man of one mind, my guide, and my familiar, who didst take sweetmeats together with me: in the house of God we walked with consent. The Latin Vulgate calls him familiaris meus, my familiar, the same root word Aquinas uses for friendship with God. The pain of the psalm is precisely that the loss is the loss of a friend, not an enemy. The man who shared the table and the prayer is the man who has now broken the bond.

Proverbs is, characteristically, more clinical. To trust to an unfaithful man in the time of trouble is like a rotten tooth and a weary foot. Both images are physical: the body has a part that should be reliable and is not. You bite down on what should be a sound tooth and pain runs up the jaw. You step forward on what should be a sound foot and it gives. The Hebrew sage is teaching the practical lesson that the spiritual writers will later teach more delicately: an unreliable friend is worse than no friend at all in trouble, because you have leaned on a thing that does not hold.

How does a lawyer come to this? Cicero, in De Amicitia, treats the question gravely. He says friendships go wrong for many reasons but two are most common. The first is when a friend, raised by fortune above his old companions, comes to find them inconvenient. The second is when the agreement on the things that matter — Cicero's consensio in things divine and human — was never as deep as both parties had supposed, and the first real test reveals the shallowness. The relation looked like friendship; it was actually an alliance of convenience; the convenience expired and so did the relation.

You will recognize both patterns. The first is the partner who made partner before you did and stopped returning your calls. The relation was real, but it was not strong enough to survive his being above you. The second is the lawyer who agreed with you on everything until the firm pressured both of you to do the questionable thing, and you said no, and he said yes, and you both discovered that what you had taken for a shared moral sense was actually a shared cultural surface. Cicero is unsentimental about this. Some friendships were never quite what we took them for, and the discovery is sad but instructive. The friendships that survive such tests are the real ones.

Here is the danger of the broken friendship at the bar: not that you will be hurt by it, although you will. The danger is that you will let it harden you into the kind of lawyer who no longer trusts anyone, who treats every collegial relation as a transaction in advance, who keeps his cards close because of the one set of cards that was once turned against him. This is the bitter ex-friend's curse on you, and it works whether he intended it or not. The wound becomes a teacher of withdrawal. After enough such wounds, you are alone in your office, civil to everyone, intimate with no one, telling yourself you have wised up when in fact you have shrunken.

The Christian way through is harder than withdrawal and harder than naive re-trust. It begins with two acts: honesty about what happened, and refusal to let the broken friendship become the template. Honesty: name to yourself what he did and what you did. He may have been the chief wrongdoer; you were rarely an innocent party, and the discipline of confession is for this exact reason. Forgive him. Forgiveness does not require reconciliation, which depends on him as well as you; forgiveness requires only that you let go of the right to be his judge. Pray for him. The medieval practice of praying by name for the one who has injured you is not pious decoration; it is the actual surgery that detaches the wound from your daily life.

Then, the refusal to let the template harden. The next colleague who shows promise of becoming a real friend deserves to be met as himself, not as a re-edition of the man who failed you. The old wound makes this difficult. You will catch yourself doing it — testing him, holding back, expecting the betrayal that has not happened. Notice the pattern. Bring it to confession. Try again. The slow work of trusting another lawyer after you have been burned is one of the hidden penances of a long career, and the rebuilding, when it happens, is itself a small resurrection.

A note for the senior lawyer. Younger lawyers are watching how you treat your peers — how you speak of an opposing counsel in private, how you handle the colleague who once wounded you. They are learning, from your example, whether the bar is the kind of small civilization in which friendship is possible. Conduct yourself as though it is.

Pray tonight for the colleague who broke trust with you. Pray for him by name, for the part you played, and ask the Lord to redeem the loss without requiring you to pretend it did not happen. The familiar of the psalm became, in the long providence, the type of Judas, and the type of Judas became, in another providence, the occasion of the redemption of the world. Your smaller losses, taken to the foot of the cross, may yet bear a smaller fruit. They will not bear it if you keep them in the locked drawer of bitterness instead of bringing them out.`,
    prayer: `Lord, you know the colleague I am thinking of as I pray this. I have carried the wound longer than I have admitted. Give me the grace to forgive him by name, to ask forgiveness for my own part, and not to let the broken friendship harden into a habit of mistrust toward better friends still to come. Amen.`,
    prompt: `Name to yourself the colleague who broke trust with you — and ask whether you have actually forgiven him, or only stopped speaking of him.`,
    situationalTags: ["senior-partner-bullying", "partnership-track"],
  },
  {
    day: 110,
    date: "04-20",
    weekNumber: 16,
    weekArc: "Friendship",
    weekArcLatin: "Amicitia",
    title: "When Work Makes Friendship Hard",
    scripture: {
      reference: "Genesis 13:7-9 (DR)",
      text: "Whereupon also there was a strife between the herdsmen of Abram and of Lot. . . . Abram therefore said to Lot: Let there be no quarrel, I beseech thee, between me and thee, and between my herdsmen and thy herdsmen: for we are brethren. Behold the whole land is before thee: depart from me, I pray thee: if thou wilt go to the left hand, I will take the right: if thou choose the right hand, I will pass to the left.",
    },
    excerpt: {
      author: "St. Augustine of Hippo",
      citation: "Letter 73 (to Jerome), §10",
      text: "I confess to your charity, that I have learned to fear nothing in my friendships so much as that, while we are still living in this world, the things which the providence of God uses for our trial should so divide us in feeling as to separate us in spirit. For it is one thing for friends to be in different places, and another for them to be of different minds; and it is grievous to me even to think of the second, where, by the very fact of our once having been one, the loss is doubled. Let us therefore pray for each other, and resolve to bear with each other, that no occasion of our calling may make us cease to be brethren.",
    },
    meditation: `She was your moot court partner. Second year. You wrote the brief together over six weeks in the law library, alternating sections, fighting about the order of arguments, finally agreeing that the privacy argument went first and the federalism argument went second, drafting until 2 AM the night before. You won regionals. You came in second at nationals to a team from a school you both privately despised. You spent the bus ride home rehearsing what you should have said at the bench's third question. You graduated together. You both clerked. You both went to firms in the same city. You were in each other's weddings.

Now, fifteen years later, she is opposing counsel on a major matter. Not a small matter — a major one. There is a $40 million exposure for your client, and her client is the one trying to extract it. The case will go on for two years. There will be twelve depositions. There will be discovery motions every two months. The two of you have not had a real conversation in eight years, because the work has not allowed it, and now the work has made it impossible.

The matter is in nobody's hand. It is not that either of you behaved badly. The partners chose. The clients chose. The conflict-of-interest letter went out from her firm explaining why she would be taking the case. Your firm responded that they would be opposing. The bar has fewer of these stories than novels suggest, but it has more than the bar itself remembers. Two lawyers who were once one — to use Augustine's phrase — are now in different rooms, and the rooms are not changing for two years.

Augustine wrote his most painful correspondence on exactly this dynamic, although the matter at issue was theological rather than litigation. He and Jerome — two of the great minds of the patristic west, men who admired each other across the Mediterranean — fell into a long, slow, partly-bitter exchange about whether Paul had rebuked Peter sincerely or only ostensibly at Antioch. Augustine took one view, Jerome the other. The correspondence ran for years. Both men understood that the issue itself, while important, was being used by something larger to test their friendship. Augustine, in the letter excerpted today, names what he fears: that the providence of God uses our trials to separate us in spirit, even when it does not separate us in place. It is one thing to be far from one's friend; it is another, and worse, to be of a different mind from him, when the very fact of having been one makes the loss double.

Litigation does this to former co-conspirators of moot court. The providence here is not malicious; God is not arranging the conflict to wound either of you. But the conflict is real, and you must decide, on each motion and each deposition and each call between you and her, what kind of opposing counsel you are going to be. The options narrow quickly. You could become brittle and formal — communicating only in writing, refusing the small courtesies, treating every motion as a chance to embarrass. You could become falsely warm — performing the old friendship at depositions, sending Christmas cards, while doing in the file what you would not do in front of anyone you actually loved. Or you could find the third thing, which is harder and which the Christian tradition has more of a vocabulary for than the law schools admit.

The third thing is honest opposition inside continuing regard. You file the motion the case requires. You take the deposition the case requires. You do not pull punches; she would not forgive you if you did. But you do not put into the briefs the snide footnote that you could put in; you do not use the deposition to embarrass her witness beyond what the answer requires; you return her calls within the hour even when the call is going to be hard. And — this is the part that requires actual virtue — you pray for her, by name, before the depositions you take of her witnesses. The prayer is not for her to lose. The prayer is that the matter come out justly, that neither of you do something cheap, that the friendship, weakened but not killed, survive the two years of being on opposite sides.

Abraham and Lot in Genesis 13 is the older version of this. The herdsmen fight; the land is not large enough for both households; Abraham, the elder, declines to insist on his prerogative. Let there be no quarrel. We are brethren. Take the land you choose; I will take the other. They part — but they part as brothers, and a few chapters later when Lot is captured Abraham raises an army to rescue him. The separation did not have to be enmity. It could be sober and provisional. The case lasted as long as it lasted, and then they were brothers again.

The conflict-of-interest letter is the Genesis 13 of your generation. It is the formal acknowledgement that two lawyers, who would otherwise sit at the same dinner, cannot for a season sit on the same side. The right response to it is grief, not bitterness. Grief is the appropriate human emotion when something good is interrupted by something necessary. Bitterness is what grief becomes when you refuse to call it grief.

Practical counsel. First, do not stop praying for her because you are now opposing her. The temptation is to drop her from the list precisely when she most needs to be on it. Second, do not use the litigation to indulge feelings you have been carrying about her from the years before. The conflict deserves a clean fight, not a proxy one. Third, find the small courtesies that the rules allow and the case does not require — the extension on a deadline that does not matter, the courtesy copy emailed without being asked, the brief acknowledgment when she has filed something well. None of this is weakness; it is the maintenance of the friendship through a long professional winter. Fourth, when the case ends — settlement, verdict, appeal exhausted — call her. Suggest dinner. Do not pretend the two years did not happen. Let them have been what they were. Move on if she will, and grieve if she will not.

The friendship that survives the case will be tougher than the one that did not have to. The friendship that does not survive will have done its work, in its time, and the memory of it is itself a participation in the friendship of God, who lost human friends often and went on loving them. Sleep with that tonight if you can.`,
    prayer: `Lord, you know the lawyer on the other side of my hardest current matter, and you know what she was to me before the work made us opponents. Keep both of us honest in the file. Keep me from the cheap blow, and from the false warmth that would betray the honesty of opposition. Save the friendship for the day after the case ends. Amen.`,
    prompt: `Is there a lawyer with whom your friendship has gone cold because the work demanded it — and what small fidelity could you practice toward her, this week, that the case does not require?`,
    situationalTags: ["partnership-track", "envy-of-the-bigger-firm"],
  },
  {
    day: 111,
    date: "04-21",
    weekNumber: 16,
    weekArc: "Friendship",
    weekArcLatin: "Amicitia",
    title: "I Will Not Now Call You Servants",
    scripture: {
      reference: "John 15:13-17 (DR)",
      text: "Greater love than this no man hath, that a man lay down his life for his friends. You are my friends, if you do the things that I command you. I will not now call you servants: for the servant knoweth not what his lord doth. But I have called you friends: because all things whatsoever I have heard of my Father, I have made known to you. You have not chosen me: but I have chosen you; and have appointed you, that you should go, and should bring forth fruit; and your fruit should remain: that whatsoever you shall ask of the Father in my name, he may give it you. These things I command you, that you love one another.",
    },
    excerpt: {
      author: "St. John Henry Newman",
      citation: "Parochial and Plain Sermons, Vol. IV, Sermon XV ('Love of Religion, a New Spring of Life')",
      text: "And what is the office of Christ to us, but that of intimate Friend? He chose us first, when we were enemies; he calls us friends now that we are reconciled. There is no human friendship which is not, when truly examined, an image and a foretaste of his; the love of brother for brother, of husband for wife, of child for parent — all are but rays of that one love which streamed forth from the cross. To know him, then, is not only to know our Saviour: it is to know what friendship really is, for the first time, and to be enabled, by knowing it, to be the friend that, before, we could only attempt to be.",
      workId: "newman-idea",
    },
    meditation: `The sentence is short and the Latin is shorter: iam non dicam vos servos. I will not now call you servants. The text is from the long discourse at the Last Supper, the night before Christ is arrested. He has just washed their feet. He has just identified the betrayer. He is twenty-four hours from the cross. He says this to them in that hour.

Pause on the situation. The disciples are not in a heroic moment. They are confused, sleepy, frightened. Most of them will run before sunrise. Peter will deny him three times before the cock crows. Judas has already left the room. And it is to this group — not a successful group, not an impressive group, a group about to fail him at every level — that he says: I will not now call you servants. The change of name is not earned. It is given.

If you are tempted to think you must achieve friendship with God by your own performance, the timing of John 15 is meant to break that thought. Christ does not say, after Pentecost you will be friends. He does not say, when you have proven yourselves in the great trial that begins tomorrow, then I will call you friends. He says it now, before the failures. He says it precisely now, before. The friendship is constituted by his word, not by the disciples' character. Their character will catch up later, but it does not catch up first. The friendship comes first.

This is a hard word for a lawyer to receive. You make your living by performance. You bill in increments; you are measured by deliverables; your name is on briefs the quality of which determines your professional standing. You inhabit a profession that has, almost by structure, instilled in you the conviction that approval is earned in real time. The category of being given a relation prior to performance is foreign to your daily grammar. It is the gospel's first move on you, and the move it has to make over and over because you keep forgetting it.

Note the content of the friendship Christ describes. The mark of his calling them friends is that he has confided in them. All things whatsoever I have heard of my Father, I have made known to you. Friendship, for him, is the shared confidence — the same Aristotelian and Ciceronian element you read about earlier in the week, the communicatio of life. The Father's life has been opened to the disciples through the Son's confidence in them. They are friends because they know the Father's business. They are not servants because servants do not know it.

Newman, in the Parochial and Plain Sermons, traces the implication. If Christ is the friend, then every human friendship is, when truly examined, an image and foretaste of his. The friendships you have at the bar, the friendship you have with your spouse, the friendship you formed with your moot court partner in the law library at 2 AM — these are not separate from your friendship with God. They are particular instances of the universal friendship that the Incarnation has established between God and the human race. The love between brother and brother is a ray of the love that streamed from the cross. Newman is not being lyrical; he is being theologically literal. The cross is the founding act of Christian friendship, and every smaller friendship is downstream of it.

This means several things for a Christian lawyer.

First, your friendships at the bar have a depth they would not have without Christ. The man you call at 11 PM is not just a useful colleague; he is, in the order of grace, a near-sacramental presence — a small image of the High Priest who is interceding for you above. Every time the friendship at the bar holds firm in adversity, you are seeing the action of the friendship of Christ working through human matter. Take the friendships more seriously. They are theologically more important than your professional vocabulary admits.

Second, the loneliness many lawyers experience is partly the loss of this dimension. The lawyer who has stopped practicing his faith but kept his bar friendships often notices, around year fifteen or twenty, that the friendships have flattened without his being able to say why. The flattening is real. The friendships have lost the upward reference that gave them their depth. Cicero noticed this without being able to name it; he said friendship requires consensio in things divine and human, and when the divine drops out the consensio thins. The remedy is not to recover Cicero. The remedy is to recover the Friend who said, on the night before he died, I will not now call you servants. He has not stopped saying it. Your bar friendships, returned to that ground, gain back the dimension they have lost.

Third, the obligation Christ lays on the disciples in the same paragraph is the strange one: that you love one another. The you is plural. The friendship he has constituted between himself and them obligates them to a friendship among themselves. The vertical relation requires the horizontal one. You cannot, in the order of John 15, be a friend of Christ and treat the colleague at the next desk as merely a useful associate. The friendship of Christ obligates you to extend the same posture, in your small measure, to the people he has put around you. Newman: to know him is to know what friendship really is, for the first time, and to be enabled, by knowing it, to be the friend that, before, we could only attempt to be.

A practical exercise tonight. Take the prayer of intercession you say before sleep — you may already have one, or you may not — and place into it, by name, the five colleagues at the bar who are closest to you. Not as professional contacts. As friends. Pray for them the way Christ in John 17 prays for his disciples: keep them, sanctify them, may they be one. The prayer will feel slightly strange the first time you pray it that way, because you have not used that vocabulary for them before. The strangeness is itself a sign that something needs to be adjusted. The Lord has called you friend; the people he has put next to you are also called friend; the friendship is meant to be at the table together.

The Latin Mass tradition saves the most intimate moments of friendship for the few seconds before communion. The priest says, in the older form, Domine, non sum dignus — Lord, I am not worthy. He goes on to say that the Lord should say only the word and his soul will be healed. The exchange is the exchange of friends, and the Bread is the body of the Friend, given to make the friendship more than ceremonial. Each Mass is the renewal of John 15. Each communion is the audible repetition, sub specie sacramenti, of the same sentence: I will not now call you servants. I have called you friends. Go and love one another, because I have loved you.`,
    prayer: `Lord Jesus, you called me friend on a night when I would have failed you, and you have not stopped calling me friend on every night since. Make my friendships at the bar small images of your friendship with me. When I forget which I am — friend or servant — say the word again, and let me hear it. Amen.`,
    prompt: `If Christ has already named you friend, what would change in how you treat the five colleagues whose names rise first to mind tonight?`,
    situationalTags: ["before-mass", "gratitude-for-the-bar"],
  },
  {
    day: 112,
    date: "04-22",
    weekNumber: 16,
    weekArc: "Friendship",
    weekArcLatin: "Amicitia",
    title: "Friendship Across the Bar",
    scripture: {
      reference: "Matthew 5:43-45 (DR)",
      text: "You have heard that it hath been said, Thou shalt love thy neighbour, and hate thy enemy. But I say to you, Love your enemies: do good to them that hate you: and pray for them that persecute and calumniate you: That you may be the children of your Father who is in heaven, who maketh his sun to rise upon the good, and bad, and raineth upon the just and the unjust.",
    },
    excerpt: {
      author: "St. John Henry Newman",
      citation: "The Idea of a University, Discourse VIII ('Knowledge Viewed in Relation to Religion'), §10",
      text: "It is almost a definition of a gentleman to say he is one who never inflicts pain. . . . He has his eyes on all his company; he is tender towards the bashful, gentle towards the distant, and merciful towards the absurd; he can recollect to whom he is speaking; he guards against unseasonable allusions, or topics which may irritate; he is seldom prominent in conversation, and never wearisome. He makes light of favours while he does them, and seems to be receiving when he is conferring. He never speaks of himself except when compelled, never defends himself by a mere retort, he has no ears for slander or gossip, is scrupulous in imputing motives to those who interfere with him, and interprets every thing for the best.",
      workId: "newman-idea",
    },
    meditation: `The adversary system rests on a paradox the public never quite believes. Two lawyers oppose each other ferociously in court and then walk out together to the cafeteria. They cross-examine a witness who has just contradicted their case under oath, and then exchange a joke at the elevator about the judge's tie. The public reads this as proof that lawyers are cynics; that the courtroom is theater; that what they say to each other in pleadings is not what they think. The reading is wrong. The reality is more interesting and more important. The adversary system can function only because the bar is, beneath the cases, a fraternity. Without the fraternity, the system would collapse into the war of all against all that the cases by themselves would produce.

This is not a sentimental claim. It is a structural one. Every working bar has unwritten rules — that you do not embarrass opposing counsel in court without cause, that you grant the reasonable extension, that you do not bait the witness with traps you would resent if used against your own, that you accept the other side's word in small matters, that you do not, when the case ends, carry the case into the rest of your life. These rules are not in the Rules of Professional Conduct, though some of them have echoes there. They are in the air the courthouse breathes. They are taught by the older lawyers to the younger ones by example more than by speech. They are what makes it possible for the system to be adversarial without being savage.

The Christian tradition has a name for the deeper version of this. Christ in Matthew 5 commands the disciples to love their enemies. He does not soften the command. He does not turn the enemies into friends in disguise. He acknowledges, in the very wording, that they are enemies — that there is real opposition, real harm done. Then he commands the love anyway. The reason given is not utilitarian. The reason is that the Father makes his sun to rise upon the good and the bad, and raineth upon the just and the unjust. The Christian is to behave like the Father — to extend, beyond the boundary of mutual benefit, a goodwill that crosses lines of allegiance.

Translate that to the bar. Opposing counsel is not your enemy in any biblical sense; he is your opponent in a specific matter, a much smaller category. But the command scales down. You are to behave toward the opponent the way the Father behaves toward those who do not love him: with a basic goodwill that does not depend on him deserving it, and that does not stop when the case is going badly for you. The cross-examination remains. The motion to compel remains. The closing argument remains. What is forbidden is the small cruelty, the unnecessary humiliation, the line in the brief that exists only to wound.

Newman, in the famous passage from the Idea of a University, describes the gentleman: one who never inflicts pain. The whole passage is worth memorizing, though it is too long to print here in full. He is tender towards the bashful, gentle towards the distant, and merciful towards the absurd. He has no ears for slander or gossip, is scrupulous in imputing motives to those who interfere with him, and interprets every thing for the best. Newman is describing, in nineteenth-century English, almost exactly what the older bar means when it calls a lawyer a gentleman — a man with whom one can litigate, hard, and shake hands afterward without insincerity. Newman knew the type because the Inns of Court, in his day, were full of it.

The type is endangered. The pressures of modern practice — the social media instantiation of every dispute, the firm websites that crow about scorched-earth tactics, the cable-news habit of contempt — work against the type. Every working bar has a few partners who specialize in being unpleasant, and the unpleasantness is presented as a service. It is not a service. It is a corrosion of the only fabric that holds the system together. The lawyer who treats every opposing counsel as a domestic enemy is not a fierce advocate; he is a free-rider on the civility of everyone else.

This week has been about friendship — Cicero, Aquinas, the eleven-o'clock friend, the colleague who broke trust, the former co-counsel who is now opposing counsel. The week ends here, with the question of what friendship can mean across the bar. The Christian answer is twofold. First, friendship in the full sense, of the kind Aquinas describes — accord in the things divine and human — is rare across the bar, as it is rare everywhere, and it is not the standard you can impose on a relationship structured by opposition. You will not be friends in that full sense with most of the lawyers you face. Second, the analogue of friendship that the bar at its best embodies — fraternity, courtesy, mutual recognition of dignity, the practice of opposing without despising — is achievable across the bar, is in fact required of you by Christ in Matthew 5, and is one of the small ways the Kingdom is built inside an adversary system.

Practical disciplines. First, before a hard hearing or deposition, take three minutes to pray for opposing counsel by name — not for him to lose, but for him to be honest, to do his job, to go home to his family. The three minutes change you, not him. Second, honor the older bar's small courtesies. Grant the extension when it does not hurt your client. Return calls promptly. Do not file the motion if a phone call will solve it. Third, when you are tempted to write the cutting footnote, do not. It will not help your client. It will only mark you, in the file and in your own soul, as the kind of lawyer who writes such footnotes.

Fourth, the longest discipline: build the bar you want to belong to. Show up at the bar association. Take on the unglamorous committee work. Mentor the younger lawyer who reminds you of yourself fifteen years ago. The bar is a small civilization, sustained by the people who sustain it.

The week closes with one image. The Latin Mass at the kiss of peace — pax tecum — has the priests exchanging the small embrace of fellow servants of the same Lord: brothers at the same altar, before the same sacrifice, exchanging the physical sign that they are not at war with each other. The bar at its best practices a secular version of the same gesture — the handshake at the end of the hearing, the nod across the courtroom, the courtesy in the elevator. Practice it. It is not weakness. It is the small daily liturgy by which the system you have been given the privilege to serve continues to be possible.

A faithful friend, Ecclesiasticus says, is a strong defence. So is a faithful adversary, which is a different thing and a related one. May you, by the end of your career, have a long list of both.`,
    prayer: `Lord, you commanded me to love even those who oppose me, and you knew I would have to learn this in courthouses I had not yet seen. Teach me to fight hard and despise no one. Make me the kind of lawyer with whom others can litigate without injury, and let me leave the bar, when I leave it, a little better than I found it. Amen.`,
    prompt: `Which opposing counsel would you most struggle to pray for by name tonight — and what would it cost you, and what might it give you, to do so?`,
    situationalTags: ["bar-committee", "gratitude-for-the-bar"],
  },
];
