import type { DevotionalDay } from "../types";

export const week12: DevotionalDay[] = [
  {
    day: 78,
    date: "03-19",
    weekNumber: 12,
    weekArc: "Subsidiarity",
    weekArcLatin: "Subsidiaritas",
    title: "The Foundational Text",
    scripture: {
      reference: "Exodus 18:21-22",
      text: `And provide out of all the people able men, such as fear God, in whom there is truth, and that hate avarice, and appoint of them rulers of thousands, and of hundreds, and of fifties, and of tens, who may judge the people at all times: and when any great matter soever shall fall out, let them refer it to thee, and let them judge the lesser matters only: that so it may be lighter for thee, the burden being shared out unto others.`,
    },
    excerpt: {
      workId: "pius-quadragesimo",
      author: "Pius XI",
      citation: "Quadragesimo Anno §§79-80 (1931)",
      text: `As history abundantly proves, it is true that on account of changed conditions many things which were done by small associations in former times cannot be done now save by large associations. Still, that most weighty principle, which cannot be set aside or changed, remains fixed and unshaken in social philosophy: Just as it is gravely wrong to take from individuals what they can accomplish by their own initiative and industry and give it to the community, so also it is an injustice and at the same time a grave evil and disturbance of right order to assign to a greater and higher association what lesser and subordinate organizations can do. For every social activity ought of its very nature to furnish help to the members of the body social, and never destroy and absorb them.`,
    },
  },
  {
    day: 79,
    date: "03-20",
    weekNumber: 12,
    weekArc: "Subsidiarity",
    weekArcLatin: "Subsidiaritas",
    title: "When the Higher Arrogates",
    scripture: {
      reference: "1 Samuel 8:11-14",
      text: `This will be the right of the king, that shall reign over you: He will take your sons, and put them in his chariots, and will make them his horsemen, and his running footmen to run before his chariots, And he will appoint of them to be his tribunes, and centurions, and to plough his fields, and to reap his corn, and to make him arms and chariots. Your daughters also he will take to make him ointments, and to be his cooks, and bakers. And he will take your fields, and your vineyards, and your best oliveyards, and give them to his servants.`,
    },
    excerpt: {
      workId: "burke-reflections",
      author: "Edmund Burke",
      citation: "Reflections on the Revolution in France (1790)",
      text: `To be attached to the subdivision, to love the little platoon we belong to in society, is the first principle (the germ as it were) of public affections. It is the first link in the series by which we proceed towards a love to our country and to mankind. The interest of that portion of social arrangement is a trust in the hands of all those who compose it; and as none but bad men would justify it in abuse, none but traitors would barter it away for their own personal advantage.`,
    },
  },
  {
    day: 80,
    date: "03-21",
    weekNumber: 12,
    weekArc: "Subsidiarity",
    weekArcLatin: "Subsidiaritas",
    title: "The Partner Who Decides What the Associate Should",
    scripture: {
      reference: "Numbers 11:14-17",
      text: `I am not able alone to bear all this people, because it is too heavy for me. But if it seem unto thee otherwise, I beseech thee to kill me, and let me find grace in thy eyes, that I be not afflicted with so great evils. And the Lord said to Moses: Gather unto me seventy men of the ancients of Israel, whom thou knowest to be ancients and masters of the people: and thou shalt bring them to the door of the tabernacle of the covenant, and shalt make them stand there with thee, that I may come down and speak with thee: and I will take of thy spirit, and will give to them, that they may bear with thee the burden of the people, and thou mayest not be burthened alone.`,
    },
    excerpt: {
      workId: "pius-quadragesimo",
      author: "Pius XI",
      citation: "Quadragesimo Anno §80 (1931)",
      text: `The supreme authority of the State ought, therefore, to let subordinate groups handle matters and concerns of lesser importance, which would otherwise dissipate its efforts greatly. Thereby the State will more freely, powerfully, and effectively do all those things that belong to it alone because it alone can do them: directing, watching, urging, restraining, as occasion requires and necessity demands. Therefore, those in power should be sure that the more perfectly a graduated order is kept among the various associations, in observance of the principle of subsidiary function, the stronger social authority and effectiveness will be, and the happier and more prosperous the condition of the State.`,
    },
  },
  {
    day: 81,
    date: "03-22",
    weekNumber: 12,
    weekArc: "Subsidiarity",
    weekArcLatin: "Subsidiaritas",
    title: "The Bishop's Restraint",
    scripture: {
      reference: "1 Peter 5:2-3",
      text: `Feed the flock of God which is among you, taking care of it, not by constraint, but willingly, according to God: not for filthy lucre's sake, but voluntarily: Neither as lording it over the clergy, but being made a pattern of the flock from the heart.`,
    },
    excerpt: {
      workId: "leo-rerum-novarum",
      author: "Leo XIII",
      citation: "Rerum Novarum §51 (1891)",
      text: `The State should watch over these societies of citizens banded together in accordance with their rights, but it should not thrust itself into their peculiar concerns and their organization, for things move and live by the spirit inspiring them, and may be killed by the rough grasp of a hand from without.`,
    },
  },
  {
    day: 82,
    date: "03-23",
    weekNumber: 12,
    weekArc: "Subsidiarity",
    weekArcLatin: "Subsidiaritas",
    title: "The Foundation That Crowds Out",
    scripture: {
      reference: "Acts 4:34-35",
      text: `For neither was there any one needy among them. For as many as were owners of lands or houses sold them, and brought the price of the things they sold, and laid it down before the feet of the apostles. And distribution was made to every one, according as he had need.`,
    },
    excerpt: {
      workId: "leo-rerum-novarum",
      author: "Leo XIII",
      citation: "Rerum Novarum §49 (1891)",
      text: `Such societies as are adapted to the needs of the time in which we live, societies for mutual help, various benevolent foundations established by private persons to provide for the workman, and for his widow or his orphans, in case of sudden calamity, in sickness, and in the event of death, and what are called "patronages" for boys and girls, for young people, and also for those of more mature age, hold the foremost place. The most important of all are workingmen's unions, for these virtually include all the rest.`,
    },
  },
  {
    day: 83,
    date: "03-24",
    weekNumber: 12,
    weekArc: "Subsidiarity",
    weekArcLatin: "Subsidiaritas",
    title: "When Subsidiarity Is Excuse",
    scripture: {
      reference: "Luke 10:31-32",
      text: "And it chanced, that a certain priest went down the same way: and seeing him, passed by. In like manner also a Levite, when he was near the place and saw him, passed by.",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologica II-II, q. 71, a. 1",
      text: `It belongs to one who exercises an office, in virtue of that office, to give counsel: thus a lawyer is bound to give counsel in matters of law, a physician in matters of medicine, an architect in matters of building. Wherefore if anyone, through guile or laziness, fails to do so, he sins against justice. And, similarly, in cases of necessity, one is bound to give counsel to anyone who asks it, even though one does not exercise an office in his regard.`,
    },
  },
  {
    day: 84,
    date: "03-25",
    weekNumber: 12,
    weekArc: "Subsidiarity",
    weekArcLatin: "Subsidiaritas",
    title: "The Annunciation",
    scripture: {
      reference: "Luke 1:26-38",
      text: `And in the sixth month, the angel Gabriel was sent from God into a city of Galilee, called Nazareth, To a virgin espoused to a man whose name was Joseph, of the house of David; and the virgin's name was Mary. And the angel being come in, said unto her: Hail, full of grace, the Lord is with thee: blessed art thou among women. Who having heard, was troubled at his saying, and thought with herself what manner of salutation this should be. And the angel said to her: Fear not, Mary, for thou hast found grace with God. Behold thou shalt conceive in thy womb, and shalt bring forth a son; and thou shalt call his name Jesus. He shall be great, and shall be called the Son of the Most High; and the Lord God shall give unto him the throne of David his father; and he shall reign in the house of Jacob for ever. And of his kingdom there shall be no end. And Mary said to the angel: How shall this be done, because I know not man? And the angel answering, said to her: The Holy Ghost shall come upon thee, and the power of the Most High shall overshadow thee. And therefore also the Holy which shall be born of thee shall be called the Son of God. And behold thy cousin Elizabeth, she also hath conceived a son in her old age; and this is the sixth month with her that is called barren: Because no word shall be impossible with God. And Mary said: Behold the handmaid of the Lord; be it done to me according to thy word. And the angel departed from her.`,
    },
    excerpt: {
      workId: "augustine-city",
      author: "Augustine of Hippo",
      citation: "Sermon 215, on the Creed",
      text: `He chose a mother whom He had created; He created a mother whom He chose. Mary was the Virgin Mother, the chaste handmaid, who in conceiving the Word also conceived virginity. She brought forth her Son in such wise that she did not lose her virginity; for as a virgin she conceived, as a virgin brought forth, and a virgin she remained. Why dost thou wonder at this, O man? It behoved God to be born in this manner, when He deigned to become man.`,
    },
  },
];
