import type { DevotionalDay } from "../types";

/**
 * Week 3 — Equity / Aequitas.
 * Where the rule fails the case. The lawyer's particular charism of
 * remembering what the statute forgot.
 */
export const week03: DevotionalDay[] = [
  {
    day: 15,
    date: "01-15",
    weekNumber: 3,
    weekArc: "Equity",
    weekArcLatin: "Aequitas",
    title: "When the rule fails the case",
    scripture: {
      reference: "Matthew 12:7",
      text: "And if you knew what this meaneth: I will have mercy, and not sacrifice: you would never have condemned the innocent.",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae I-II, q. 96, a. 6 (trans. Fathers of the English Dominican Province, 1920)",
      text: "Every law is directed to the common weal of men, and derives the force and nature of law accordingly. Hence the Jurist says: 'By no reason of law, or favour of equity, is it allowable for us to interpret harshly, and render burdensome, those useful measures which have been enacted for the welfare of man.' Now it happens often that the observance of some point of law conduces to the common weal in the majority of instances, and yet, in some cases, is very hurtful. Since then the lawgiver cannot have in view every single case, he shapes the law according to what happens most frequently, by directing his attention to the common good. Wherefore if a case arise wherein the observance of that law would be hurtful to the general welfare, it should not be observed.",
    },
    meditation: `There is a moment in nearly every practice when the statute, read straight through, will produce a result that no honest person would call just. The text is plain. The facts fit it as a key fits a lock. And still, applying the rule will work an injury the legislature plainly never imagined. This is the moment the Christian advocate inherits a problem older than common law and older than the Code: the problem of the general rule confronted by the particular case.

Aquinas is not afraid of it. "The lawgiver cannot have in view every single case," he writes, and so he "shapes the law according to what happens most frequently." That is what a statute is: a portrait of the ordinary. It is drafted with the typical defendant in mind, the typical contract, the typical accident, the typical family. But there are no typical defendants in your office today. There is only the one in front of you, with her particular history and her particular fear, and the question she has come to ask is whether the law has anything to say to her case that is not cruel.

The Lord answers the Pharisees in the same temper. They have caught the disciples plucking grain on the Sabbath and they have a statute. The statute is real; it is not a fiction; it is Sinai itself. And Jesus does not deny the statute. He quotes the prophet against the misuse of it. "If you knew what this meaneth: I will have mercy, and not sacrifice: you would never have condemned the innocent." The condemnation comes not from the law but from a way of reading the law that has forgotten what the law was for. The Sabbath was given for man, and the man before them is hungry. The rule, applied without remembering its purpose, has become an instrument against the very life it was given to protect.

You will be tempted, as you read this, to think that equity is a soft virtue, a kind of moral leniency that lets the well-meaning lawyer fudge the edges of the rule. It is not. Equity is harder than the rule. The rule asks only that you read; equity asks that you understand. The rule can be applied at scale; equity must be applied to a person. The rule fits in a checklist; equity will not fit anywhere except inside a conscience that has been formed by long attention. To stand in the gap between the statute and the case is to do a more difficult thing than to apply the statute, because you must know the statute well enough to see what it was reaching for, and you must know the case well enough to see where its reaching falls short.

Consider the boilerplate motion you will file this week. It is a form. Someone you never met drafted the original, and you have changed three names and a docket number and the citation to a case. The form is, in itself, a small monument to legal economy: it is what allows one lawyer to serve many clients without inventing the wheel for each of them. But it is also a danger, because the form does not know your client. The form has a typical client in mind, and your client is not typical. Read the form again before you sign it and ask whether anything in this particular case requires a sentence the form does not contain. Most days the answer will be no. The day the answer is yes, you have met equity, and you owe it the extra hour.

Consider the misdemeanor docket call. Forty cases before lunch. The judge has a script and the prosecutor has a script and the public defender, if your client is fortunate enough to have one, has been handed a file ten minutes ago. The system is built for volume. It is, again, not a wicked thing in itself: the alternative — that every shoplifting case receive the attention of a homicide — would collapse the courts within a week. But the volume creates a temptation to forget that each case is a case. The defendant who is third on the list is not a unit; she is a woman whose mother is in the hospital and whose children are in school and whose job will not survive a conviction. The statute does not know any of this. You may be the only person in the room whose office it is to tell the court that the statute does not know.

Aquinas calls the virtue by its Greek name, epieikeia — the right reading of the rule. It is not the suspension of the rule; it is the rule's own honesty about what it is. A statute that pretended to anticipate every case would be either tyrannical or absurd. The statute is humble; it knows it is general. Equity is the courtesy the law shows itself by remembering that humility in the courtroom. The advocate who pleads equity is not pleading against the legislature; he is pleading on behalf of the legislature, defending what the lawmakers would have said had they been told this particular story.

Take this, then, into the day. The forms will pile up. The dockets will move. The pressure to bill the hour and close the file is real, and you cannot make it vanish by being holy about it. But somewhere in the stack will be one case where the typical answer is not the true answer, and the question for you is whether you will see it. The whole vocation, in a sense, is the practice of seeing it. The law schools do not teach you to see it; the bar exam does not test for it; the partners' compensation formula does not reward it. You will learn it, if you learn it at all, from cases. And from prayer, which is the slow training of attention.

"I will have mercy, and not sacrifice." It is not a license to break the rule. It is a warning against the kind of reading that makes the rule break people.`,
    prayer: `Lord of the Sabbath, give me eyes today for the one case in my stack that does not fit the form. Teach me to know the rule well enough to know when it is silent, and to plead, in the silence, for the mercy You taught us You prefer to sacrifice. Keep me from the laziness that calls the typical answer the just one. Amen.`,
    prompt: `Which file on your desk this week is the file the statute did not foresee?`,
  },
  {
    day: 16,
    date: "01-16",
    weekNumber: 3,
    weekArc: "Equity",
    weekArcLatin: "Aequitas",
    title: "The leaden rule",
    scripture: {
      reference: "Wisdom 11:24",
      text: "But thou hast mercy upon all, because thou canst do all things, and overlookest the sins of men for the sake of repentance.",
    },
    excerpt: {
      author: "Aristotle",
      citation: "Nicomachean Ethics V.10, 1137b (trans. W. D. Ross, 1908)",
      text: "When the law speaks universally, then, and a case arises on it which is not covered by the universal statement, then it is right, where the legislator fails us and has erred by over-simplicity, to correct the omission — to say what the legislator himself would have said had he been present, and would have put into his law if he had known. Hence the equitable is just, and better than one kind of justice — not better than absolute justice but better than the error that arises from the absoluteness of the statement. And this is the nature of the equitable, a correction of law where it is defective owing to its universality. In fact this is the reason why all things are not determined by law, viz. that about some things it is impossible to lay down a law, so that a decree is needed. For when the thing is indefinite the rule also is indefinite, like the leaden rule used in making the Lesbian moulding; the rule adapts itself to the shape of the stone and is not rigid, and so too the decree is adapted to the facts.",
    },
    meditation: `Long before there were chanceries there was a builder in Lesbos. He worked, Aristotle tells us, with a rule of lead. A wooden rule is straight, and it measures only what is straight; if you press it against a curved stone it lies to you, and the building suffers. The leaden rule was something else. It bent. It took the shape of the stone, and so it told the truth about the stone, and the wall went up in a way that honored what was actually there. Aristotle saw in that humble tool an image of the highest justice: a measure willing to be shaped by what it measured.

We do not, as lawyers, like to think of our rules as leaden. We like them iron. The legal mind is trained, from the first weeks of law school, to admire the bright line, the per se rule, the elements neatly enumerated, the test that yields the same answer in every court in every county. There is real beauty in this — the beauty of predictability, of equal treatment, of a citizen being able to know in advance what the law requires. Aristotle does not denigrate it. He only points out that the bright-line rule, faithfully applied, sometimes builds a crooked wall, because the stone in front of you is not the stone the legislator imagined.

"When the law speaks universally," he says, "and a case arises on it which is not covered by the universal statement, then it is right, where the legislator fails us and has erred by over-simplicity, to correct the omission." Notice the verb. He does not say overrule, set aside, suspend. He says correct. The error is in the absoluteness of the statement, not in the law itself. Equity, for Aristotle, is not a separate jurisdiction with its own throne; it is the law's own conscience reaching back into itself to repair the place where its universality has overshot the case.

The author of Wisdom puts the theological version of the same thought. "Thou hast mercy upon all, because thou canst do all things, and overlookest the sins of men for the sake of repentance." It is striking that the writer grounds God's mercy in His power. We tend to imagine that mercy is what we do when we are not strong enough to enforce the rule, a kind of compassionate failure. Wisdom inverts it. Mercy is what only the wholly competent judge can afford. The weak judge is rigid because he cannot trust himself to bend. The strong judge — the One who can do all things — can afford to overlook, to wait, to hold open the possibility of repentance, because His justice is not threatened by the delay. The leaden rule does not betray the wall; it builds it.

There is a temptation in the legal mind to be a wooden rule. It feels safer. The form contract is a wooden rule: every party signs the same words, every clause means what the precedent says it means, every ambiguity is construed in the same direction. You can defend yourself, in any malpractice action, by pointing to the standard form. No one fired you for using the boilerplate. But the form was drafted, like the wooden ruler, for the stone that is straight, and many of the stones on your desk are not straight. The closely-held family business with three siblings who haven't spoken in a decade is not the stone the form imagined. The licensing agreement between a sophisticated tech company and a nonprofit run by two volunteers is not the stone the form imagined. The non-compete clause boilerplated into the offer letter of an immigrant nurse from a country with no equivalent doctrine is not the stone the form imagined. The rule is wooden; the stone is curved; if you do not bend the rule, you will build a crooked wall, and someone will live in it.

This does not mean you should throw away the form. It means you should know what the form was made for, and you should know your client well enough to know whether the form was made for him. The leaden rule was still a rule. It had a length; it had a purpose; it did not become merely whatever the builder wished. It was simply willing to take the shape of what it measured. The equitable lawyer is not the lawyer with no rules; he is the lawyer whose rules have been pressed against enough actual stones that they have learned to bend without breaking.

There is a vocational warning in this passage too. If you are early in practice, you will spend years memorizing the wooden rules. You must. The leaden rule is useless to a builder who does not know what straight is, because he has no standard against which to perceive that the stone is curved. The law student who skips to equity has skipped the apprenticeship. But if you are late in practice — if you have been doing this for fifteen years and you find yourself, more and more often, refusing to bend the rule because bending the rule is harder than applying it — Aristotle is asking a question of you. He is asking whether you have grown into the leaden rule or hardened into the wooden one.

The hour-billing structure punishes the leaden rule, because the leaden rule costs time. The custom-drafted clause takes three hours; the boilerplate takes ten minutes. The careful negotiation around a unique family situation takes a month; the cease-and-desist takes an afternoon. There is no metric on your timesheet for "shaped the rule to fit the stone." There is no bonus for "built a wall that will stand." You will only know you did it because the wall stands. The client, years later, will not call to thank you, because he will not know how close he came to a crooked building. The thanks, if it comes, will come from the One who built mercy into His own justice because He could afford to.

Be that builder. Carry the leaden rule into the day.`,
    prayer: `God of mercy and of power, You have shown us that the truest justice bends toward the case in front of it without breaking. Make me a builder with a leaden rule today: faithful to the measure, willing to be shaped by the stone, unafraid of the time it costs. Where I have hardened into wood, soften me back into the law's own conscience. Amen.`,
    prompt: `Where in your practice have you become a wooden rule when the case asked for a leaden one?`,
  },
  {
    day: 17,
    date: "01-17",
    weekNumber: 3,
    weekArc: "Equity",
    weekArcLatin: "Aequitas",
    title: "Law remembering its own purpose",
    scripture: {
      reference: "Micheas 6:8",
      text: "I will shew thee, O man, what is good, and what the Lord requireth of thee: Verily to do judgment, and to love mercy, and to walk solicitous with thy God.",
    },
    excerpt: {
      author: "Christopher St. German",
      citation: "Doctor and Student, Dialogue I, ch. 16 (1530; spelling modernized)",
      text: "Equity is a righteousness that considereth all the particular circumstances of the deed, the which also is tempered with the sweetness of mercy. And such an equity must always be observed in every law of man, and in every general rule thereof: and that knew he well that said thus, Laws covet to be ruled by equity. And the wise man saith, Be not over much righteous; for the extreme righteousness is extreme wrong: as who saith, if thou take all that the words of the law giveth thee thou shalt sometime do against the law. And for the plainer declaration what equity is, thou shalt understand that sith the deeds and acts of men, for which laws have been ordained, happen in divers manners infinitely, it is not possible to make any general rule of the law but that it shall fail in some case.",
    },
    meditation: `St. German was writing in 1530, in the small hinge of a dialogue between a Doctor of Divinity and a Student of the Laws of England. He was trying to teach the student something that the bar exam still does not teach: that equity is not a separate court invented by chancellors but a faculty of the law itself. "Equity," he says, "is a righteousness that considereth all the particular circumstances of the deed, the which also is tempered with the sweetness of mercy." The whole sentence is worth slow reading. Equity is a righteousness. It is not a softening of righteousness, not its opposite. It is righteousness done in the only way that fully serves its name: with the particular case in view.

The prophet Micheas says the same thing from a different angle. "What doth the Lord require of thee?" — and then three things in apposition, not three separate duties but one duty refracted into three lights. To do judgment. To love mercy. To walk solicitous with thy God. Judgment without mercy is what Pharaoh did in Egypt; mercy without judgment is what Eli did with his sons. The third clause, walking solicitous with God, is the discipline by which the first two stay married. To do judgment and to love mercy is the work of one undivided heart, and equity, in our trade, is the legal name for that undividedness.

Notice the structure of St. German's argument. He does not say that equity steps in when the law has run out. He says that equity must be observed in every law and in every general rule of it. Equity is not a backup system. It is the way every general rule is meant to be read. The rule and its equity are like the body and the breath: separate them and you no longer have a living creature. The lawyer who thinks of equity as a special remedy for unusual cases has misunderstood what equity is. Equity is the ordinary mode of the lawful mind.

He quotes, beautifully, the wise man: "Be not over much righteous; for the extreme righteousness is extreme wrong." It is the same warning Cicero put as summum ius summa iniuria — the highest law, the highest injury. The lawyer who is most certain that he is right is the lawyer most in danger of doing the most serious wrong. The certainty is a sign that the case has been compressed into the rule before it was understood. The compression is what does the harm. The form contract that solves ninety-nine cases and ruins one is, for the one, an instrument of the highest injury, precisely because it carried the highest law into a place the law was not made for.

Consider what it means for a statute to remember its own purpose. A statute is a sentence written by people for people. It came into being because of a problem. Someone, at some point, saw an injustice and tried to prevent its recurrence by laying down a general rule. The rule was a means. The purpose was the prevention of the injustice. Over time, the rule begins to lead a life of its own; it is cited and re-cited; it accumulates a commentary; it becomes, in the legal imagination, a thing whose authority no longer requires reference to the injustice that prompted it. This is when statutes go bad. They go bad not by being violated but by being applied without memory.

You have seen this. The fee schedule that was promulgated to ensure widows got their probate inheritance promptly, now used to extract twice the fee from a widow whose case is simple. The expedited eviction process that was designed for genuinely abandoned units, now used against tenants who answered the door. The mandatory minimum that was passed in response to a particular crime wave, now applied to the seventy-year-old grandmother whose case bears no resemblance to anything the legislature pictured. In each case the rule is intact. In each case the purpose has been forgotten. The injustice the rule was meant to prevent is now being committed by the rule.

The Christian advocate has a particular calling here, and it is not a sentimental one. It is the calling to be the memory of the law. The judge cannot hold every legislative history in mind. The prosecutor will not, in the heat of the docket, recall the floor debate. The client does not know any of it. You are the one who has been trained, sometimes at appalling expense, to read the statute against its purpose. You are the one whose name on the brief obliges you to ask, in every case, not only what the rule says but what the rule was for. When you do this, you are not opposing the law. You are doing for the law what no one else in the courtroom has the standing to do. You are loving it back to itself.

This is harder than it sounds, because the legal culture rewards the opposite. It rewards the citation, the brief, the brightness of the line. To plead purpose feels, often, like pleading at a different register, as if you had switched from prose to poetry mid-argument. The judge will sometimes resent it. Opposing counsel will treat it as weakness, the lawyer's confession that he has no case on the text. You will need a particular kind of nerve. You will need to remember, on those mornings, that the law was made for man and not man for the law, and that the courtroom that has forgotten this has not become more lawful but less.

Walk solicitous with God today. The word in Hebrew suggests careful attention, the kind of walk that watches its steps. Equity is the lawyer's version of that walk. Watch your steps in the cases. Read the rule, and then read again for its purpose. The judgment and the mercy were never two things; they were one thing, and your office is to keep them so.`,
    prayer: `Lord of the law and of its purpose, give me a memory that does not forget what each rule was made to protect. Keep me from the certainty that flattens the case into the citation. Let me walk solicitous today, with judgment and mercy held in one hand, and not let me put them down. Amen.`,
    prompt: `What rule do you apply often without asking what it was originally for?`,
  },
  {
    day: 18,
    date: "01-18",
    weekNumber: 3,
    weekArc: "Equity",
    weekArcLatin: "Aequitas",
    title: "The chancellor's foot",
    scripture: {
      reference: "Proverbs 21:3",
      text: "To do mercy and judgment, pleaseth the Lord more than victims.",
    },
    excerpt: {
      author: "John Selden",
      citation: "Table Talk (compiled by Richard Milward, 1689), s.v. \"Equity\"",
      text: "Equity is a roguish thing: for law we have a measure, know what to trust to; equity is according to the conscience of him that is Chancellor, and as that is larger or narrower, so is equity. 'Tis all one as if they should make the standard for the measure we call a foot, a Chancellor's foot; what an uncertain measure would this be? One Chancellor has a long foot, another a short foot, a third an indifferent foot: 'tis the same thing in the Chancellor's conscience.",
    },
    meditation: `Selden was no enemy of equity; he was a friend of measure. His jibe about the chancellor's foot is the most quoted line in the literature on equity, and it deserves its fame, because it names the discipline equity owes the law. If equity is only the conscience of the particular judge — if it is whatever this chancellor, on this morning, with this digestion, happens to think fair — then it is not a virtue but a mood. A mood with the force of a decree behind it is a frightening thing. Selden's joke is a warning that has lost none of its bite in three hundred and fifty years.

The warning matters because the temptation it names is real. You will encounter, in your career, judges whose sense of fairness is essentially their sense of themselves. You will encounter advocates who plead equity whenever the text is against them, as if the word were a wild card to be played from the back of the hand. You will, in your own work, feel the pull. The text is hard; the case is sympathetic; you would like to argue that the rule should bend. Selden is asking you, before you draft the brief, what discipline your argument is under. Whose foot will set the standard? Yours? The judge's? The client's tears? Or something more durable than any of these?

The book of Proverbs gives the answer in a single line. "To do mercy and judgment, pleaseth the Lord more than victims." Mercy and judgment, again together, again inseparable. The verse does not exalt mercy over judgment; it does not exalt judgment over mercy; it exalts the doing of them as a single pleasing thing, more pleasing than the elaborate ritual that pretends to substitute for either. The "victims" in the Hebrew are the sacrifices of the temple, the costly performance of religion. The proverb says, in effect: do not bring me the brief that performs righteousness without doing it. The chancellor whose foot is his own appetite is performing equity. He is not doing it. The doing has a standard, and the standard is older than him.

The medieval chancellors knew this, although Selden's joke obscures it. The Chancery in its great period was an ecclesiastical court before it was a royal one. The Lord Chancellor was usually a bishop, trained in canon law, accountable not only to the king but to a confessor and, behind the confessor, to a tradition that took conscience as a matter for examination, not improvisation. Conscience in that tradition is not what you feel; it is the application of a known good to the case before you. It can be ill-formed; it can be malformed; it requires training. The chancellor's foot was supposed to be a foot disciplined by Scripture, by the Fathers, by the canons, by the moral theology in which he had been catechized for thirty years before he ever set foot in Westminster. That is a foot of a particular size. It is not the foot of the chancellor's mood.

The Christian advocate is the heir of that discipline, and the heir is supposed to know what was bequeathed. When you plead equity in a brief, you are not pleading your sentiment. You are pleading a tradition. You are pleading Aquinas and Aristotle and Micheas and James. You are pleading the long argument of a civilization that has thought carefully about when the rule should bend and why, and you owe it to the court to do that argument in public, with citations and reasoning and a clear account of the limits of what you are asking. You owe the court an equity that is not a roguish thing. The chancellor's foot is not a problem if the foot has been measured.

There is a parallel discipline you owe in your own life. The lawyer who is honest with himself knows that he has favored clients. There are people he wants to help; there are people he does not. There are cases that move him; there are cases that bore him. Equity becomes roguish when these inclinations begin to determine which cases get the careful work and which get the boilerplate. You may not realize you are doing it. The sympathetic case gets the late hours; the unsympathetic case gets the form motion; the small case for the difficult client gets the intern. This is the chancellor's foot in your own office, and you are the chancellor. The discipline of equity begins at home, with an honest account of where your foot is unequal.

Selden's quip is also a warning against a certain rhetoric that has become common in our time, the rhetoric that treats every appeal to rules as a failure of compassion and every appeal to compassion as a higher form of law. This is precisely the move Selden mocks. The "compassion" that is exempt from any measure outside itself is the chancellor's foot in a new dress. The compassionate ruling that contradicts the constitution will, over time, hollow out the constitution; the compassionate ruling that contradicts the next compassionate ruling will, over time, hollow out compassion itself. Equity is a friend of law because equity is itself a kind of law: the law of the case, disciplined by the law of the text, both of them disciplined by the prior law of conscience formed in tradition.

Take the warning into the day. When you plead for the bending of a rule, plead it under a rule. When you sit in any seat of judgment — and even the negotiator and the supervising partner sit in such seats — discipline your foot. Walk solicitous with God, as Micheas said yesterday, which means walk in a measure not your own. The mercy and judgment that pleased the Lord are not improvisations. They are the long obedience that learned, over years, how to be merciful without being arbitrary and how to judge without becoming cruel. Selden's jibe should hang above your desk. It is a Protestant joke, but it teaches a Catholic discipline.`,
    prayer: `Lord, measure my foot today. Do not let me mistake my own appetite for Your mercy, nor my own irritation for Your judgment. When I plead equity, give me the older arguments; when I sit in judgment, give me the older measures. Keep my conscience under a discipline not its own. Amen.`,
    prompt: `Where in your work is the standard of fairness secretly the size of your own foot?`,
  },
  {
    day: 19,
    date: "01-19",
    weekNumber: 3,
    weekArc: "Equity",
    weekArcLatin: "Aequitas",
    title: "The prayer for relief",
    scripture: {
      reference: "Psalm 84:11",
      text: "Mercy and truth have met each other: justice and peace have kissed.",
    },
    excerpt: {
      workId: "blackstone-commentaries",
      author: "William Blackstone",
      citation: "Commentaries on the Laws of England, Book III, ch. 27 (1768)",
      text: "Equity, in its true and genuine meaning, is the soul and spirit of all law: positive law is construed, and rational law is made, by it. In this, equity is synonymous to justice; in that, to the true sense and sound interpretation of the rule. But there is also another, or oeconomical species of equity, which is the principal subject of jurisdiction in the court of chancery. The system of our courts of equity is a labour'd connected system, governed by established rules, and bound down by precedents from which they do not depart, although the reason of some of them may perhaps be liable to objection.",
    },
    meditation: `At the bottom of every complaint in the old chancery practice was a clause that has survived, in mostly fossilized form, into our modern pleading: the prayer for relief. The word "prayer" is not accidental. The plaintiff is not demanding; he is asking. He is asking a court of conscience to grant him a particular remedy, and the form of the request acknowledges that the granting is not automatic, that the chancellor sits with a discretion the common-law judge did not have, that the answer to the petition will depend on more than the text of the writ. The prayer for relief is the place in the lawsuit where the legal document becomes, however briefly, a liturgical document. It is the place where the lawyer admits he is asking for grace.

The Psalmist gives us the metaphor in one of the loveliest lines in the Psalter. "Mercy and truth have met each other: justice and peace have kissed." The four virtues are not four; they are two pairs, and each pair is the embrace of opposites that the world cannot keep married. Truth, alone, condemns. Mercy, alone, excuses. They meet in the prayer for relief, when the lawyer brings the truth of the case and the mercy of the remedy into the same paragraph, and asks the court to grant what is just in a particular case rather than what is merely owed under a general rule. Justice and peace, similarly, are not the same; the justice that produces no peace is a justice that has failed of its end. The chancery courts existed to perform that kiss. The modern lawyer, in many practices, is the one still tasked with arranging the meeting.

Blackstone, in his great defense of equity, calls it "the soul and spirit of all law." That is a high phrase, and worth pausing over. The body of the law is the text — the statutes, the codes, the precedents, the rules of procedure. The soul of the law is what gives the body its life: the purpose it serves, the conscience it answers to, the human good it was constituted to protect. A body without a soul is a corpse, no matter how well preserved. A statute without equity is enforceable but dead. The chancery, in Blackstone's account, is the institution that keeps the soul present to the body, that breathes purpose back into the rule when the rule has begun to forget.

It matters that the prayer for relief is plural. The old pleading typically ended with a request for specific relief — return of the property, an injunction, an accounting — and then a residual clause: "and for such other and further relief as to the court may seem just and equitable." The residual clause is the open hand. It is the lawyer's acknowledgment that he cannot specify in advance every remedy the case might require, and his trust that the court, sitting in equity, has the imagination and the authority to fashion what the case demands. The clause is small and easy to skim. It is also a confession that the law is not a vending machine: you do not press the button for your remedy and receive it; you ask, and the court answers.

You will draft prayers for relief this week. Many of them will be formulaic, and that is fine; the form has its place. But there are cases in which the prayer is the most important paragraph in the complaint, and you should know how to write one. The first discipline is to ask for what you actually want, not what the form last asked for. The second is to ask for what the court can actually give, in the actual jurisdiction, under the actual cause of action; nothing collapses the prayer faster than the asking for what no court has the power to grant. The third, and the deepest, is to ask in a register that takes seriously the conscience of the court. You are not filing a demand letter; you are entering an institution that, at its origin, was a chapel as much as a court, and that even now retains the form of a petition. The petition has a shape. Honor the shape.

The shape, the Psalmist tells us, is the embrace. Mercy meets truth; justice kisses peace. The prayer for relief is the place in the lawsuit where the lawyer practices that embrace publicly. He asks for the relief that is true to the wrong done — not less, not more — and he asks for it in a form that opens toward peace. He does not ask for the destruction of the defendant; he asks for the restoration of the plaintiff. He does not ask for vengeance; he asks for the remedy that allows the parties, after this is over, to live in the same town. There is a discipline of the imagination required for this. Most lawyers, under client pressure, draft prayers that prosecute. The equitable lawyer drafts prayers that heal.

Consider what this means in a particular case. The contract has been breached; the damages are quantifiable; the client wants every cent. You can plead it that way, and you may have to. But the prayer for relief is also the place where you ask whether specific performance would actually serve your client better than money, whether a constructive trust would protect what damages would only paper over, whether an accounting would establish a baseline that prevents the next dispute. These are equitable remedies. They are remedies of the imagination, fashioned by chancellors over centuries because the common-law remedy of damages, by itself, often fails to do what justice in the case requires. The lawyer who knows them, and who knows when to ask for them, is the lawyer who can pray for the kind of relief the case actually needs.

Pray your prayers for relief carefully this week. The form has a memory you should not lose.`,
    prayer: `God of mercy and truth, teach me to ask in the courts as I ask in prayer: with the truth of the case held open, with the mercy of the remedy in view, and with the peace that ought to follow the judgment never far from my hand. Let my prayers for relief be honest petitions, not demands. Amen.`,
    prompt: `Of the relief you are about to request, which clause is true to the wrong, and which is only your client's appetite?`,
  },
  {
    day: 20,
    date: "01-20",
    weekNumber: 3,
    weekArc: "Equity",
    weekArcLatin: "Aequitas",
    title: "The merciful judge who still upholds the law",
    scripture: {
      reference: "Luke 6:36-38",
      text: "Be ye therefore merciful, as your Father also is merciful. Judge not, and you shall not be judged. Condemn not, and you shall not be condemned. Forgive, and you shall be forgiven. Give, and it shall be given to you: good measure, and pressed down and shaken together, and running over shall they give into your bosom. For with the same measure that you shall mete withal, it shall be measured to you again.",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae II-II, q. 120, a. 1 (trans. Fathers of the English Dominican Province, 1920)",
      text: "As stated above, when we were treating of laws, since human actions, with which laws are concerned, are composed of contingent singulars and are innumerable in their diversity, it was not possible to lay down rules of law that would apply to every single case. Legislators in framing laws attend to what commonly happens, although if the law be applied to certain cases it will frustrate the equality of justice and be contrary to the common good, which the law has in view. Thus the law requires deposits to be restored, because in the majority of cases this is just. Yet it happens sometimes to be injurious, for instance, if a madman were to put his sword in deposit, and demand its delivery while in a state of madness, or if a man were to seek the return of his deposit in order to fight against his country. In these and like cases it is bad to follow the law, and it is good to set aside the letter of the law and to follow the dictates of justice and the common good. This is the object of epieikeia which we call equity.",
    },
    meditation: `Aquinas gives the famous example. A friend has left his sword with you for safekeeping. He returns one day, raging — perhaps mad, perhaps drunk, perhaps possessed by some grievance that has lost its proportion — and demands the sword back. The law says: restore deposits. The law has no exceptions for moods. And yet to hand him the sword is to make yourself the proximate cause of whatever he does with it. Equity, in this case, is the refusal to hand back the sword. It is not a violation of the law; it is, Aquinas says, the law's own intention rightly perceived. The lawgiver, had he foreseen this case, would have written the exception in. The exception is implicit in the purpose of the rule.

The merciful judge stands daily in this position. He is asked to apply rules that were drafted, sensibly, for the average case. He sees, in front of him, the case the rule did not foresee. He has to decide whether to hand back the sword. The Lord's command in Luke is not, as a lazy reading sometimes takes it, a counsel against judging at all. "Judge not, and you shall not be judged" is spoken to disciples in a moral context, not to officers of a court. The judge of a misdemeanor docket is required by his oath to judge. The question is what kind of judge. Christ's answer is precise: be merciful, as your Father also is merciful. Merciful, not lax. Merciful, not abolitionist. Merciful, in the way that the Father's mercy does not undo His justice but completes it.

Consider what this looks like in a sentencing. The guidelines yield a number. The number is the product of a calculation done by a commission with no knowledge of this defendant, refined by amendments lobbied for by interests that may have nothing to do with him, applied by a probation officer whose report was drafted in an hour. The number is a sword the rule asks the judge to return. Sometimes the number is right; the guidelines exist for a reason; most cases fit reasonably well within the band. Sometimes the number is wrong, and the judge can see, from the bench, that handing it back will be the proximate cause of harm the rule never intended. The merciful judge departs from the guideline. He writes the departure into the record, in language that other judges can read, so that the departure does not become an arbitrariness but a contribution to the slow growth of the law's conscience. He upholds the law by refusing the law's own miscalculation.

You may not be a judge. Most readers will not be. But you stand at sentencing on behalf of someone — defendant, victim, prosecutor's office, parole board, employer considering whether to fire — and the position you take influences what the merciful judge will do. The Christian advocate at sentencing has a particular calling, which is to tell the court the things the guideline cannot know. The defendant's childhood. The mother in the hospital. The job that is waiting if the sentence is short. The pattern of cooperation. The remorse that is real and the remorse that is performed. The cookie-cutter sentencing memorandum is a betrayal here. The guidelines have already supplied the cookie cutter; what the court needs from you is the case, written in enough detail that the judge has something to be merciful with. Mercy without information is the chancellor's foot we feared yesterday. Mercy with information is the discipline of equity at work.

Luke pushes the discipline further: "with the same measure that you shall mete withal, it shall be measured to you again." It is one of the few places where the Gospel makes the legal mind shudder. The measure with which you measure others will be the measure brought to you. The judge who sentences without imagination will be sentenced without imagination. The prosecutor who charges to the maximum without inquiry will be charged to the maximum without inquiry. The advocate who fails to plead the human details of his client will, on a day he hopes will never come, find that no one is pleading the human details of him. The verse is terrifying because it is true. The legal life is not insulated from the moral economy of mercy; it is one of the places that economy is most visibly enacted, and the mercy you spend on your hardest cases is the mercy you are storing up for your own.

Aquinas's sword example contains a discipline against sentimentality, which the merciful judge needs as much as he needs the courage to bend. The discipline is this: mercy is not the same as the wish to be liked, nor the same as the avoidance of difficult outcomes. The mercy of refusing the sword is, for the lender, a hard mercy; he will leave the house angry and may never speak to you again. The mercy of a downward departure may be experienced by the victim as a betrayal, and the merciful judge owes the victim an account of why the law in this case asked something other than what its number said. Mercy that costs nothing is not yet mercy. Mercy that costs the merciful something — the friendship, the easy ruling, the appeal — is mercy that participates, in some small measure, in the costly mercy of the Father, who did not save the world by waiving its laws but by satisfying them in His Son.

Be merciful, as your Father also is merciful. The verb is imperative because the disposition is one we will not arrive at by accident. The pressures of the docket, the pull of the metric, the appetite for the clean case — these will form a different disposition unless we resist. The form of resistance is small: a sentencing memorandum that takes an extra evening, a question to the probation officer that takes an extra phone call, a willingness to depart from the boilerplate when the boilerplate is the sword the case asked you to return. The merciful judge is built in these small acts. So is the merciful advocate.`,
    prayer: `Merciful Father, when I sit, or stand, in any seat of judgment today, give me the imagination to see the case the rule did not foresee. Let me uphold the law by refusing its miscalculations, and let the measure I bring to others be the measure I would willingly receive. Make me costly in my mercy and faithful in my judgment. Amen.`,
    prompt: `Whose sword have you been about to hand back without asking first what they intend to do with it?`,
  },
  {
    day: 21,
    date: "01-21",
    weekNumber: 3,
    weekArc: "Equity",
    weekArcLatin: "Aequitas",
    title: "The negotiation table as a court of conscience",
    scripture: {
      reference: "James 2:13",
      text: "For judgment without mercy to him that hath not done mercy. And mercy exalteth itself above judgment.",
    },
    excerpt: {
      author: "Marcus Tullius Cicero",
      citation: "De Officiis I.10.33 (trans. Walter Miller, Loeb Classical Library, 1913; public domain in US)",
      text: "Injustices often arise also through chicanery, that is, through an over-subtle and even fraudulent construction of the law. This it is that gave rise to the now familiar saw, 'More law, less justice.' Through such interpretation also a great deal of wrong is committed in transactions between state and state; thus, when a truce had been made with the enemy for thirty days, a famous general went to ravaging their fields by night, because, he said, the truce stipulated 'days,' not nights. Not even our own countryman's action is to be commended, if what is told of Quintus Fabius Labeo is true.... Such sharp practice is, therefore, in my opinion, not to be approved.",
    },
    meditation: `The negotiation table is the last private court most of your cases will ever see. The litigated case is the exception; the settled case is the rule. Most of the work you do for clients will end not with a verdict but with a signed agreement, drafted late, often in a windowless conference room or on a phone call between two tired lawyers, after the discovery has dragged on too long and the trial date is too close and everyone wants to be done. The agreement will not be reviewed by a judge. It will not be examined by a jury. It will become, between these parties, the law that governs their continued life. The negotiation table is, in this sense, a court of conscience. The chancellor sitting at it is you.

Cicero saw, two thousand years ago, what your week will see in miniature. "Injustices often arise also through chicanery, that is, through an over-subtle and even fraudulent construction of the law." The famous general makes a thirty-day truce and ravages the enemy fields by night, on the technicality that the truce spoke of "days." The text is on his side. The conscience is not. Cicero's verdict is unsparing: such sharp practice, he says, is not to be approved. The proverb he is quoting — summum ius summa iniuria, here in its early form "more law, less justice" — names exactly the temptation the negotiation table puts in front of the careful lawyer.

The temptation is sharper at the table than in the courtroom, because at the table there is no judge to stop you. If you draft an indemnity clause that the other side does not quite understand, the court will not catch it; it will only be discovered, perhaps years later, when the indemnification is triggered and the other party realizes what they signed. If you slip a release of unknown claims into the boilerplate of a settlement, the plaintiff who signed it may not learn what she gave up until she tries, later, to bring the claim she never knew she had. If you negotiate against an unrepresented party — a homeowner, a small contractor, a domestic-violence victim trying to settle a civil matter alongside the criminal case — you have, in effect, become both advocate and chancellor. There is no one else in the room with the legal training to see what you are doing. You are not only the one who can take advantage; you are the only one who can refuse to.

James, with his characteristic bluntness, frames the stakes theologically. "For judgment without mercy to him that hath not done mercy. And mercy exalteth itself above judgment." The verse is sometimes read as a simple promise that the merciful will be treated mercifully and the unmerciful will not. That is part of it. But the second sentence is more striking: mercy exalts itself above judgment. The Greek verb is one of triumph; mercy stands taller than judgment, mercy wins. James is not saying that mercy abolishes judgment. He is saying that, in the final accounting, the merciful action carries a weight the judgmental action does not. The merciful clause in your settlement agreement is louder, before God, than the clever clause. You will not see this in the metrics. You will see it, perhaps, in a stillness that comes when you close the file and know that you did not have to add a sentence to be ashamed of.

Equity at the table looks like several specific habits. It looks like reading the agreement back in the voice of the other party. Does this paragraph mean what you would want it to mean if you were on the other side? It looks like distinguishing the leverage that the case actually gives you from the leverage that the other party's ignorance, exhaustion, or unrepresented status gives you. The first is fair; the second is the chicanery Cicero condemned. It looks like the discipline of explanation: where a clause is unusual, where a waiver is consequential, where a release is broad, you say so plainly, and you give the other side a chance to understand it. You will sometimes lose, by this practice, a few sentences of advantage. You will also sleep.

Equity at the table looks, too, like the willingness to ask the question that lawyers are trained not to ask: what would be just? Lawyers are trained to ask what their client wants and how to maximize the chance of getting it. These are necessary questions; the lawyer who does not ask them is failing his client. But they are not the only questions. There is, somewhere in the night when the deal is almost done, a moment when the careful lawyer asks himself whether the agreement now on the table is something he could defend to a judge if a judge ever saw it, and beyond that, whether it is something he could defend to his confessor or to God. The settlement agreement is, after all, a creature he is bringing into the world. He owes it the same scrutiny he would owe a court order with his name on it.

The hour-billing structure makes this harder. The careful equity-shaped negotiation takes longer than the aggressive one; the client may not want to pay for the extra time, especially when the marginal hour seems to be benefiting the other side. You will have to learn to explain to your clients, when you can, that the settlement that is sharp will, over years, generate the disputes and the reputational damage and the spiritual residue that the merciful settlement will not. You will not always persuade them. But the duty to attempt the persuasion is part of your office. The advocate is not only the one who closes the deal. He is the one who refuses to close the deal that he knows, in the room, was reached by mercy hiding from itself.

Mercy exalteth itself above judgment. Bring it to the table today. The agreement you draft, the clause you decline to insert, the explanation you offer to the unrepresented party, the moment you stop and ask whether what you are about to do is true to the case — these are the chancery work of a profession that does most of its judgment in private. The week began with the rule that fails the case; it ends with the lawyer who, at the small table where most cases are decided, becomes himself the place where the rule remembers its purpose. Equity, in the end, is a name for the kind of person the law needs in the room.`,
    prayer: `Lord of the secret rooms, when I sit at the negotiation table today, sit there with me. Let me draft only what I could defend to You. Restrain me from the cleverness that costs the other party more than the case allows. Let mercy exalt itself above judgment in my hand, in my pen, and in my signature. Amen.`,
    prompt: `Which clause in your last settlement would you rewrite if the other side's lawyer had been as well-prepared as you?`,
  },
];
