import type { DevotionalDay } from "../types";

export const week35: DevotionalDay[] = [
  {
    day: 239,
    date: "08-27",
    weekNumber: 35,
    weekArc: "The Brief",
    weekArcLatin: "Memoriale",
    title: "Write the Vision, Make It Plain",
    scripture: {
      reference: "Habacuc 2:2",
      text: `And the Lord answered me, and said: Write the vision, and make it plain upon tables: that he that readeth it may run over it.`,
    },
    excerpt: {
      workId: "blackstone-commentaries",
      author: "William Blackstone",
      citation: "Commentaries on the Laws of England, Book III, ch. 20 (1768)",
      text: `The next step towards the decision of a cause is the pleading; or the mutual altercations between the plaintiff and defendant; which at present are set down and delivered into the proper office in writing, though formerly they were usually put in by their counsel ore tenus, or viva voce, in court, and then minuted down by the chief clerks, or prothonotaries. The first of these is the declaration, narratio, or count, anciently called the tale; in which the plaintiff sets forth his cause of complaint at length: being indeed only an amplification or exposition of the original writ upon which his action is founded, with the additional circumstances of time and place, when and where the injury was committed.`,
    },
    situationalTags: ["before-trial", "civic-amicus"],
  },
  {
    day: 240,
    date: "08-28",
    weekNumber: 35,
    weekArc: "The Brief",
    weekArcLatin: "Memoriale",
    title: "Blot Me Out of Thy Book",
    scripture: {
      reference: "Exodus 32:32",
      text: `Either forgive them this trespass, or if thou do not, strike me out of the book that thou hast written.`,
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae II-II, q.83, a.6",
      text: `It is lawful to desire the temporal goods of others, not indeed inordinately, but in due moderation: and in like manner it is lawful to ask in prayer for whatever it is lawful to desire. Moreover, the prayer whereby we ask something for others is called intercession. Now charity requires that we should ask not only for ourselves but also for others: wherefore Augustine says that the words of the Lord's Prayer prescribe to us not only to pray for ourselves, but also for others. For we say not "My Father" but "Our Father"; nor "give me," but "give us"; and so on with the other petitions. And Moses, by the very fact that he prayed to be blotted out of the book of life if his people were not spared, gives us an example of intercession written into the records of the people of God.`,
    },
    situationalTags: ["accepting-pro-bono", "arguing-against-conscience"],
  },
  {
    day: 241,
    date: "08-29",
    weekNumber: 35,
    weekArc: "The Brief",
    weekArcLatin: "Memoriale",
    title: "Baruch at the Scribe's Desk",
    scripture: {
      reference: "Jeremias 36:1-4",
      text: `And it came to pass in the fourth year of Joakim the son of Josias king of Juda, that this word came to Jeremias by the Lord, saying: Take thee a roll of a book, and thou shalt write in it all the words that I have spoken to thee against Israel and Juda, and against all the nations from the day that I spoke to thee, from the days of Josias even to this day. If so be, when the house of Juda shall hear all the evils that I purpose to do unto them, that they may return every man from his wicked way: and I will forgive their iniquity, and their sin. So Jeremias called Baruch the son of Nerias: and Baruch wrote from the mouth of Jeremias all the words of the Lord, which he spoke to him, upon the roll of a book.`,
    },
    excerpt: {
      author: "Augustine of Hippo",
      citation: "Confessions XI.3 (Pusey trans., 1838)",
      text: `Let me hear and understand how in the Beginning Thou madest the heaven and the earth. Moses wrote this; he wrote and departed, passed hence from Thee to Thee. Nor now is he before me; for if he were, I would hold him, and ask him, and beseech him by Thee, to open these things unto me, and would lay the ears of my body to the sounds bursting out of his mouth. But should he speak Hebrew, in vain would it strike on my senses, nor would aught of it touch my mind; but if Latin, I should know what he said. But whence should I know whether he spake truth? Yea, and if I knew this also, should I know it from him? Truly within me, within in the chamber of my thought, Truth, neither Hebrew, nor Greek, nor Latin, nor barbarian, without organs of voice or tongue, without sound of syllables, would say, He speaks truth.`,
    },
    situationalTags: ["11pm-still-at-office", "weekend-document-review"],
  },
  {
    day: 242,
    date: "08-30",
    weekNumber: 35,
    weekArc: "The Brief",
    weekArcLatin: "Memoriale",
    title: "My Tongue Is the Pen of a Ready Writer",
    scripture: {
      reference: "Psalm 44:1 (Vulgate; 45:1 Hebrew)",
      text: `My heart hath uttered a good word: I speak my works to the king; my tongue is the pen of a scrivener that writeth swiftly.`,
    },
    excerpt: {
      workId: "newman-idea",
      author: "John Henry Newman",
      citation: "The Idea of a University, Discourse VI (1852)",
      text: `That perfection of the Intellect, which is the result of Education, and its beau ideal, to be imparted to individuals in their respective measures, is the clear, calm, accurate vision and comprehension of all things, as far as the finite mind can embrace them, each in its place, and with its own characteristics upon it. It is almost prophetic from its knowledge of history; it is almost heart-searching from its knowledge of human nature; it has almost supernatural charity from its freedom from littleness and prejudice; it has almost the repose of faith, because nothing can startle it; it has almost the beauty and harmony of heavenly contemplation, so intimate is it with the eternal order of things and the music of the spheres.`,
    },
    situationalTags: ["forgetting-why-you-do-this", "gratitude-for-the-bar"],
  },
  {
    day: 243,
    date: "08-31",
    weekNumber: 35,
    weekArc: "The Brief",
    weekArcLatin: "Memoriale",
    title: "Write It in a Book for Ever",
    scripture: {
      reference: "Isaias 30:8",
      text: `Now therefore go in and write for them upon box, and note it diligently in a book, and it shall be in the latter days for a testimony for ever.`,
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae I, q.117, a.1",
      text: `As regards knowledge, a man pre-exists as a teacher in act, while the learner pre-exists as such only in potentiality. Thus the action of the teacher is to bring the learner from potentiality to act. Now the intelligible light together with the first principles is in us from God, and these are like the seedlings of all the knowledge subsequently acquired through the senses and through teaching. Wherefore a man is said to teach another inasmuch as, by signs, he manifests to that other the reasoning process which he himself goes through by his own natural reason. And thus, by the function of natural reason, one man may cause knowledge in another. So also, by the function of writing, the teacher manifests his thought to those who are absent in body and to those who come after him.`,
    },
    situationalTags: ["bar-committee", "civic-amicus"],
  },
  {
    day: 244,
    date: "09-01",
    weekNumber: 35,
    weekArc: "The Brief",
    weekArcLatin: "Memoriale",
    title: "Not One Jot, Not One Tittle",
    scripture: {
      reference: "Matthew 5:18",
      text: `For amen I say unto you, till heaven and earth pass, one jot, or one tittle shall not pass of the law, till all be fulfilled.`,
    },
    excerpt: {
      author: "Ambrose of Milan",
      citation: "De Officiis Ministrorum I.22.99 (tr. H. de Romestin, NPNF)",
      text: `It is right, then, to guard against many things even in our words, lest they fall from us unadvisedly; for a word once uttered, like a stone thrown from the hand, cannot be brought back again. Whence also we may well admire the saying of David: I said, I will take heed unto my ways, that I sin not with my tongue. For he knew that the natural restraint upon our words consists in silence, and the natural exercise of them, in speech. He therefore as a teacher of virtue, knowing that for the most part we offend by speech, thought silence to be the best remedy. And not without reason did he set a guard over his words, lest by speaking he should fall into sin. Let us, then, guard our heart, guard our tongue, both of them. For in both we may sin.`,
    },
    situationalTags: ["discovery-response-borderline", "young-associate-mistake"],
  },
  {
    day: 245,
    date: "09-02",
    weekNumber: 35,
    weekArc: "The Brief",
    weekArcLatin: "Memoriale",
    title: "Many Other Things Also Which Jesus Did",
    scripture: {
      reference: "John 21:25",
      text: `But there are also many other things which Jesus did; which, if they were written every one, the world itself, I think, would not be able to contain the books that should be written.`,
    },
    excerpt: {
      author: "John Henry Newman",
      citation: "Parochial and Plain Sermons, Vol. II, Sermon 18 (1835)",
      text: `It cannot be supposed that the Apostles and their immediate disciples conducted their teaching on a different principle from those who came after them. The whole tenor of Scripture leads us to conclude that they too taught by word of mouth as well as by writing. Scripture, on the other hand, is the record of these truths, the standard of them, the test of them, the storehouse of them; not, perhaps, the originator of them in the mind of the individual, but the divine ratification of what has been received. And hence the duty of careful study, the duty of patient meditation, the duty of submitting one's reasoning to its plain words; for though much is left untold, that which is told is told for ever, and binds the conscience of all who read.`,
    },
    situationalTags: ["after-loss", "appeal-rejected"],
  },
];
