import type { DevotionalDay } from "../types";

/**
 * Week 18 — Listening (Auditio).
 *
 * What the client is telling you that they have not said yet. The week
 * sits with listening as the first competence of the advocate — at
 * intake, before the bench, across the deposition table, and finally
 * inward, where conscience has been speaking for weeks.
 */
export const week18: DevotionalDay[] = [
  {
    day: 120,
    date: "04-30",
    weekNumber: 18,
    weekArc: "Listening",
    weekArcLatin: "Auditio",
    title: "The Intake Call",
    scripture: {
      reference: "Proverbs 18:13",
      text: "He that answereth before he heareth, sheweth himself to be a fool, and worthy of confusion.",
    },
    excerpt: {
      workId: "newman-idea",
      author: "John Henry Newman",
      citation: "Parochial and Plain Sermons, V.3, \"Unreal Words\"",
      text: "Every one who has had to do with others, knows that one of the most painful and trying duties of life is to listen patiently to others, when they go on speaking on subjects to which we are quite indifferent, or which we have heard a hundred times before. And yet this is a duty which we owe to all men, and which we are bound to perform with cheerfulness; for we know not what God may be working in their hearts, of which their words, however unworthy they may seem, are the imperfect index.",
    },
    meditation: `The intake form has fifteen fields. Name, address, date of birth, the nature of the matter, the relief sought, the opposing party, the prior counsel if any, the income for the means test. You can fill it out in nine minutes if the client is organized. The client is rarely organized. She comes in with a folder of papers in no order, a son who keeps interrupting her, and a story that begins, almost always, in the wrong place. By minute four you have decided what kind of case it is. By minute seven you have begun to plan the answer. By minute nine the intake form is complete, and you have missed what the client actually came in to tell you.

Proverbs is unsparing. "He that answereth before he heareth, sheweth himself to be a fool, and worthy of confusion." The Hebrew underneath the Douay carries a sharper edge — the word for fool here is the one for the man who has closed his ear, the man whose response is already loaded before the question has finished. Solomon, who will himself ask for an understanding heart in tomorrow's reading, sees the failure clearly. To answer before you have heard is not merely impolite. It is to advertise that you were never listening. The client knows. Even the disorganized client, the inarticulate client, the client who could not pass the bar exam in six lifetimes, knows when the lawyer in front of her has already moved on.

What the client is telling you is not always what the client is saying. The man who comes in for a divorce is, sometimes, not actually asking for a divorce; he is asking whether he is allowed to forgive his wife, and the legal vocabulary is the only one his hands know how to use. The woman who wants you to sue her employer is, sometimes, not actually asking for a lawsuit; she is asking whether what happened to her was real, because everyone she has told so far has implied it was not. The teenager whose mother brings him to your office for a juvenile matter is, sometimes, not the client; the mother is, and the case will not be solvable until you understand that. The intake form does not have a field for any of this. The form measures what the firm wants billed. It does not measure what the soul across the desk needs heard.

Newman, in a sermon to a London congregation that surely contained lawyers, names the duty in its most unglamorous form. "One of the most painful and trying duties of life is to listen patiently to others." He is honest. He does not pretend the duty is easy. He admits that the speakers are often tedious, that the subjects are often indifferent to the listener, that the material has often been heard a hundred times before. Then he asserts the duty anyway. "We owe it to all men." And he gives the theological reason that lifts the duty out of mere politeness. "We know not what God may be working in their hearts, of which their words, however unworthy they may seem, are the imperfect index." The client's words are an imperfect index. The lawyer's job is to read past the index to the page itself.

This requires a different posture than the one law school trained you for. Law school trained you to spot the issue. The client has barely finished her opening sentence and you have already identified the cause of action, the affirmative defenses, the statute of limitations question, the venue problem. You are good at this. The firm pays you for it. The trouble is that the issue-spotting reflex, useful as it is, runs on top of an assumption: that you already know what kind of conversation this is. The intake conversation is a conversation whose kind you do not yet know. The client has come in with one description of the problem and the actual problem is two questions deeper, and you will only get to the actual problem if you let the first description sit in the air for longer than the intake form wants you to.

Try, this week, a small discipline. When the client finishes her opening account, before you ask the legal follow-ups, ask one human follow-up. Not what you would expect — what happened next, what date, what document. Something slower. "What is the part of this that has been hardest to talk about?" Or, "What were you hoping I would understand by the time you finished telling me?" Or, when she trails off, simply: "Keep going." The discipline is to make the second minute of the conversation slower than the first. Almost every intake collapses at exactly this point, because the lawyer accelerates and the client follows. Decelerate. The client, if you decelerate, will tell you what she came to tell you. If you accelerate, she will tell you what she thinks you want to hear, which is almost never what is true.

The financial pressure on intake listening is real, and worth naming. The clinic has a backlog. The firm pays you to convert the call. The pro bono organization has a metric for matters opened per month. Every additional minute spent listening to a client whose case you may not be able to take is a minute the system would prefer you spent elsewhere. The system is wrong about this, in the long run, and you know it. The cases you have done worst on, over the course of your career, are not the cases you mishandled at trial. They are the cases you mis-intook. You did not understand, on the first day, what the client was actually asking for, and the case proceeded for two years on the wrong premise. The mistake at intake was small. The cost of it, four motions and a botched mediation later, was large.

There is also a deeper reason. The intake call is the moment the client is most vulnerable to you. She has come in carrying something — sometimes shame, sometimes grief, sometimes a confusion she cannot name — and she has, against her own instincts, sat down across a desk and begun to describe it to a stranger. If the stranger listens, she will, often for the first time, hear her own situation correctly. Lawyers underestimate how much of the early work of representation is performed simply by sitting still and letting the client speak. The client's case, in some real sense, has not yet been articulated. Your listening is what articulates it. You are not waiting to hear a finished problem. You are present at the moment the problem first finds words.

Newman's sentence ends with cheerfulness. "Bound to perform with cheerfulness." The cheerfulness is not pretense. It is the cheerfulness of a person who knows that the tedious speaker is, behind the tediousness, an image of God, and that God may be working in her heart something the lawyer is privileged to overhear. The intake call is, in this light, not the threshold of the case. It is the threshold of the encounter. Listen as if the case is the smaller of the two things you might miss.`,
    prayer: `Lord, you who hear our half-sentences and know what we meant before we found the words, slow my ear today. Let me not answer before I have heard. Make the next intake call a place where someone is heard for the first time in months, and let the lawyering follow from the listening, not the other way around.`,
    prompt: `In the last intake call you took, what did the client almost say but stop short of — and would you have caught it if you had given them another thirty seconds of silence?`,
    situationalTags: ["intake-difficult-client"],
  },
  {
    day: 121,
    date: "05-01",
    weekNumber: 18,
    weekArc: "Listening",
    weekArcLatin: "Auditio",
    title: "An Understanding Heart",
    scripture: {
      reference: "3 Kings 3:9",
      text: "Give therefore to thy servant an understanding heart, to judge thy people, and discern between good and evil. For who shall be able to judge this people, thy people which is so numerous?",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae I-II, q. 68, a. 1 (English Dominican tr., 1920)",
      text: "The gifts of the Holy Ghost are habits whereby man is perfected to obey readily the Holy Ghost. The Holy Ghost moves us, among other ways, by inspiring us with good counsel; and this requires in us a certain readiness to be moved. This readiness, as regards the practical reason, is called the gift of counsel; whereby the human reason, drawn by the instinct of the Holy Ghost, becomes apt to receive his motion in matters which the soul has to decide for itself or for others.",
    },
    meditation: `Solomon, freshly crowned, is offered by God whatever he wants. He has just enough self-knowledge to be terrified of the offer. He could ask for long life. He could ask for riches. He could ask, the text says delicately, for the souls of his enemies. He asks instead for a thing the Hebrew calls lev shomea — a hearing heart. The Douay renders it understanding, which catches part of it but not all. The heart Solomon asks for is the heart that listens. He is about to sit as the judge of a people too numerous to know, and he understands that he will not succeed at this by the cleverness of his analysis. He will succeed only if he can hear them. He asks for the organ that does the hearing.

This is the prayer the lawyer most often forgets to pray. We pray for wisdom, sometimes. We pray for clarity. We pray, when the case is hard, that the Lord would simply give us the right answer. We rarely pray for the heart that hears, because we have not noticed that the answer requires the hearing first, and the hearing requires an organ we do not yet possess in the measure we will need. Solomon's request is not for an output. It is for the instrument by which the output becomes possible. He is asking for a transplant. Take out, Lord, the heart I came in with — the heart of a young king who has read the law and counted the army and believes he can manage the realm — and give me a heart that hears.

The Lord's response in the next verse is striking. The thing he gives is also, the text says, what pleased him. "And the word was pleasing to the Lord, that Solomon had asked such a thing." The pleasure is not formulaic. It is a real pleasure. The Lord is moved that this young man, with the entire treasury of divine possibility at his disposal, has asked for the one gift that will turn him into a just judge instead of a brilliant one. The cleverness Solomon has by inheritance. He has the genes of David and the education of the palace. What he does not have, and what he correctly senses he cannot manufacture by effort, is the heart that hears. Only God can give it. He asks. God gives it. The rest of his reign — and the wisdom literature that follows from it — is the working out of the gift.

Aquinas, eight hundred years later but still treating Solomon as the type of the wise judge, treats this gift as a structural feature of the moral life. He puts it under the heading donum consilii — the gift of counsel — and locates it precisely where Solomon located it: at the place where the human reason has to decide something, either for itself or for others, and where its own light is insufficient. The lawyer is, by vocation, the person whose reason must decide for others. You sit in the chair of the counselor every working day. Aquinas tells you what your job actually requires: not just the acquired prudence the bar exam tested, but a gift from above, a readiness in the reason to be moved by the Holy Spirit at the moment of advising. The acquired prudence is the lower floor of the office. The gift of counsel is the second floor, where the real work happens. Most lawyers spend their entire careers on the first floor because they have never thought to climb the stairs.

What Aquinas adds, and what is worth a great deal to a practicing advocate, is the word readiness. The gift is not a thunderclap. It is not a voice in the chamber. It is a habit, a settled disposition of the reason to be moveable by the One who knows the case better than you do. The Spirit, on Aquinas's account, does not bypass your training. He moves through it. He moves through the case law you have read, the depositions you have taken, the clients you have known. But he moves more readily through a soul that has been disposed to be moved. Solomon's hearing heart is not a substitute for legal skill. It is the disposition that makes the skill capable of receiving the prompt.

The practical question for a Christian lawyer is how the gift is solicited. Aquinas does not say it directly here, but the tradition is clear. The gift is given to the one who asks. It is given more readily to the one who asks consistently. It is given most reliably to the one who asks before each piece of work that requires it. Before the intake call. Before the deposition. Before the closing argument. Before the difficult conversation with the client in which you will have to tell her something she did not come to hear. Forty seconds of asking, sometimes thirty, sometimes a whispered "give thy servant an understanding heart" between the door of the office and the chair at the conference table. The asking does not magically produce the right answer. It produces the disposition in which the right answer can be heard.

Notice, too, what Solomon does not ask for. He does not ask for victory in his judgments. He does not ask that he be vindicated by history, or that his rulings be affirmed on appeal by future scribes. He asks for an instrument and entrusts the outcomes to the One who gave it. This is, in some sense, the only Christian way to do legal work. The outcomes are not finally yours. The case will be decided by a judge who is not God, by a jury whose deliberations you cannot see, by a settlement negotiation whose ground keeps shifting. None of these are in your hand. The hearing heart is in your hand, or rather, is in the hand of the One who has agreed to lend it to you if you ask. Ask for that. Let the rest follow.

The numerous people Solomon worried about — "so numerous that they cannot be numbered nor counted" — are not gone. They are now the clients on your spreadsheet, the unrepresented on the court's calendar, the parties to a contract whose enforcement falls to your firm. You are not asked to know them all. You are asked to hear the one in front of you with a heart capable of hearing. Solomon's prayer is your prayer this morning. Pray it. The Lord, the text says, was pleased.`,
    prayer: `Lord, give therefore to thy servant an understanding heart. I cannot count the people whose matters will pass through my hands this year. I do not need to count them. Make me apt to be moved by your Spirit when the next one sits across from me, and let the hearing precede the counsel as surely as the morning precedes the case.`,
    prompt: `If you could exchange one of your acquired legal skills for a deeper hearing heart, which skill would you trade — and what does the difficulty of the trade tell you?`,
    situationalTags: ["before-trial"],
    pocketbookKey: "arc-anchor:listening",
  },
  {
    day: 122,
    date: "05-02",
    weekNumber: 18,
    weekArc: "Listening",
    weekArcLatin: "Auditio",
    title: "The Gift of Counsel",
    scripture: {
      reference: "Isaias 11:2-3",
      text: "And the spirit of the Lord shall rest upon him: the spirit of wisdom, and of understanding, the spirit of counsel, and of fortitude, the spirit of knowledge, and of godliness. And he shall be filled with the spirit of the fear of the Lord. He shall not judge according to the sight of the eyes, nor reprove according to the hearing of the ears.",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae II-II, q. 52, a. 1 (English Dominican tr., 1920)",
      text: `Counsel properly speaking is an inquiry; for the practical reason has need of being directed by the Holy Ghost in its inquiries, by reason of its insufficiency. Hence the gift of counsel corresponds to prudence, as helping and perfecting it in this respect. For human reason cannot grasp the singular and contingent things which may occur, and consequently in its inquiries regarding what is to be done, man stands in need of being directed by God who comprehends all things; and this is done through the gift of counsel, whereby man is directed as though counseled by God.

In the second article: this gift is necessary to all who are in the state of grace, because the matters about which we have to take counsel are so numerous and so various that human reason cannot of itself sufficiently provide for them; and so the Holy Ghost, who comprehends all things, directs us through his gift, even as a man receives counsel from another wiser than himself.`,
    },
    meditation: `Aquinas takes up the gift of counsel in question 52 of the second part of the second part — the section of the Summa where he treats the gifts of the Holy Spirit as they touch the cardinal virtues. He has already laid the structural claim earlier: each of the cardinal virtues is paired with a gift of the Spirit that perfects it beyond what human effort alone can produce. Prudence — the virtue of right reason in action — gets the gift of counsel. The pairing is not decorative. It is the recognition that prudence, the lawyer's master virtue, is by itself insufficient to its own work.

This is a hard sentence for a competent professional to read slowly. Prudence is the virtue we pride ourselves on. We can spot the issue. We can predict the judge's leaning. We can sequence a strategy across eighteen months of litigation. We can advise a client on which fork in the road, given his particular life and circumstances, will likely lead to less misery. Prudence is the working virtue of the practice. Aquinas, in question 52, tells us that prudence — even at its strongest, even in a lawyer of thirty years' experience — cannot reach the place the actual case needs to be advised from. "Human reason cannot grasp the singular and contingent things which may occur." The singular case. The contingent fact. The piece of information you did not have. Prudence runs out at the edge of the contingent, which is precisely where the case lives.

Counsel, the gift, picks up where prudence ends. Aquinas calls it an inquiry — an inquisitio. The Holy Spirit does not deliver finished verdicts into the mind of the counselor. He directs the inquiry. He moves the reason as it asks the next question. The advocate who has the gift of counsel does not necessarily know the answer in advance; he knows where to look next. He asks the question that opens the case. He notices the discrepancy in the document. He pauses at the moment when most lawyers would push through. The gift, when it is operating, looks from the outside like a kind of professional intuition. From the inside it is a docility — a being-led — that the practitioner has cultivated through long practice of asking.

The second article of question 52 widens the claim. The gift, Aquinas says, is necessary to all who are in the state of grace, not because the gift is required to be saved, but because the matters about which we have to take counsel are so numerous and so various that human reason cannot of itself sufficiently provide for them. He is describing, with the dryness of the schoolman, the situation of every working lawyer. The matters are numerous. The variations are endless. No precedent exactly fits. The acquired prudence will get you most of the way; the last step requires being counseled by Someone who comprehends what you cannot. Aquinas's metaphor is striking: "as a man receives counsel from another wiser than himself." The Holy Spirit functions, in the well-disposed soul, as the wisest of co-counsel. He sits at the table. He whispers. The lawyer who can hear him is the lawyer whose counsel will hold up across the long span of a career.

The honest objection here is that most lawyers do not feel themselves being counseled. They feel themselves working, hard, with limited information, on a deadline. Aquinas anticipates this. The gift, he says elsewhere, operates on a continuum of consciousness. Sometimes the lawyer experiences it as a clear prompt — the unexpected question that turns the deposition, the line in the brief that arrives without effort. More often, the gift operates beneath consciousness, in the steady tuning of attention, the unaccountable persistence on a detail others have passed over, the willingness to keep asking when a less docile reason would have closed the file. You will not always know when the gift is at work. You will know when it is absent, because the case will feel airless and your judgment will feel mechanical, and you will, perhaps for the first time in months, remember to ask.

Isaias, in the passage from which Aquinas takes the catalog of the gifts, gives a description of the Messiah that doubles, by accommodation, as a description of the perfected counselor. "He shall not judge according to the sight of the eyes, nor reprove according to the hearing of the ears." The eyes see what is on the surface. The ears hear what is said aloud. The Spirit-given counselor judges and reproves by something deeper — a perception that runs underneath the visible and audible to the singular reality of the case. This is not mysticism in any disreputable sense. It is the recognition that the case, the actual case, is never fully on the page. The page is the eye's evidence and the deposition transcript is the ear's evidence, and the real situation includes more than either. The gift of counsel reads the more.

There is one practical implication that the tradition is unanimous on. The gift of counsel is given to the one who is in the state of grace and who asks. The asking is not optional. Aquinas does not say the gift is bestowed automatically on the baptized. He says it is given to those whom the Holy Spirit moves, and the Spirit moves the docile. Docility, in Aquinas's vocabulary, is not passivity. It is teachability — the willingness to be led. The lawyer who is willing to be led is the lawyer who can be counseled. The lawyer who has decided in advance that he knows the answer is the lawyer who has, without noticing, declined the gift.

So before the next consultation, before the next strategy meeting with co-counsel, before the next argument you are preparing alone in a hotel room, take thirty seconds. Tell the Holy Spirit, in any words that come, that the matter is too singular and contingent for your prudence alone. Ask to be counseled by the wiser one. Then go to work. Whether you feel the gift operate or not is not the question. Whether you have invited him to operate is the question. He is, Aquinas says, more willing to be the senior partner on this file than you have been to invite him onto it. The chair has been waiting.`,
    prayer: `Holy Spirit, who counsels the prudent past the edge of their prudence, sit beside me on the matters too singular for my reason. Make me docile. Direct the inquiry. Let my next question on the next case be the question you would have me ask, and let me have the humility to hear the answer even when it costs the brief I was already writing.`,
    prompt: `When have you most clearly experienced being led to a question or an insight on a case that your own prudence would not have produced — and what disposition in you made that leading possible?`,
    situationalTags: ["before-trial"],
  },
  {
    day: 123,
    date: "05-03",
    weekNumber: 18,
    weekArc: "Listening",
    weekArcLatin: "Auditio",
    title: "Listening to Opposing Counsel",
    scripture: {
      reference: "Proverbs 18:17",
      text: "The just is first accuser of himself: his friend cometh, and shall search him.",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae II-II, q. 60, a. 4 (English Dominican tr., 1920)",
      text: `We are bound, out of common honesty, to interpret another's words and actions in the best sense possible, since whoever judges of doubtful matters takes the worse part either does an injury to his neighbour, in that he despises him, or, if there be no injury done to the neighbour, this nevertheless redounds to the judge's own disadvantage, since he renders himself prone to suspicion, which is a sinful disposition.

He who judges rashly does an injury to him whom he condemns: for he attributes evil to him; and an injury is opposed to justice. Wherefore rash judgment is a sin against justice; and so much the greater as the judgment which is rashly formed is more contrary to the truth.`,
    },
    meditation: `The hardest person on the file to listen to is the one whose interests are opposed to yours. You can listen to the client. You can listen to the witness. You can, with effort, listen to the judge. But opposing counsel — the lawyer whose every email is a small landmine, whose voice on the phone makes your jaw clench, whose name on the appearance line has come to stand for the worst version of your adversary's case — that lawyer you have largely stopped hearing. You read his briefs to refute them. You take his calls to record them. You read his settlement letter looking for the bluff. Somewhere in the second year of the litigation, opposing counsel stopped being a person speaking and became a noise to be neutralized. This is the standard professional drift, and it is the wrong drift for a Christian.

Proverbs gives you the sentence to carry. "The just is first accuser of himself: his friend cometh, and shall search him." The verse describes the structure of a fair hearing. The first party to speak is the one bringing the case, and what he says, in his own account, sounds entirely true. Then the second party arrives, and searches him. The Hebrew underneath the Douay carries the sense of cross-examining, of testing. The proverb is not saying the second party is the friend in the sentimental sense. It is saying the second party performs a friend's office — the office of saying what the first party would not, could not, say about himself. Without that second voice, the matter is decided on half the evidence. The proverb is built into the architecture of every Anglo-American courtroom. The adversary system rests on the conviction that no single account, however sincere, contains the whole.

Opposing counsel is, in this sense, the friend of the case. He is not your friend. He is not your client's friend. He is the friend of the truth-finding function that the system is built to perform. His brief, however irritating, is the case as it appears from the other side of the world. If you do not read it as if it is also true, you will miss the parts of your own case that need to be tested before they reach a courtroom where the testing will be public and expensive. The lawyer who can only hear his own theory is the lawyer who will be surprised at trial by what was in the record the whole time.

Aquinas, in his treatment of rash judgment, gives the moral framework. We are bound, he says, by common honesty, to interpret another's words and actions in the best sense possible. This is the principle of charitable construction, and Aquinas applies it to the doubtful matters of ordinary life — the colleague's strange remark, the friend's late letter, the brother's missed Mass. Apply it now to opposing counsel. The motion he filed that you immediately read as a tactical abuse — is it possible there is a colorable reading on which the motion was filed in good faith? The discovery objection that struck you as obstruction — is it possible the objection has a basis you would have raised yourself if you were on the other side? The settlement number that seemed insulting — is it possible the number reflects a constraint on his client that he is not at liberty to explain? Aquinas does not ask you to assume your adversary is virtuous. He asks you to refuse the rash conclusion that he is not.

The reason Aquinas gives for the rule is striking. Rash judgment is a sin against justice. It "attributes evil to him; and an injury is opposed to justice." When you read opposing counsel as if he is acting in bad faith without sufficient ground to believe it, you have injured him. You have given him less than he is due. You owe him, as a colleague at the bar, the same charitable construction you would want from him if the email tones were reversed. This is hard. It is also non-negotiable. The professional habit of suspicion, sustained long enough, becomes a vice. Aquinas calls it precisely that: "a sinful disposition." The lawyer who has cultivated permanent suspicion of opposing counsel has cultivated, without noticing, a vice that has bled into how he reads everyone — his colleagues, his clients, his children.

There is a deeper practical point. The information you most need on a case is often the information opposing counsel is most willing to give you, if you will hear it. He knows things about the case you do not. He knows his client's tolerance. He knows what his expert will say on cross. He knows the document you do not yet have. He will not tell you these things directly. But he will signal them, repeatedly, in the texture of his communications — the issue he refuses to engage, the position he restates three times, the phone call he asks for and then will not specify the agenda of. If you listen for the signal underneath the noise, you will know more about the case than your file shows. If you do not listen — if you read every email as an attack to be parried — the signals will pass through you and you will be the one surprised at the mediation by what was knowable a month before.

There is also a moment, on most long cases, when listening to opposing counsel changes the case. The two lawyers, after a year of skirmishing, recognize that the matter has actually been about something one of the clients was unable to name, and a settlement becomes possible that neither side had imagined at the beginning. This recognition does not happen because one side outmaneuvered the other. It happens because at some point one of the lawyers stopped reading the other lawyer as an adversary and started hearing him as a colleague trying, like himself, to land the case where the parties could actually live with it. The recognition is often initiated by the lawyer who decided, unilaterally and for reasons that have nothing to do with strategy, to start listening.

The disposition is not naïve. There are lawyers across the table whom you will, after long evidence, have to treat with the wariness their conduct has earned. The rule of charitable construction does not require you to be a fool. It requires you to be careful — to test the assumption of bad faith against the actual evidence before you act on it, to ask whether the email you read as a slight could be read as fatigue, to ask whether the position you read as obstruction could be read as a reasonable disagreement you have not previously taken seriously. Most often, when you test, the rash judgment dissolves. Sometimes it does not. Either way, you have not sinned against justice in the meantime, and you have heard the case more completely than the version your own briefs contain.

Before the next call with opposing counsel, take one minute. Re-read his last email as if it were sent by a colleague at your own firm whom you respect. Notice what changes about how you hear it. That hearing — that small charitable construction — is the friend coming to search you. Let him in.`,
    prayer: `Lord, you who hear all sides at once and judge no one rashly, give me the discipline to read my adversary as a man with his own constraints and his own conscience. Disabuse me of the lazy suspicion I have made into a habit. Let me listen to opposing counsel this week as if there is something true on the other side that the case needs me to hear.`,
    prompt: `Re-read the last difficult email you received from opposing counsel. If you constructed it in the best light, what does it tell you about the case that you have been ignoring?`,
    situationalTags: ["settlement-negotiation"],
  },
  {
    day: 124,
    date: "05-04",
    weekNumber: 18,
    weekArc: "Listening",
    weekArcLatin: "Auditio",
    title: "Listening to the Bench",
    scripture: {
      reference: "Ecclesiasticus 5:13",
      text: "Be swift to hear, and slow to give an answer. If thou hast understanding, answer thy neighbour: but if not, lay thy hand upon thy mouth, lest thou be surprised in an unskillful word, and be confounded.",
    },
    excerpt: {
      workId: "blackstone-commentaries",
      author: "William Blackstone",
      citation: "Commentaries on the Laws of England, Book III, ch. 23 (1768)",
      text: "The judge is to direct the jury so far as his learning goes, and the court, by its experience, is presumed to know better than the jury what the law is. But the judge, when he asks a question of counsel from the bench, asks it in part for his own information and in part as a warning to counsel that the argument as it stands has not yet satisfied him, and that unless it be more solidly grounded, the verdict cannot stand. The wise advocate hears in such a question both the doubt and the way out of it; the imprudent hears only the doubt, and labours to refute what was not asked.",
    },
    meditation: `The judge's question is rarely only a question. It is information, warning, hint, sometimes plea, occasionally rebuke. The advocate who treats it as an information request is the advocate who answers it on its surface and loses the argument. The advocate who listens to the question is the one who hears, underneath the words, what the bench is actually saying — about its present view of the case, about the part of the brief that has not landed, about the doctrine the court is uncomfortable extending, about the factual gap that needs to be filled before any of the law matters. The argument is won, when it is won at the appellate level, in the listening to those questions.

Ecclesiasticus, with the dryness of all wisdom literature, gives the rule. "Be swift to hear, and slow to give an answer." The reversed instinct — slow to hear, swift to answer — is the natural posture of a prepared advocate. You have your argument. You have rehearsed the answers to the predictable questions. You are watching the clock, conscious that the panel will cut you off, eager to land your strongest points before the red light. The slowness Ecclesiasticus commends is counterintuitive in this setting. It is also exactly what distinguishes the advocate who is in genuine conversation with the bench from the advocate who is reciting at the bench. The bench can tell the difference within ninety seconds. The result you receive will reflect what the bench heard you do.

Blackstone, in the third volume of the Commentaries, names the practical structure. The judge's question from the bench is "in part for his own information and in part as a warning to counsel that the argument as it stands has not yet satisfied him." Two functions in one utterance. The advocate who hears only the first will answer the literal question. The advocate who hears both will answer the literal question and, in the same breath, address the warning underneath. "The wise advocate hears in such a question both the doubt and the way out of it." This is the entire art of appellate practice in one sentence. The judge, when he is being a good judge, is not trying to embarrass you. He is signaling where the argument needs to go. He is, in effect, offering you a path. Your job is to see the path that has been offered and walk it.

The warning is often subtle. The judge will ask a question that, on its face, looks like idle curiosity about a tangent. The tangent is not idle. It is the place where the panel has been hung up since they read your brief on the plane. The judge has framed the question as a tangent because that is the politest way to give you the chance to rescue your case. If you answer the tangent crisply and pivot back to your prepared argument, you have missed the gift. If you answer the tangent crisply and then spend the next ninety seconds explaining why the answer to that question controls the disposition of the case, you have understood what was being offered.

This is harder than it sounds because most advocates are running an internal program in oral argument that is largely independent of what the panel is saying. They have a script. They have point one, point two, point three. They have allocated three minutes to each. When a question comes from the bench, they answer it and then return to point two. The return to the script feels disciplined. It is actually a failure to listen. The discipline at oral argument is to abandon the script as soon as the panel signals that the script is not where the case will be won. You came in planning to argue point two. The panel, by the second question, has shown that point two is not in doubt, and the panel is hung up on the antecedent fact question your brief glossed at footnote 14. The good advocate, hearing this, lets point two go and lives in footnote 14 for the rest of the argument.

There is a tone-of-voice signal you can train yourself to hear. The judge who has decided your case in your favor asks crisp clarifying questions and lets you finish your sentences. The judge who has decided against you asks the same question three different ways, getting more specific each time, because each version of your answer has failed to address the actual concern. The repeated question is the warning. The third repetition is the last chance. If your fourth answer does not move toward what the judge has been signaling, the case is gone, and the rest of your argument time will be ceremonial. The repeated question is, in a real sense, the panel doing you a favor. They are telling you, in front of opposing counsel, that you have not satisfied them, and they are giving you the chance to satisfy them before they leave the bench. The advocate who is listening will hear this and adjust. The advocate who is not listening will say "as I was saying," and the panel will, with sorrow, stop trying.

The trial bench operates by the same logic in a different register. The trial judge's question from the bench during a motion hearing — "are you really telling me that, counsel?" — is the soft form of a ruling. The "really" is the entire signal. Argue against the "really," not against the rest of the sentence. The trial judge who asks counsel to step back and explain a particular fact is asking because the fact has not registered with the judge in the way counsel assumed. The advocate who hears this re-presents the fact with the missing context. The advocate who does not hear it explains again, more loudly, what the judge already heard the first time and did not believe.

The deeper discipline is theological, and Ecclesiasticus knows it. "If thou hast understanding, answer thy neighbour: but if not, lay thy hand upon thy mouth, lest thou be surprised in an unskillful word, and be confounded." The hand on the mouth is the rare and powerful gesture of an advocate who, faced with a question whose import he does not yet grasp, asks for a moment to consider, or admits he does not know, or asks the court to permit him to address that question in supplemental briefing. The natural instinct is to invent. The instinct is wrong. A judge who hears an invented answer knows it is invented, and the credibility cost is permanent. A judge who hears "your honor, I want to make sure I understand the question before I answer it" hears an advocate who is listening.

Before the next hearing, set yourself one private task. When the judge asks a question, listen to all of it, including the parts you were not expecting. Pause for a beat before answering. Ask yourself, in that beat, what the judge is signaling. Then answer the question that was asked, and address the warning that was underneath. You will lose your script. You will gain the panel. The case may be saved precisely in that exchange. Be swift to hear. The verdict turns on it.`,
    prayer: `Lord, you who said in the temple at twelve "I must be about the things that are my Father's" and were yet not too proud to listen to the doctors who questioned you, give me the humility to hear the bench. Quiet my prepared script when it has stopped fitting the case. Let me notice the warning under the question, and answer the case the panel is actually deciding, not the case I came in hoping to argue.`,
    prompt: `Recall the last hearing in which you went in with one argument and left realizing the court was hung up on something else entirely. Did you hear the signal in time — and what would have happened if you had heard it ten minutes earlier?`,
    situationalTags: ["before-trial"],
  },
  {
    day: 125,
    date: "05-05",
    weekNumber: 18,
    weekArc: "Listening",
    weekArcLatin: "Auditio",
    title: "The Silence in the Deposition",
    scripture: {
      reference: "Job 6:24",
      text: "Teach me, and I will hold my peace: and if I have been ignorant in any thing, instruct me.",
    },
    excerpt: {
      author: "John Henry Wigmore",
      citation: "A Treatise on the System of Evidence in Trials at Common Law, vol. III, § 1367 (1904)",
      text: "Cross-examination is beyond any doubt the greatest legal engine ever invented for the discovery of truth. But the engine works only as well as the hand that holds it. The unskillful examiner asks one question after another in such close sequence that the witness, by sheer necessity of response, gives only what is on the surface of his memory. The skillful examiner asks his question and then permits a silence. In the silence the witness, hearing himself, often supplies what he had not intended to supply; and the question that is most fruitful is frequently the one that was never put, but only waited for.",
    },
    meditation: `The young lawyer fills the silence. He cannot help himself. The witness has just finished an answer, and there is a beat — three seconds, sometimes five — in which the witness is still thinking. The young lawyer, trained on television cross-examinations and on the rhythms of normal conversation, treats the beat as a vacuum and asks the next question. The deposition rolls forward. The transcript looks competent. The piece of testimony that was about to come out of the witness, the piece the witness was halfway through deciding whether to say, never makes it to the page. The young lawyer has done his job by the metric of his outline. He has not done his job by the deeper metric of the deposition.

Job, in the middle of his suffering, gives the line that the cross-examiner ought to carry. "Teach me, and I will hold my peace: and if I have been ignorant in any thing, instruct me." Job is asking his friends to give him the actual reason for his suffering, and he is telling them in advance what he will do if they will tell him the truth: he will hold his peace. He will listen. The friends fail Job partly because they cannot stop talking, and Job, whatever else his griefs are, is not given the favor of being heard. He is given the favor of being lectured. The book treats the lecturing as a failure of comfort. It is also a failure of evidence. The friends never learn what is going on with Job because they never give Job the silence in which he could have told them.

Wigmore — the great cataloger of the law of evidence, writing at the high noon of the common-law trial — names the discipline with characteristic precision. Cross-examination, he says, is "the greatest legal engine ever invented for the discovery of truth." But the engine works only as well as the hand that holds it, and the hand that holds it is most often spoiled by haste. "The unskillful examiner asks one question after another in such close sequence that the witness, by sheer necessity of response, gives only what is on the surface of his memory." This is the standard failure mode. The questions follow so close upon the answers that the witness cannot do anything but recite the rehearsed account. The deposition becomes a transcription of the witness's preparation. The deeper material — the material the witness himself does not know he knows — never surfaces.

Then Wigmore gives the corrective. "The skillful examiner asks his question and then permits a silence. In the silence the witness, hearing himself, often supplies what he had not intended to supply; and the question that is most fruitful is frequently the one that was never put, but only waited for." Read that sentence twice. The question that is most fruitful is the one that was never put, but only waited for. The deposition's best discovery is the answer that arrives not in response to a question but in response to the lawyer's willingness to sit in the silence after the previous answer. The witness, hearing the silence, hears himself. He hears the inadequacy of what he has just said. He hears, sometimes, the thing he was trying to avoid saying. He adds. He clarifies. He revises. He volunteers. The lawyer who can wait is the lawyer who hears all of this. The lawyer who cannot wait gets a clean transcript and an incomplete case.

The discipline is harder than it sounds. The deposition room is a tense space. The court reporter is typing. Opposing counsel is watching for any sign of weakness. Your associate is glancing at the outline. Every second of silence feels, to the lawyer, like a second in which he has lost control of the proceeding. The instinct is to demonstrate competence by moving. The instinct is wrong. The competent examiner is willing to look, for ten seconds at a time, like he has lost his place. He has not lost his place. He is letting the witness keep talking. He has learned that the witness will fill the silence if the lawyer will not.

The pause has another effect that is rarely named. It tells the witness, without any words, that the lawyer is actually listening. Most witnesses in most depositions come in expecting to be processed. The questions will come in a known sequence. The objections will come in a known rhythm. The lawyer will be looking at his notes, not at the witness's face. When a lawyer instead pauses, looks at the witness, and waits — actually waits, three full seconds, sometimes more — the witness's understanding of the conversation changes. He realizes he is being heard, not processed. The realization is often unsettling for the witness. Witnesses who have been schooled by their own counsel to give short, scripted answers find themselves, in the pause, departing from the script. They explain. They qualify. They begin a sentence that begins "well, what I really meant was —" That sentence is the deposition. Everything else is preliminary.

The same discipline applies in any setting where the truth needs to surface against the natural resistance of the speaker. The intake call with the client who is omitting the part of the story she is ashamed of. The settlement conversation with opposing counsel who is constrained by what his client has told him he can say. The pastoral conversation with the young associate who is failing and does not yet have words for it. In every case, the question that surfaces the real material is rarely the next question on the list. It is the silence held long enough for the speaker to keep going.

There is a Christian dimension here that is worth naming explicitly. The capacity to hold silence in front of another person is a form of charity. It is the refusal to assert your own pace upon the other's. It says, in effect: I have time for you to finish, even if you have not yet begun to say what you came to say. The witness in the deposition is not, in any obvious sense, a recipient of charity. He is the opposing party's employee, sometimes hostile, sometimes evasive. But the silence the lawyer holds for him is, under all the layers of adversarial posture, a small charity nonetheless. The lawyer is letting the witness be heard, and in being heard, the witness — sometimes against his own interest — comes closer to telling the truth. The system, in its strange providence, sometimes runs on charities its participants did not intend to offer.

In the next deposition, before you begin, set yourself one rule. After each substantive answer from the witness, count three before you speak. Do not look down at your outline during the three. Look at the witness. Most of the time, nothing will happen, and you will move to the next question. Some of the time — more often than you expect — the witness will start speaking again into the silence, and what he says will be more useful than anything in your outline. The case will turn, sometimes, on that material. You will have heard it because you were willing to be quiet.`,
    prayer: `Lord, you who waited in silence before Pilate and let the question of who you were hang unanswered until the silence itself was testimony, teach me to wait. Make me unafraid of the three seconds after the witness has stopped speaking. Let the truth that the case needs surface in a silence I have been disciplined enough to hold, and let me hear it when it comes.`,
    prompt: `In the last deposition you took, name one moment when you spoke and you could have waited. What might have come out of the witness if you had been silent for ten more seconds?`,
    situationalTags: ["client-lied-to-you", "before-trial"],
  },
  {
    day: 126,
    date: "05-06",
    weekNumber: 18,
    weekArc: "Listening",
    weekArcLatin: "Auditio",
    title: "Listening to One's Own Conscience",
    scripture: {
      reference: "1 Kings 19:11-13",
      text: "And after the fire a whistling of a gentle air. And when Elias heard it, he covered his face with his mantle, and coming forth stood in the entering in of the cave, and behold a voice unto him, saying: What dost thou here, Elias?",
    },
    excerpt: {
      workId: "newman-idea",
      author: "John Henry Newman",
      citation: "A Letter Addressed to His Grace the Duke of Norfolk, § 5 (1875)",
      text: "Conscience is the aboriginal Vicar of Christ, a prophet in its informations, a monarch in its peremptoriness, a priest in its blessings and anathemas, and, even though the eternal priesthood throughout the Church could cease to be, in it the sacerdotal principle would remain and would have a sway. Were it not for this voice, speaking so clearly in our conscience and our heart, we should have no sense of being responsible at all; or rather, we should have no sense of being persons at all.",
    },
    meditation: `The hardest voice in the practice to listen to is the one inside you. You can train your ear to opposing counsel, to the bench, to the witness, to the client. You can sit in the silence of the deposition and let the witness fill it. The voice you have grown most practiced at not hearing is the one that has been speaking, often for weeks, about the very case you are now sitting with — your own conscience.

The conscience does not usually shout. It works the way the small voice at Horeb worked. Not the wind, not the earthquake, not the fire — the whistling of a gentle air. By the time you hear it clearly, it has often been speaking for a long time, and you have been turning the radio up. The case is going forward and you have agreed to the strategy, and somewhere underneath the strategy a small persistent note has been sounding: this is not right. You have been hearing the note as background noise. The note has been louder than you allowed yourself to notice. The conscience, in Newman's phrase, is patient. It does not give up after the first dismissal. It also does not, on its own, become more audible. It is on you to listen.

Newman's defense of conscience, in the Letter to the Duke of Norfolk, is the great Catholic statement of what is at stake. "Conscience is the aboriginal Vicar of Christ." The phrasing is deliberately enormous. The conscience is older than the visible Church, older than the legal profession, older than your firm, older than the bar. It is the prophetic voice God has lodged inside you so that, when every external authority fails or contradicts itself, you would still have an internal witness to right and wrong. Newman calls it a prophet in its informations, a monarch in its peremptoriness, a priest in its blessings and anathemas. The conscience tells you what is true (prophet), it commands without negotiation (monarch), and it pronounces over the soul a benediction or a curse (priest). You are not free to ignore any of the three functions. You are free, painfully, to disobey them. The disobedience does not silence the voice. It only roughens your hearing.

Notice that Newman locates personhood in the capacity for conscience. "Were it not for this voice, speaking so clearly in our conscience and our heart, we should have no sense of being responsible at all; or rather, we should have no sense of being persons at all." A lawyer who has trained himself to override his conscience long enough has trained himself out of the experience of being a person. He is still a competent professional. He is still skilled at the work. But the interior thing that once said "wait, this is not right" has either gone quiet or has gone over to the side of the strategy. The proceedings of his life, conducted in the absence of that voice, are no longer truly his proceedings. They are proceedings he is performing.

The lawyer's specific failure mode here is well known. The conscience speaks about a particular case. The lawyer responds, not by changing what he is doing, but by re-framing what he is doing in terms that the conscience cannot easily object to. The discovery response is borderline; he calls it aggressive lawyering. The witness preparation has crossed a line; he calls it thorough. The argument he is about to make is one he does not believe; he calls it advocacy. The vocabulary of the profession is enormously useful at making the conscience's objections sound naive. The conscience, however, is not naive. It is using a smaller vocabulary because it is older than the profession, and it knows that the smaller words — wrong, not right, you cannot, you must not — are the words that actually correspond to what is going on. Re-framing the case in fancier vocabulary does not change what the conscience is responding to. It only adds another layer between you and the voice.

The Christian tradition has named one practice for keeping the channel open: the daily examination of conscience. Not as an act of scrupulosity, not as an excavation of every misstep, but as a few minutes at the end of the working day in which you ask yourself, in front of God, what the small voice has been saying that you have been declining to hear. Was there an email you should not have sent? Was there a moment in the deposition where you went further than you should have? Was there a representation to opposing counsel that, technically true, was meant to mislead? The examination does not require dramatic findings. Most days, the findings are small. The point is to keep your ear in. The lawyer who examines at the end of each day is the lawyer who is not going to be surprised, three years from now, to find that he has slowly become someone he did not intend to be. The lawyer who never examines is the lawyer for whom the moral injury arrives as a kind of weather. He cannot say when it started raining. He only notices that he is wet.

There is a particular case that always belongs to this examination, and most lawyers have one. The case the conscience has been speaking about for weeks. You know which one. It is the case you avoid mentioning to your spouse. It is the case you check the document on at midnight, hoping you misread it earlier. It is the case that makes you suddenly tired when its name comes up at the morning meeting. The conscience knows what is wrong with this case. You know what the conscience knows. The strategy of avoidance is no longer working. The case has been speaking to you in the gentle voice for some time, and the gentleness is not weakness. The gentleness is patience. The voice will become harder to hear if you keep refusing it. It will not, however, stop. The conscience, Newman says, is sovereign. It abides.

What is to be done. The honest answer is uncomfortable. Sometimes the right step is to recuse from the matter. Sometimes the right step is to refuse the next step in the strategy and force the discussion the firm is avoiding. Sometimes the right step is to go to confession, name what you have done, and then come back to the file with the conscience cleared and the path forward newly visible. Sometimes the right step is the simplest and the hardest: to do the thing the conscience has been telling you to do, even though it costs the case, and to trust that the cost is bearable because the alternative is the slow erosion of the personhood Newman says the conscience guards.

Elias, in the cave, had to come out and stand at the entering in. The voice would not speak fully until he had stopped hiding from it. The same is true of the lawyer who has been refusing to hear his own conscience on a particular file. The voice is still there. The mantle over your face is what is keeping you from hearing it cleanly. Stand at the entering in. Ask the question Elias was asked, and let yourself answer honestly. What dost thou here. What, in fact, are you doing on this file that you are not ready to say out loud? The voice that asked the prophet that question is the same voice that has been waiting all month for you to be ready to answer it. It is asking now.`,
    prayer: `Lord, you who spoke to your prophet in the whistling of a gentle air after the wind and the earthquake had passed, give me the courage to come out of the cave and stand at the entering in. Quiet the noise I have been using to drown the small voice. Let me name the case the conscience has been speaking about, and let me act on what I hear, even where the action will cost me the brief.`,
    prompt: `Which case in your current file room has your conscience been speaking about for weeks — and what would the smallest faithful act of obedience look like before Friday?`,
    situationalTags: ["arguing-against-conscience", "sole-practice-loneliness"],
    pocketbookKey: "situation:arguing-against-conscience",
  },
];
