import type { DevotionalDay } from "../types";

/**
 * Week 24 — Pardon / Indulgentia.
 *
 * A meditation week on the Christian doctrine of forgiveness, considered
 * through the lens of legal practice. The week sits with what forgiveness
 * asks of us: as advocates, as Christians, as ordinary professionals
 * carrying the weight of cases handled long ago.
 */
export const week24: DevotionalDay[] = [
  {
    day: 162,
    date: "06-11",
    weekNumber: 24,
    weekArc: "Pardon",
    weekArcLatin: "Indulgentia",
    title: "As We Also Forgive",
    scripture: {
      reference: "Matthew 6:9-15",
      text: "Thus therefore shall you pray: Our Father who art in heaven, hallowed be thy name. Thy kingdom come. Thy will be done on earth as it is in heaven. Give us this day our supersubstantial bread. And forgive us our debts, as we also forgive our debtors. And lead us not into temptation. But deliver us from evil. Amen. For if you will forgive men their offences, your heavenly Father will forgive you also your offences. But if you will not forgive men, neither will your Father forgive you your offences.",
    },
    excerpt: {
      author: "John Chrysostom",
      citation: "Homilies on the Gospel of St. Matthew, Homily XIX (NPNF tr.)",
      text: "Seest thou after how many things He hath put it here? For since it was likely, being men, that they should sin after the laver, He shewing here also His great love to man, commanded us to draw nigh unto God's love towards man, entreating Him to forgive us our debts, as we forgive our debtors. And on this argument He brought in His doctrine, that we may see clearly that nothing is so much our own as the things which we have lent unto God by deeds done unto our neighbour. Forgive, that thou mayest be forgiven; for in this matter He hath made us the lords of our own arraignment.",
    },
    meditation: `The petition is the only one in the prayer that ties God's hand to ours. The others ask. This one bargains. \"Forgive us our debts, as we also forgive our debtors.\" The Greek and the Latin both carry the legal term — debita, what is owed and not paid, the unsettled account on the ledger — and the prayer asks the Father to settle our account on the same terms we settle the accounts of the people who have failed us.

You, who deal in debt all day, who litigate it, who collect it, who argue for the discharge of it, ought to feel that petition more sharply than most. You know what it costs to release a debt. You know that a debt released is, from the creditor's side, a loss recognized. Forgiveness is not the discovery that the wrong did not happen. Forgiveness is the decision to bear the cost of the wrong yourself, instead of demanding the debtor bear it. This is exactly what the Lord does, in the cross, with your account. And it is exactly what he asks you to do, in your day, with the accounts of those who owe you something they will never pay.

Chrysostom, preaching this passage to the Christians of Antioch, sees what is dangerous in the petition. \"He hath made us the lords of our own arraignment.\" The phrase is exact. You are not pleading your case before a remote judge who will decide on the merits of your contrition. You are pleading your case before a judge who has handed you the pen and asked you to write the rule by which you yourself will be judged. The rule you write for your debtors is the rule the Father will apply to you. If you write a hard rule, you will be judged by a hard rule. If you write a generous one, you will be judged generously. The arraignment is yours. The verdict will track the rule.

This is uncomfortable for a lawyer because lawyers, as a class, keep good books. You remember slights. You remember which adversary lied in the deposition six years ago. You remember the colleague who took credit for the brief you wrote at three in the morning. You remember the judge who ruled against you in chambers and never explained why. The professional faculties that make you a careful litigator — accurate memory, attention to inconsistency, a sense of when you are being played — are exactly the faculties that make forgiveness hard. The same memory that wins the cross-examination keeps the grudge alive long after the case is closed.

Notice what Christ does not say. He does not say that forgiveness is the discovery that the debtor was not really a debtor. He does not say you must persuade yourself that the wrong was not a wrong. He uses the word debts. The debt is real. The wrong was a wrong. The petition asks you to release a debt you have every right, under the natural law of the ledger, to keep. That is what makes it a petition and not an observation. If the debt were unreal, no release would be required. The release is the price of admission to the prayer.

Sit with this in your own practice. Begin with the small ones, because the large ones will overwhelm you. The opposing counsel who emailed you at eleven on a Friday night demanding a response by Monday morning, knowing full well you have small children — do you still hold that against him? The partner who put your name third on the brief, where it should have been second — do you still feel the heat in your chest when you see her in the corridor? The client who ran up the bill and then complained you over-charged — what does the ledger of your heart still say about him? These are not the great wrongs of your life. They are the practice ones. They are the ones the Lord is asking you to release first, so that you will know how to release the larger ones when they come.

Chrysostom understood that the petition is also a comfort. \"Nothing is so much our own,\" he says, \"as the things which we have lent unto God by deeds done unto our neighbour.\" The forgiveness you extend to your debtors is not lost. It is lent. It is deposited in an account from which you yourself will be paid. The mercy you give is the mercy you will be given. This is not magic. It is not a divine quid pro quo. It is something deeper: the disclosure that the mercy you are capable of giving is the only measure you have of the mercy you are capable of receiving. A heart that cannot release is a heart that cannot be released. The narrowness of the channel runs both ways.

You may protest that some debts are too large to release. The lawyer in you will be ready with the arguments. Some wrongs require justice. Some debtors must be made to pay, or the moral order itself collapses. The arguments are not wrong. There is a place for accountability, for the criminal docket, for the civil action, for the disbarment hearing. But the place is not in your prayer at night. In your prayer at night you are asked to release what you have a right to hold, not because the wrong was small, but because the Father has released what he had a right to hold against you, and the only adequate response is to extend the same release to the people who owe you.

Pray the petition slowly tonight. Pray it with a specific name in mind — the colleague, the client, the adversary, the family member. Pray it knowing you are writing the rule by which you yourself will be judged. Then go to sleep, and let the Father, who has already paid your debt, teach you what you have just promised.`,
    prayer: `Father, you have forgiven me debts I could not have paid, and you have asked me, in your own prayer, to forgive the small debts of those who owe me. Loosen my hand from the ledger I keep against them. Let the rule I write for my debtors be the rule I will not regret when it is read back to me. Forgive me, as I forgive them.`,
    prompt: `Whose name comes to mind when you pray \"as we also forgive our debtors\" — and what is the debt, and what would it cost you to release it?`,
    situationalTags: ["moral-injury", "after-confession"],
  },
  {
    day: 163,
    date: "06-12",
    weekNumber: 24,
    weekArc: "Pardon",
    weekArcLatin: "Indulgentia",
    title: "The Virtue of Mercy",
    scripture: {
      reference: "Luke 6:36-38",
      text: "Be ye therefore merciful, as your Father also is merciful. Judge not, and you shall not be judged. Condemn not, and you shall not be condemned. Forgive, and you shall be forgiven. Give, and it shall be given to you: good measure and pressed down and shaken together and running over shall they give into your bosom. For with the same measure that you shall mete withal, it shall be measured to you again.",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae II-II, q. 30, a. 4 (English Dominican tr.)",
      text: "Mercy signifies grief for another's distress. Now this grief may denote, in one way, a movement of the sensitive appetite, in which case mercy is not a virtue but a passion; whereas, in another way, it may denote a movement of the intellective appetite, in as much as one person's evil is displeasing to another. This movement may be ruled in accordance with reason, and in accordance with this movement regulated by reason, the movement of the lower appetite may be regulated. Hence Augustine says that this movement of the mind obeys the reason, when mercy is vouchsafed in such a way that justice is safeguarded, whether we give to the needy or forgive the repentant. And thus mercy is a virtue, and indeed the greatest of those virtues which relate to our neighbour.",
    },
    meditation: `Aquinas, in his patient way, asks the question a lawyer would ask: is mercy actually a virtue, or is it only a feeling? The distinction matters. A feeling visits you and leaves. A virtue is a stable disposition, a habit of soul, something on which a life can be built. If mercy is only the warm flush you sometimes feel at the sentencing hearing — the moment your client's mother weeps in the second row and your throat thickens — then mercy is unreliable. It will not be there when the courtroom is empty and the file is closed and the question is whether to make the next phone call.

His answer is careful. Mercy is, in one of its modes, a passion: the involuntary grief that another's distress provokes in the well-formed soul. That mode is good but insufficient. It is the seed. The virtue proper is mercy that has passed through the intellect, been weighed in the light of reason, and emerged on the other side as a deliberate disposition: I will be the kind of person who is moved by the suffering of others, and I will let that motion shape what I do, even when the motion has subsided. Mercy as virtue does not require the welling-up. It requires the will.

Then Aquinas does something startling. He calls mercy \"the greatest of those virtues which relate to our neighbour.\" Not justice. Not piety. Mercy. The reason he gives, a few articles later, is that mercy is the virtue most properly attributed to God, because in mercy the strong stoop to the weak, and this stooping is the deepest signature of the divine nature. Justice gives each their due. Mercy gives more than is due. The lawyer is the professional of due. The Christian is the professional of more than due. To be both at once is the hardest possible vocation.

In the next quaestio Aquinas turns to clementia — clemency — and treats it as the virtue that moderates the impulse to punish. He is writing for princes and judges, but he is also writing for you, because you live among the moderating professions. You write the demand letter that could have been harsher. You take the deposition that could have humiliated the witness and chose not to. You craft the cross-examination that could have ruined the elderly widow on the stand and instead let her keep her dignity. Clemency in your hands is not the abandonment of advocacy. It is the moderation of force, the deliberate use of less power than you possess, the small daily decisions by which the strong stoop to the weak.

The reason clemency is hard is that it is invisible. No one rewards you for it. No client says: thank you for not destroying him on cross. No partner says: the brief was effective and also kind. The market does not price restraint. Clemency, like most of the deep virtues, is its own and only witness. You will know that you did not need to call the third witness, the one whose only function was to twist the knife, and you will not call her, and no one in the courtroom will know what you have just refused. Mercy lives in the gap between what you could have done and what you did.

Notice, however, that Aquinas safeguards mercy from a danger lawyers especially feel. \"Mercy is vouchsafed in such a way that justice is safeguarded.\" Mercy is not the dissolution of justice. Mercy is justice fulfilled. The merciful prosecutor does not stop prosecuting. He prosecutes with proportion. The merciful judge does not abandon the sentencing range. He uses it with discernment. The merciful counsel does not stop representing his client. He represents him without making the litigation into a vendetta. Mercy is the way a just hand learns to open.

A lawyer once told me she had stopped praying for her opponents because the prayer felt false. She did not want them blessed. She wanted them defeated. I told her that the prayer for one's enemies is not the prayer of a feeling but of a virtue. You do not have to feel benevolence toward the opposing counsel to pray that he be saved. You only have to be willing to say the words. The feeling, Aquinas would tell her, may follow the act. The virtue is built up by the act long before the feeling catches up to it. If you wait to be merciful until you feel merciful, you will never be merciful, because the feeling does not come on demand. The virtue does, because the virtue is yours to deploy.

There is a particular trap for advocates. You are paid to win, and winning has its own gravity. The case organizes itself around the binary, and the binary trains you to see the opponent as something less than a full neighbour. The witness becomes a target. The adversary becomes an obstacle. The judge, if he rules against you, becomes a fool. Without noticing it, you have stopped seeing persons and started seeing positions. Mercy is the slow re-introduction of the person into the field of your vision. It is the act by which you remember that the opposing counsel will go home tonight to a child who is sick, that the witness will lie awake remembering the cross, that the judge has a docket of two hundred matters and yours was not the deepest one he heard today. Mercy, at this level, is just the recovery of perception. It is seeing what is actually there.

Aquinas ends the article on mercy with a sentence that has always undone me. He notes that mercy, considered in itself, is greater than every other virtue concerning our neighbour, but considered as ordered to God, charity is greater, because charity unites us to God, while mercy unites us only to our neighbour in his deficiency. Sit with that. Charity carries you up. Mercy stoops you down. You need both. The lawyer who only stoops will burn out. The lawyer who only ascends will float free of the suffering he was sent to. The Christian advocate is the one who, lifted by charity, comes back down with mercy. He stoops not because he has been demoted but because he has been sent.`,
    prayer: `Lord, who hast called mercy the greatest of the virtues toward my neighbour, build it in me as a habit and not a mood. Let me use less force than I possess, and let me see the persons behind the positions in my file. When I cannot feel mercy, let me at least will it, knowing that the feeling follows the act in the soul of one who has decided to be merciful as the Father is merciful.`,
    prompt: `Where in this week's work could you use less power than you possess — and what, exactly, is keeping you from doing so?`,
    situationalTags: ["before-sentencing", "moral-injury"],
  },
  {
    day: 164,
    date: "06-13",
    weekNumber: 24,
    weekArc: "Pardon",
    weekArcLatin: "Indulgentia",
    title: "The Year of Jubilee",
    scripture: {
      reference: "Leviticus 25:10-13",
      text: "And thou shalt sanctify the fiftieth year, and shalt proclaim remission to all the inhabitants of thy land: for it is the year of jubilee. Every man shall return to his possession, and every one shall go back to his former family: Because it is the jubilee and the fiftieth year. You shall not sow, nor reap the things that grow in the field of their own accord, neither shall you gather the firstfruits of the vines, because of the sanctification of the jubilee: But as they shall be found, you shall presently eat them. In the year of the jubilee all shall return to their possessions.",
    },
    excerpt: {
      workId: "blackstone-commentaries",
      author: "William Blackstone",
      citation: "Commentaries on the Laws of England, Bk. IV, ch. 31 (Of Pardon)",
      text: "In democracies, this power of pardon can never subsist; for there nothing higher is acknowledged than the magistrate who administers the laws; and it would be impolitic for the power of judging and of pardoning to centre in one and the same person. This (as the president Montesquieu observes) would oblige him very often to contradict himself, to make and to unmake his decisions; it would tend to confound all ideas of right among the mass of the people; as they would find it difficult to tell, whether a prisoner was discharged by his innocence, or obtained a pardon through favour. To him therefore the people look up as the fountain of nothing but bounty and grace; and these repeated acts of goodness, coming immediately from his own hand, endear the sovereign to his subjects, and contribute more than any thing to root in their hearts that filial affection, and personal loyalty, which are the sure establishment of a prince.",
    },
    meditation: `The pardon power is the strangest authority in the constitutional architecture. Every other power can be checked. Every other decision can be reviewed. But the executive's act of clemency, once given, is given. The conviction stands; the sentence is forgiven. The legal order recognizes, by this single provision, that justice unrelieved by mercy is not the whole of what a polity owes its members. There must be, somewhere in the structure, a hand that can let a person go.

Blackstone, writing in the high noon of the English constitution, locates the pardon in the prince because the prince, alone among officers, stands above the system that has condemned the prisoner. The system is doing its work properly when it convicts; the system is doing a different work when it pardons; the two cannot be done by the same hand without contradiction, so the Crown is given the second. Notice the political theology folded inside the Commentaries: the pardon is not a derogation from law but a perfection of it. It is the place in the law where the law confesses its own limits and admits that the rule, applied without remainder, would fail the human being.

This is the doctrine of pardon as a legal institution, and it is older than the constitution. It is older than Rome. It is older than the prophets. It is found, perhaps most beautifully, in the law of Jubilee. Every fiftieth year, Leviticus commands, the trumpet sounds, debts are released, slaves go free, and the land returns to its original families. The land cannot be sold in perpetuity, because the land does not belong to those who hold it; it belongs to the Lord, and they are tenants. The Jubilee is the institutional confession that property and bondage and accumulated debt, left to their natural growth, will swallow the poor man whole, and that the law must build into itself a periodic relief, a structural mercy, a moment at which the ledger is wiped and the people begin again.

You may not have a Jubilee year in your own practice. But you have its descendants. You have expungement, which lets a man rent an apartment without his twenty-year-old conviction following him onto the application. You have the executive clemency petition, which you have drafted three times and seen granted once, and which on the day it was granted made your client's mother sit down on the courthouse steps and weep. You have the discharge in bankruptcy, which is in its essence a Jubilee for the over-indebted, written into the federal code. You have the criminal record sealing, the youthful offender adjudication, the deferred prosecution agreement. These are not technicalities. These are the law remembering what it is for.

Sit with that for a moment. The lawyer's work in pardon is not the work of bending the law toward mercy from outside. It is the work of finding, within the law, the places where mercy has already been written, and putting them to use for the persons who need them. The Jubilee is in the code. You have only to file the petition.

You have probably had clients for whom the merciful provision was available and who had never heard of it. The young man whose conviction is eligible to be sealed. The woman whose deportation could be deferred under a humanitarian discretion she did not know existed. The veteran whose discharge could be upgraded if someone took the time to assemble the records. The system is full of small jubilees that lie dormant because no lawyer has filed the paper. This is one of the cheapest works of mercy available to you. It does not require a feeling. It requires only the time to fill out the form, the willingness to write the cover letter, the patience to follow up when the agency does not respond.

There is a temptation, in modern practice, to scorn pardon as soft. The hard work, we are told, is the trial. The hard work is the appeal. Pardon is a kind of consolation prize, the thing you turn to when the law has run out. Blackstone, and the Jubilee, would correct us. Pardon is not the failure of law. Pardon is one of the law's highest acts. The trial determines what is owed under the rules. The pardon determines what mercy will do about what is owed. Both are operations of justice. The second is the harder, because the first can be conducted by a machine, and the second cannot.

A lawyer who works in clemency once told me that what wrecked him was not the denials. It was the granted petitions, because each granted petition opened a door he could see and most other petitioners could not afford. He carried, after twenty years, the names of the ones who never had a lawyer to file the paper. He carried them, he said, the way a soldier carries his dead. They are still in the system. They are still serving the sentence. They are eligible for the relief no one filed for. He could not save them, and he could not stop knowing they were there.

This is, perhaps, the lawyer's most particular share in the doctrine of pardon: the knowledge of who is eligible and the inability to reach them all. You will never reach them all. The Jubilee, in the original text, came every fifty years. Yours comes every business day, in the matters that cross your desk. File the petitions you can. Train the next lawyer to file the petitions you cannot. And do not despise the institution because it is small. The man whose conviction is sealed will tell you, when you call to give him the news, that it is not small. He has been waiting for the trumpet for twenty years.`,
    prayer: `Lord of the Jubilee, who hast written mercy into the law itself, give me eyes to find the provisions of pardon that lie unused in the codes I work under. Let me file the petition for the client who does not know it exists. Let me not despise the small clemencies because the great ones are rare. Sound the trumpet through my hands today, for one prisoner, for one debtor, for one of yours.`,
    prompt: `Whose file, on your desk or in your memory, contains a small Jubilee that has not been claimed — and what would it take to claim it?`,
    situationalTags: ["accepting-pro-bono", "justice-gap"],
  },
  {
    day: 165,
    date: "06-14",
    weekNumber: 24,
    weekArc: "Pardon",
    weekArcLatin: "Indulgentia",
    title: "When the Client Cannot Yet Forgive",
    scripture: {
      reference: "Psalm 6:2-7",
      text: "Have mercy on me, O Lord, for I am weak: heal me, O Lord, for my bones are troubled. And my soul is troubled exceedingly: but thou, O Lord, how long? Turn to me, O Lord, and deliver my soul: O save me for thy mercy's sake. For there is no one in death, that is mindful of thee: and who shall confess to thee in hell? I have laboured in my groanings, every night I will wash my bed: I will water my couch with my tears. My eye is troubled through indignation: I have grown old amongst all my enemies.",
    },
    excerpt: {
      author: "Ambrose of Milan",
      citation: "De Paenitentia, Book II, ch. 10 (NPNF tr.)",
      text: "It is good that a man should bear correction with patience, but in penitence there is more than this; for he who repents must not only bear his grief but love it, and esteem it sweet, since by it he is restored. We do not therefore demand from the wounded man the strength of one in health, nor from him who is yet trembling under the lash the cheer of one already healed. Let us bear with our brother who is still weeping, for the Lord himself wept at the tomb of Lazarus, and did not rebuke the sisters that they had not yet seen the resurrection.",
    },
    meditation: `She sat across the conference table and told you, in the flattest voice you have ever heard, that she would not forgive him. Not now. Not ever. She did not want the restorative-justice meeting. She did not want the apology letter. She wanted the maximum, and if the court would not give her the maximum she wanted to know whether you could appeal it. You took notes. You said you understood. You did not, in that conversation, ask her to be merciful. You knew better.

There is a kind of pastoral malpractice common among Christians, and it is sometimes practiced by Christian lawyers in the worst possible setting: the conference room with a victim of a serious wrong. The malpractice is to rush the wounded toward forgiveness. To tell her, while the bruise is still fresh, that she must let it go for the sake of her soul. To quote the Lord's Prayer at her before her body has stopped remembering what happened to it. It is a kind of theological violence, well-meant, that has driven many honest people out of the Church.

Ambrose, who knew something about the discipline of penitence, writes the corrective. \"We do not therefore demand from the wounded man the strength of one in health, nor from him who is yet trembling under the lash the cheer of one already healed.\" The phrase is a small marvel. The wounded man is not in the same condition as the healed man, and the spiritual demands appropriate to one are not appropriate to the other. The Lord, Ambrose adds, wept at the tomb of Lazarus and did not rebuke the sisters for not yet seeing the resurrection. He stood with them in their grief before he raised their brother. He did not say: be of good cheer, the miracle is coming. He wept.

Your client is in the position of the wounded man. She is trembling under a lash that has just fallen on her. To press her toward forgiveness while she is still bleeding is to ask of her a virtue that the Lord himself, by his tears at Lazarus, validated as too soon for her. She is permitted, in your office, to be where she actually is. Her where-she-actually-is is the eighth verse of the sixth psalm: \"I have laboured in my groanings, every night I will wash my bed: I will water my couch with my tears. My eye is troubled through indignation: I have grown old amongst all my enemies.\" The psalm is not embarrassed by the unfinished forgiveness. The psalm is the prayer of the unfinished. The Church included it in the Penitential Psalms not because it is exemplary but because it is honest. The wound speaks for itself.

What, then, is your work? Not to forgive on her behalf. You cannot. Not to rebuke her for not yet forgiving. The Lord at the tomb forbids it. Your work is to walk with her along the road her soul is actually on, while remaining yourself a person who knows the road has a destination she cannot yet see. You hold the doctrine of forgiveness in trust for her. You do not press it on her. You preserve it. You become, in the language of an older spirituality, a custodian of the hope that she will one day be able to forgive, while not requiring that day of her now.

This requires of you a particular discipline. You must not pretend that the wrong was small. The temptation to minimize will be strong, because if the wrong is large, the road to forgiveness is long, and you would like the matter to settle. Do not minimize. The wrong was what it was. You must also not validate the corrosive forms her grief is taking. If she begins to organize her life around the maximum penalty, around the wish that the defendant be ruined, around the consoling fantasy that his suffering will eventually equal hers, you must, gently, indicate that this road leads somewhere she does not want to go. She does not need a lawyer who feeds the bitterness. She needs a lawyer who holds the door of forgiveness open without pushing her through it.

There is a particular pastoral moment that recurs in this work, and you should be ready for it. It comes months or years later. The case is over. She calls you about a renewed restraining order, or about a notice from victim services, or about nothing at all. She mentions, almost in passing, that she has been thinking about writing him a letter. She is not sure she will send it. She wanted to tell you. You ask her, carefully, what the letter would say. She tells you. She has begun, in her own time and at her own pace, to forgive. The road that you would have wrecked by pressing her along it has carried her, in its own seasons, to a place she could not have reached at the conference table. Your job, in that phone call, is to listen. It is to thank her for telling you. It is to refrain, even now, from saying anything that would make her grief into your accomplishment.

Ambrose ends his chapter with a note for the confessors of his diocese: do not lay heavier burdens on the wounded than the wounded can bear. The principle applies to you. You are not her confessor. You are her advocate. But you are, in your office, in the place of the priest, in this sense: you are one of the few people who will see her grief at full strength and have the chance to handle it well or badly. Handle it well. Let her weep. Let her say the things she would not be permitted to say in church. Do not make her feel that her unfinished forgiveness disqualifies her from the room. The Lord at the tomb does not disqualify her. Neither will you.

And if you are, yourself, the one who cannot yet forgive — and you may be, more often than you admit — extend to yourself the patience you have learned to extend to her. The psalm is for you too. The bed is washed with tears, the eye is troubled with indignation, the heart has grown old among its enemies. The Lord does not rebuke the sisters at the tomb. He will not rebuke you. He weeps with you first. The resurrection follows, in his own time, when you are able to bear it.`,
    prayer: `Lord, who wept at the tomb of Lazarus and did not rebuke the sisters for their grief, give me the patience to sit with those who cannot yet forgive. Keep me from pressing on the wound. Keep me also from feeding the bitterness. Let me be a faithful custodian of the hope I cannot impose, until the day my client, or my own heart, is strong enough to receive it.`,
    prompt: `Is there someone — a client, or yourself — whose unfinished forgiveness you have been treating as a failure rather than as a wound that needs time?`,
    situationalTags: ["after-loss", "moral-injury"],
  },
  {
    day: 166,
    date: "06-15",
    weekNumber: 24,
    weekArc: "Pardon",
    weekArcLatin: "Indulgentia",
    title: "Cases You Still Carry",
    scripture: {
      reference: "Psalm 50:3-6",
      text: "Have mercy on me, O God, according to thy great mercy. And according to the multitude of thy tender mercies blot out my iniquity. Wash me yet more from my iniquity, and cleanse me from my sin. For I know my iniquity, and my sin is always before me. To thee only have I sinned, and have done evil before thee: that thou mayst be justified in thy words, and mayst overcome when thou art judged.",
    },
    excerpt: {
      workId: "augustine-city",
      author: "Augustine of Hippo",
      citation: "Confessions, Book X, ch. 2-3 (Pusey tr., 1838)",
      text: "To Thee then, O Lord, am I open, whatever I am; and with what fruit I confess unto Thee, I have said. Nor do I it with words and sounds of the flesh, but with the words of my soul, and that crying of my thought which Thine ear knoweth. For when I am evil, then to confess to Thee is nothing else than to be displeased with myself; but when holy, nothing else than not to ascribe it to myself: because Thou, Lord, blessest the godly, but first Thou justifiest him ungodly. My confession then, O my God, in Thy sight, is made silently, and not silently. For in sound it is silent; in affection it cries aloud.",
    },
    meditation: `There is a file you no longer have. You closed it eleven years ago, or fifteen, or twenty. The client moved away. The matter resolved. The bills were paid. But you carry it. It comes back to you, often, in the second cup of coffee, or on the drive home, or in the strange middle of the night when the body wakes and the mind, having no defenses, opens to whatever wants to come in. You see a face. You hear a phrase you said and would not say now. You think: I should have done that differently. I should have caught that earlier. I should have made that call.

You are not unusual. This is what it is to have practiced law for any length of time. The cases you handled badly, and the cases you handled adequately when they deserved your best, and the cases that turned out as well as could be expected but in which, somewhere along the way, you said the wrong thing to the right person, or the right thing in the wrong tone — they do not vanish when the matter closes. They are with you. They are part of the inventory of your soul. The senior lawyer who tells you, with a confident bluffness, that he never thinks about old cases is either lying or has built a wall against his own interior life so thick that nothing will ever reach him again.

David, who was a king and not a lawyer, wrote the Miserere about something heavier than a missed deadline. But his line is for you. \"My sin is always before me.\" Always. Not occasionally. Not when convenient. Before me. The capacity to look squarely at one's own failures, without the apparatus of self-justification that the legal mind is so good at, is one of the harder spiritual disciplines a Christian can practice, and it is harder still for a lawyer, because the lawyer is trained to argue for his client and is therefore especially well-equipped to argue for himself. The brief on your own behalf is always available. The Miserere is the renunciation of the brief.

Augustine, whose Confessions are the longest sustained refusal of the brief in Christian literature, makes the strange point that confession to God is not silent and is not noisy. \"My confession then, O my God, in Thy sight, is made silently, and not silently. For in sound it is silent; in affection it cries aloud.\" The case you carry can be confessed without ever being put into words. It can be presented to the Lord in the affection of the soul that is displeased with itself for what it did and is asking, without ornament, to be cleansed. This is the prayer your old files are asking for. They are not asking to be re-opened. They are asking to be confessed.

There is a danger here. The lawyer's conscience can become unhealthily retrospective. You can spend so much time inventorying the old failures that you become a kind of spiritual archivist, paralyzed by the catalogue, no longer present to the case on your desk this morning. Augustine knew this danger too. The Confessions are not an exercise in scrupulosity. They are an exercise in handing-over. The point of bringing the old sin before God is not to hold it indefinitely. The point is to hand it over so that you do not have to hold it any more.

The Catechism of the Council of Trent, instructing pastors on the sacrament of penance, observed that the contrite person is not the person who feels worst about his sin but the person who hands his sin to God with the resolve not to repeat it. The feeling is not the work. The handing-over is the work. You may not feel particularly contrite about the matter from 2009. You may simply be tired of carrying it. That is enough. The Lord receives the handing-over from the tired man. He does not require the dramatic tears. He does not require the cinematic moment of recognition. He requires only that you put the file down at his feet and let him have it.

Try this tonight. Choose one case. Not all of them. One. Sit with the failure as you remember it, without arguing about it, without softening it. Acknowledge that you did what you did, or did not do what you should have done. Then say to the Lord, in whatever words come, that you would like to be done with carrying it. Ask him to take it. Ask him also to bless the client, wherever the client is, with whatever grace the client still needs. And then go to sleep, and if the case comes back to you tomorrow, hand it over again. The handing-over may need to be done many times. That is not a failure of the handing-over. That is the shape of how a lawyer learns to set his old work down.

You will be tempted to say that this is too cheap. That the work was real and the failure was real and a prayer cannot undo it. You are right that the prayer cannot undo it. The work is what it was. The harm is what it was. You may, if you can, make some material restitution — a letter to the client years later acknowledging the error, a contribution to the cause the case touched, a quiet correction of the practice in your own conduct of new matters. These are right. But there will remain a residue you cannot reach, a damage you cannot repair, a piece of the case you cannot fix. That piece is what the handing-over is for. The Lord, who paid the price of the cross for things vastly more grievous than your professional failures, can absorb the residue. You do not have the strength to carry it forever. He does.

You took a vow, when you joined this profession, to serve clients with diligence and competence. You have not always kept the vow. Neither have any of us. The vow is broader than its breach. You may resume the keeping of it tomorrow morning at nine. You may not, however, resume it well if you are still hauling the wreckage of 2009 behind you. Set the wreckage down. Confess it silently and not silently. Then walk into Tuesday a lighter man.`,
    prayer: `Lord, my sin is always before me, and you have promised that, when I confess it, you will blot it out. I bring to you tonight the cases I still carry — the calls I missed, the words I said and would not say now, the harms I did not mean and could not fully repair. Take them from me. Cleanse what I cannot cleanse. Bless the clients whose names you remember when I have forgotten them. Let me sleep, and tomorrow let me practice better.`,
    prompt: `Name one case, in your private memory, that you have never set down — and what, if anything, you are still trying to repair by carrying it.`,
    situationalTags: ["moral-injury", "considering-leaving-practice"],
  },
  {
    day: 167,
    date: "06-16",
    weekNumber: 24,
    weekArc: "Pardon",
    weekArcLatin: "Indulgentia",
    title: "You Thought Evil; God Meant Good",
    scripture: {
      reference: "Genesis 50:15-21",
      text: "Now his brethren fearing, after their father was dead, said one to another: Lest perhaps he should remember the wrong he suffered, and requite us all the evil that we did to him. And they sent a message to him, saying: Thy father commanded us before he died, That we should say thus much to thee from him: I beseech thee to forget the wickedness of thy brethren, and the sin and malice they practised against thee: we also pray thee, to forgive the servants of the God of thy father this wickedness. And when Joseph heard this, he wept. And his brethren came to him; and worshipping prostrate on the ground, they said: We are thy servants. And he answered them: Fear not: can we resist the will of God? You thought evil against me: but God turned it into good, that he might exalt me, as at present you see, and might save many people. Fear not: I will feed you and your children. And he comforted them, and spake gently and mildly.",
    },
    excerpt: {
      workId: "newman-idea",
      author: "John Henry Newman",
      citation: "Parochial and Plain Sermons, Vol. III, Sermon 7",
      text: "There are many men who are not, at the moment, conscious of any sin upon their souls, and yet, were they put to a sharp trial of patience or charity, would be found wanting. They are not yet tried; their good humour has not been crossed; their love has not been required at a real cost. But the heart of Joseph, who had been crossed beyond bearing, and who yet could weep over the brethren that had sold him, that heart was tried, and was found to be Christ's. We are not asked to feel what we do not feel, but we are asked to do what Joseph did, and to leave the rest with God who tries the reins.",
    },
    meditation: `It is the only forgiveness in Genesis. It comes at the end of fifty chapters of family ruin — the brother killed by the brother, the wife stolen and the wife traded, the inheritance bought for a bowl of stew, the trick played on the blind father, the favourite son sold into slavery for twenty pieces of silver and presented to the old man in a bloody coat. By the time Joseph sees his brothers again in Egypt, the wreckage has gone on for two generations. He could, by any worldly accounting, destroy them. He has the granary. He has Pharaoh's ear. He is the second power in the kingdom and they are starving refugees with sons in tow. The accounts could be settled in an afternoon.

He does not settle them. He weeps. Then he says the sentence that contains, in compressed form, more theology of providence than most of the prophets manage in a hundred pages: \"You thought evil against me: but God turned it into good, that he might exalt me, as at present you see, and might save many people.\"

You should sit with that sentence for a long time, because it is the sentence on which the Christian theology of injury rests, and it is the sentence you will need on the day the worst thing in your life turns out, twenty years later, to have been the door through which your vocation came. The sentence does not say that what your brothers did was not evil. They sold you. The text uses the word evil because the deed was evil. The sentence does not soften their act. It does something stranger. It refuses to give their act the final word about what their act meant. The act was theirs. The meaning, in the end, belonged to God.

This is the doctrine that allows Joseph to forgive without falsifying. He does not say, it does not matter. He does not say, you were really only trying to help me. He says, you did the wrong thing, and God did something with the wrong thing that you could not have intended and would not have wanted. The wrong thing was wrong. The use to which God put it was good. The forgiveness is possible because Joseph has, by the time of the speech, learned to see the two layers and let God hold them together. He could not have given the speech in the pit. He could not have given it in Potiphar's prison. He gives it in the granary, after the famine, after he has seen what God was doing with the long ruin of his life.

You are perhaps still in the pit. You are perhaps in Potiphar's prison. There is a thing that was done to you — by the partner who took your name off the deal, by the senior who passed you over, by the client who lied in the deposition and walked away with the money, by something earlier and worse than any of these. You cannot yet say what God meant by it. You may not say it for decades. You may never, in this life, see the granary at the end. Joseph's speech is not advice you can apply to yourself this Tuesday afternoon. Joseph's speech is the future tense of a faith you are now asked to hold without yet being able to deliver.

But it is not nothing that someone delivered it. The Old Testament is the long record of a people who waited for a forgiveness they could not yet enact, and Joseph is the one figure who, before the cross, manages to enact it on his own scale. He is, as the Fathers saw, a type of Christ. The brother sold, the brother elevated, the brother who feeds the family that betrayed him — the lines run all the way to Calvary. When Christ says forgive seventy times seven, he is, in part, recommending Joseph's example to people whose injuries are smaller and whose patience is shorter. The pattern is in the canon. It has been done. It can therefore be done.

Newman, in the sermon excerpted above, sees the danger of admiring Joseph from a comfortable seat. \"There are many men who are not, at the moment, conscious of any sin upon their souls, and yet, were they put to a sharp trial of patience or charity, would be found wanting.\" The lawyer is especially exposed to this danger because the lawyer's day is full of small frictions that do not rise to the level of trial. You handle the rude opposing counsel, the absent-minded judge, the over-billing partner, with a polite professionalism that you may mistake for charity. You are not yet at Joseph's level because you have not yet been at Joseph's depth. The character that forgives the sale into slavery is not built up by surviving an unpleasant meet-and-confer.

The character is built up, Newman says elsewhere, by doing what Joseph did when we are in the smaller versions of his situation, and leaving the rest to God. You are not Joseph today. But you have, today, a smaller version of his sentence to say. The colleague who slighted you. The client who blamed you for an outcome you did not cause. The opposing counsel who sent the snide email. You can say to yourself, in the small chamber of your own thought: he thought evil against me, but God can turn this into good, and I will not require the settling of the account here.

The point is not to feel benevolent toward the person who wronged you. Joseph wept when he saw his brothers. The wound was still there. The point is to refuse, on principle, to give the wrong-doer the last word about what the wrong meant. To leave that last word to God. To let God write the ending. The ending may surprise you. It surprised Joseph. It will surprise the lawyer who, ten years after the worst thing that happened to her practice, will look back and see that the door she went through next, the door that led to the work she now cannot imagine her life without, was the door that opened only because the earlier door slammed.

You may not yet see the granary. Joseph did not see it from the pit. He saw it from the throne, looking back. You will, if you keep faith, look back too. In the meantime: weep when you need to weep, refuse to make the account into a vendetta, and let God hold the meaning of your wound while you go on with the work.`,
    prayer: `Lord of Joseph and of all his wronged children, you have shown me that the wrong done to me does not get to write its own ending. Help me to refuse the vendetta. Help me to weep when I need to weep, and to feed those who once sold me when you give me the chance. Hold the meaning of my wounds in your own hand until I am ready to see what you have done with them.`,
    prompt: `What wrong, done to you in this profession, is still waiting for you to surrender its meaning to God rather than to the wrong-doer?`,
    situationalTags: ["after-loss", "moral-injury"],
  },
  {
    day: 168,
    date: "06-17",
    weekNumber: 24,
    weekArc: "Pardon",
    weekArcLatin: "Indulgentia",
    title: "Father, Forgive Them",
    scripture: {
      reference: "Luke 23:33-38",
      text: "And when they were come to the place which is called Calvary, they crucified him there; and the robbers, one on the right hand, and the other on the left. And Jesus said: Father, forgive them, for they know not what they do. But they, dividing his garments, cast lots. And the people stood beholding, and the rulers with them derided him, saying: He saved others; let him save himself, if he be Christ, the elect of God. And the soldiers also mocked him, coming to him, and offering him vinegar, and saying: If thou be the king of the Jews, save thyself. And there was also a superscription written over him in letters of Greek, and Latin, and Hebrew: This is the King of the Jews.",
    },
    excerpt: {
      workId: "aquinas-summa",
      author: "Thomas Aquinas",
      citation: "Summa Theologiae III, q. 47, a. 4 ad 2 (English Dominican tr.)",
      text: "Christ on the cross prayed for those who crucified Him: not, indeed, for all, but for them that knew not what they did. And in this prayer Christ exercised the office of priest, offering Himself and praying for the sinners, that they might be saved. He prayed, therefore, as Mediator of God and men, and not as one merely suffering at men's hands; for in His Passion He was both priest and victim, and in His prayer He carried His enemies into the very offering He was making of Himself.",
    },
    meditation: `It is the strangest sentence in the Gospels. He is in the middle of being killed. The nails are already in. The dividing of the garments is happening below him. The rulers are mocking him by name, the soldiers are offering him vinegar, the superscription in three languages is already nailed above his head. And he opens his mouth and prays for them. Not against them. For them.

\"Father, forgive them, for they know not what they do.\"

You, who have spent years in the criminal courts, or the bankruptcy courts, or the courts where families dissolve, know how rare this is. You have seen what people say in extremis. You have read the depositions taken in the hospital bed, the statements of the dying, the affidavits of the cornered. The native human reaction to the moment of one's destruction is the curse, the accusation, the last attempt to take someone else down with you. Christ on the cross does the opposite. He absorbs the destruction into himself and sends, in the other direction, a prayer for the destroyers. He is, in that sentence, the entirety of what the law has been trying to figure out about pardon since Hammurabi.

Aquinas, in the great Tertia Pars, says this is the moment in which Christ exercises the office of priest. The priest is the one who carries the offering to the altar. On the cross Christ is both priest and offering, but the more astonishing thing — and this is Aquinas at his most precise — is that Christ carries his enemies into the offering. He does not offer himself in spite of them. He offers himself for them. They are inside the offering. The men who crucified him are, at the moment of their worst sin, the very persons for whom the sin is being remedied. The cross is wide enough to include its own executioners.

This is what Christian forgiveness ultimately is. It is not the polite letting-go of small annoyances. It is not the mature professional decision to move on. It is the priestly act of taking the wound into yourself and refusing to send it back out as a counter-wound. It is the absorption of the harm rather than its return. It is the cross, made small enough to be lived in an ordinary day by an ordinary advocate.

You will not, of course, be crucified this week. The week ahead has different humiliations on the docket. The brief returned with insulting comments. The client who hangs up on you. The judge who interrupts you on the third sentence. The colleague who, you discover, has been speaking against you in a partners' meeting you were not invited to. None of these is the cross. All of these are, in their small way, opportunities to do what Christ did, in the dimensions you can manage. You can absorb the brief without writing the reply email you would like to write. You can let the client hang up and pray for her on the drive home. You can refrain from the small revenge that, in your sleep, you have already drafted against the colleague.

Notice that Christ's prayer does not say the crucifiers did not know enough to be guilty. He says they do not know what they are doing. The Greek is ambiguous; the Latin holds the ambiguity. They are doing something the full meaning of which is hidden from them. They are killing God and they think they are conducting a routine execution under Roman authority. Their ignorance does not exonerate them — Acts and the early sermons treat them as truly guilty — but it does become the ground on which Christ can plead for them. He pleads for them by appealing not to their innocence but to the partial blindness that attends all human evil.

This is consoling for you in a way the cross is not always consoling. The people who have wronged you in your practice did not, in most cases, fully know what they were doing. The partner who took your name off the deal was solving an internal political problem; he was not contemplating the damage to your career arc. The client who lied in the deposition was scared, was protecting something, was running a script she had been running since childhood. The opposing counsel who wrote the snide email was at the end of a long day in a practice he hates. None of this excuses them. All of it gives you, if you can use it, the same ground Christ used. They know not what they do. Father, forgive them.

The Christian doctrine of forgiveness reaches its full statement in this verse. Everything earlier in the canon — the Jubilee, the Psalms of penitence, the prophets' calls to mercy, the Lord's Prayer's own \"as we also forgive our debtors\" — is preparation. The cross is the place where it is finally enacted. And because the cross is the place where it is enacted, every Christian act of forgiveness, however small, is a participation in the cross. When you decide, in a moment that no one will witness, not to send the email you have a right to send, you are not merely exercising a useful professional restraint. You are participating, in your small way, in the priestly act by which the Lord carried his enemies into the offering he was making of himself.

This is the last thing this week wants from you. Not to be Joseph yet — that comes later, when you can see the granary. Not yet to have written your own clemency petition for the wrongs done to you — that may take decades. Only this: that on the cross of your ordinary working day, where the small humiliations come at you in their predictable way, you remember the priest who carried his crucifiers into the offering and try, in your fashion, to do likewise.

You will fail. You will send the email. You will cut the colleague at the partners' meeting. You will not forgive the client who lied. You will return, in your prayer that night, to the same petition you prayed on Monday: forgive me my debts, as I have not, today, forgiven my debtors, but as I want, by your grace, to be the kind of advocate who one day will. Pray it anyway. The week of Pardon ends not on the achievement of forgiveness but on the daily renewal of the desire for it. The Lord who said \"Father, forgive them\" from the cross is, at this moment, saying it for you as well, into an ear that hears him and will, in his own time, answer.`,
    prayer: `Lord Jesus Christ, who on the cross carried your crucifiers into the offering you were making of yourself, teach me the small participations in that priestly act that my ordinary day permits. When I am wounded today, let me absorb the wound rather than return it. When I am unable to forgive, hold the petition open on my behalf until I can join you in it. Father, forgive them. Father, forgive me. Father, by the cross, forgive us all.`,
    prompt: `Where, in the predictable humiliations of the coming week, can you refuse the counter-wound and absorb the harm, however small, in imitation of the One who absorbed yours?`,
    situationalTags: ["moral-injury", "after-confession"],
  },
];
