/**
 * Portal-handoff PDF — one page that mirrors the bar-portal's exact
 * field structure so the lawyer can transcribe in two minutes.
 *
 * This is NOT a legal filing. It's a worksheet. The lawyer logs into
 * the portal (link at the top of the sheet), opens this PDF next to it,
 * and copies each labeled value across.
 *
 * Per-jurisdiction quirks are baked into the renderer below — CA wants
 * hour-range buckets, MD wants the 5-step AIS order, IL wants the two
 * Rule 756(f) questions split by category, DC wants the simple Honor
 * Roll declaration.
 */

import { jsPDF } from "jspdf";
import autoTable, { type RowInput } from "jspdf-autotable";
import type { BarReportSummary, JurisdictionCode } from "../types";
import { CATEGORY_LABEL } from "../types";
import type { AttorneyHeader } from "../barExport";
import { catalogFor } from "./catalog";

const COLOR_INK: [number, number, number] = [25, 22, 28];
const COLOR_WINE: [number, number, number] = [128, 26, 49];
const COLOR_SLATE: [number, number, number] = [80, 80, 90];
const COLOR_MUTED: [number, number, number] = [130, 130, 140];
const FONT_BODY = "times";

export function renderPortalHandoff(
  jurisdiction: JurisdictionCode,
  summary: BarReportSummary,
  attorney: AttorneyHeader
): jsPDF {
  const doc = new jsPDF({ unit: "in", format: "letter" });
  doc.setFont(FONT_BODY, "normal");
  const catalog = catalogFor(jurisdiction);
  const margin = 1;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(13);
  doc.setTextColor(...COLOR_INK);
  doc.text(`${jurisdictionTitle(jurisdiction)} — PRO BONO REPORTING WORKSHEET`, margin, y);
  y += 0.22;

  doc.setFont(FONT_BODY, "italic");
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_WINE);
  doc.text(`${catalog.ruleCitation} · ${catalog.frequency.replace(/-/g, " ")}`, margin, y);
  y += 0.32;

  // Submission instruction box
  doc.setDrawColor(...COLOR_WINE);
  doc.setLineWidth(0.015);
  doc.rect(margin, y, contentWidth, 0.55);
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_WINE);
  doc.text("How to file:", margin + 0.12, y + 0.18);
  doc.setFont(FONT_BODY, "normal");
  doc.setTextColor(...COLOR_INK);
  const submissionLines = doc.splitTextToSize(catalog.submission, contentWidth - 0.25);
  doc.text(submissionLines, margin + 0.12, y + 0.34);
  if (catalog.portalUrl) {
    doc.setTextColor(...COLOR_WINE);
    doc.setFont(FONT_BODY, "italic");
    doc.textWithLink(catalog.portalUrl, margin + 0.12, y + 0.5, { url: catalog.portalUrl });
  }
  y += 0.75;

  // Attorney identity block
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLOR_INK);
  doc.text("ATTORNEY", margin, y);
  y += 0.18;
  doc.setFont(FONT_BODY, "normal");
  doc.setFontSize(10);
  const identity: [string, string][] = [
    ["Name", attorney.name],
    [barNumberLabel(jurisdiction), summary.barNumber ?? "—"],
    ["Firm / Clinic", attorney.firmOrClinic ?? "—"],
    ["Reporting period", `${reportingPeriod(jurisdiction, summary.reportingYear)}`],
  ];
  for (const [label, value] of identity) {
    doc.setTextColor(...COLOR_SLATE);
    doc.text(label, margin + 0.15, y);
    doc.setTextColor(...COLOR_INK);
    doc.text(value, margin + 2.2, y);
    y += 0.18;
  }
  y += 0.12;

  // Per-jurisdiction body
  switch (jurisdiction) {
    case "US-CA":
      y = renderCaliforniaSection(doc, summary, y, margin, contentWidth);
      break;
    case "US-MD":
      y = renderMarylandSection(doc, summary, y, margin, contentWidth);
      break;
    case "US-IL":
      y = renderIllinoisSection(doc, summary, y, margin, contentWidth);
      break;
    case "US-DC":
      y = renderDcSection(doc, summary, y, margin, contentWidth);
      break;
    case "US-TX":
      y = renderTexasSection(doc, summary, y, margin, contentWidth);
      break;
    default:
      y = renderGenericSection(doc, summary, y, margin, contentWidth);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFont(FONT_BODY, "italic");
  doc.setFontSize(8);
  doc.setTextColor(...COLOR_MUTED);
  doc.text(
    "Worksheet generated by Collegium Patrocinium · This is not a filing. Submit through the portal above.",
    pageWidth / 2,
    pageHeight - 0.35,
    { align: "center" }
  );

  return doc;
}

/* ------------------------------------------------------------------ */
/* California — hour-range buckets per Bus. & Prof. § 6073.2           */
/* ------------------------------------------------------------------ */

function renderCaliforniaSection(
  doc: jsPDF,
  s: BarReportSummary,
  y: number,
  margin: number,
  contentWidth: number
): number {
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLOR_INK);
  doc.text("WHAT TO SELECT ON THE PORTAL", margin, y);
  y += 0.2;

  doc.setFont(FONT_BODY, "normal");
  doc.setFontSize(10);
  doc.text(
    "California reports in HOUR-RANGE BUCKETS, not exact counts. Pick the bucket that matches your total.",
    margin + 0.15,
    y,
    { maxWidth: contentWidth - 0.3 }
  );
  y += 0.32;

  const buckets: { label: string; min: number; max: number | null }[] = [
    { label: "< 1 hour", min: 0, max: 1 },
    { label: "1 to 5 hours", min: 1, max: 6 },
    { label: "6 to 10 hours", min: 6, max: 11 },
    { label: "11 to 19 hours", min: 11, max: 20 },
    { label: "20 to 39 hours", min: 20, max: 40 },
    { label: "40 to 99 hours", min: 40, max: 100 },
    { label: "100+ hours", min: 100, max: null },
  ];
  const matching = buckets.find(
    (b) => s.totalHours >= b.min && (b.max === null || s.totalHours < b.max)
  );

  autoTable(doc, {
    startY: y,
    head: [["Bucket", "Your selection"]],
    body: buckets.map(
      (b) =>
        [
          b.label,
          matching?.label === b.label ? "● SELECT THIS" : "",
        ] as RowInput
    ),
    theme: "grid",
    headStyles: { fillColor: COLOR_WINE, textColor: 255, font: FONT_BODY, fontStyle: "bold" },
    bodyStyles: { font: FONT_BODY, textColor: COLOR_INK, fontSize: 10 },
    margin: { left: margin, right: margin },
    columnStyles: {
      0: { cellWidth: 2 },
      1: { fontStyle: "bold", textColor: COLOR_WINE },
    },
  });
  y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  y += 0.2;

  doc.setFont(FONT_BODY, "italic");
  doc.setFontSize(9);
  doc.setTextColor(...COLOR_SLATE);
  doc.text(
    `Tracked total: ${s.totalHours.toFixed(2)} hours across ${s.matters.length} matters.`,
    margin,
    y
  );
  return y + 0.2;
}

/* ------------------------------------------------------------------ */
/* Maryland — AIS five-step flow                                       */
/* ------------------------------------------------------------------ */

function renderMarylandSection(
  doc: jsPDF,
  s: BarReportSummary,
  y: number,
  margin: number,
  _contentWidth: number
): number {
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLOR_INK);
  doc.text("AIS 5-STEP FLOW", margin, y);
  y += 0.22;

  const steps = [
    [
      "Step I — Professional Activity",
      "Confirm employer type and practice status (no change unless you've switched jobs this year).",
    ],
    [
      "Step II — Practice Area",
      `Matter-type breakdown — your ${s.matters.length} matters this year:`,
    ],
    [
      "Step III — Pro Bono Service",
      `Hours by Rule 6.1 category: see table below. Total: ${s.totalHours.toFixed(2)} hr.`,
    ],
    [
      "Step IV — Financial Contributions",
      "$0 unless you also donated cash to a qualifying legal-aid org this year.",
    ],
    [
      "Step V — Signature & Submission",
      "Sign electronically; AIS will confirm submission with a receipt PDF.",
    ],
  ];
  doc.setFont(FONT_BODY, "normal");
  doc.setFontSize(10);
  for (const [label, body] of steps) {
    doc.setFont(FONT_BODY, "bold");
    doc.setTextColor(...COLOR_WINE);
    doc.text(label, margin, y);
    doc.setFont(FONT_BODY, "normal");
    doc.setTextColor(...COLOR_INK);
    doc.text(body, margin + 0.25, y + 0.16, { maxWidth: 5.5 });
    y += 0.42;
  }

  // Category table for Step III
  autoTable(doc, {
    startY: y,
    head: [["Category (Rule 6.1)", "Hours"]],
    body: s.byCategory.map((c) => [CATEGORY_LABEL[c.category], c.hours.toFixed(2)] as RowInput),
    theme: "grid",
    headStyles: { fillColor: COLOR_WINE, textColor: 255, font: FONT_BODY, fontStyle: "bold" },
    bodyStyles: { font: FONT_BODY, textColor: COLOR_INK, fontSize: 10 },
    margin: { left: margin, right: margin },
  });
  return (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
}

/* ------------------------------------------------------------------ */
/* Illinois — Rule 756(f) two questions                                */
/* ------------------------------------------------------------------ */

function renderIllinoisSection(
  doc: jsPDF,
  s: BarReportSummary,
  y: number,
  margin: number,
  _contentWidth: number
): number {
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLOR_INK);
  doc.text("ARDC REGISTRATION QUESTIONS", margin, y);
  y += 0.22;

  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_WINE);
  doc.text("Q1 — Pro bono legal services this year?", margin, y);
  y += 0.18;
  doc.setFont(FONT_BODY, "normal");
  doc.setTextColor(...COLOR_INK);
  doc.text(
    s.totalHours > 0 ? "YES" : "NO (your tracked total is 0 — confirm before answering)",
    margin + 0.25,
    y
  );
  y += 0.22;

  if (s.totalHours > 0) {
    autoTable(doc, {
      startY: y,
      head: [["Category", "Hours"]],
      body: [
        ["(a) Persons of limited means", s.totalHours.toFixed(2)],
        ["(b) Organizations serving persons of limited means", "0"],
        ["(c) Charitable/religious/civic/community orgs", "0"],
        ["(d) Pro bono training", "0"],
      ],
      theme: "grid",
      headStyles: { fillColor: COLOR_WINE, textColor: 255, font: FONT_BODY, fontStyle: "bold" },
      bodyStyles: { font: FONT_BODY, textColor: COLOR_INK, fontSize: 10 },
      margin: { left: margin, right: margin },
    });
    y = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
    y += 0.18;
    doc.setFont(FONT_BODY, "italic");
    doc.setFontSize(9);
    doc.setTextColor(...COLOR_SLATE);
    doc.text(
      "Most matters routed through Patrocinium go in (a). Reclassify on the portal if some belong in (b)–(d).",
      margin,
      y
    );
    y += 0.2;
  }

  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_WINE);
  doc.text("Q2 — Qualified monetary contributions this year?", margin, y);
  y += 0.18;
  doc.setFont(FONT_BODY, "normal");
  doc.setTextColor(...COLOR_INK);
  doc.text("$0 unless you donated cash to a qualifying legal-aid org.", margin + 0.25, y);
  return y + 0.2;
}

/* ------------------------------------------------------------------ */
/* DC — Capital Pro Bono Honor Roll declaration                        */
/* ------------------------------------------------------------------ */

function renderDcSection(
  doc: jsPDF,
  s: BarReportSummary,
  y: number,
  margin: number,
  contentWidth: number
): number {
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLOR_INK);
  doc.text("HONOR ROLL DECLARATION", margin, y);
  y += 0.22;

  const level =
    s.totalHours >= 100 ? "HIGH HONORS (≥ 100 hr)" : s.totalHours >= 50 ? "HONORS (≥ 50 hr)" : "BELOW THRESHOLD";
  const eligible = s.totalHours >= 50;

  doc.setFont(FONT_BODY, "normal");
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_INK);
  doc.text(`Tracked total: ${s.totalHours.toFixed(2)} hours.`, margin, y);
  y += 0.2;
  doc.setFont(FONT_BODY, "bold");
  doc.setTextColor(...COLOR_WINE);
  doc.text(`Honor Roll level to declare: ${level}`, margin, y);
  y += 0.3;

  doc.setFont(FONT_BODY, "normal");
  doc.setTextColor(...COLOR_INK);
  doc.setFontSize(10);
  const note = eligible
    ? "Declare at capitalprobono.net. Attestation is one checkbox + your jurisdiction(s) of admission."
    : "You do not meet the 50-hour Honor Roll threshold this year. Skip the declaration; no reporting obligation in DC (R. 6.1 is voluntary).";
  doc.text(note, margin, y, { maxWidth: contentWidth });
  return y + 0.3;
}

/* ------------------------------------------------------------------ */
/* Texas — voluntary aspirational reporting                            */
/* ------------------------------------------------------------------ */

function renderTexasSection(
  doc: jsPDF,
  s: BarReportSummary,
  y: number,
  margin: number,
  contentWidth: number
): number {
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(11);
  doc.setTextColor(...COLOR_INK);
  doc.text("TEXAS PRO BONO REPORTING", margin, y);
  y += 0.22;

  doc.setFont(FONT_BODY, "normal");
  doc.setFontSize(10);
  doc.text(
    `Aspirational target: 50 hours / year. Your tracked total: ${s.totalHours.toFixed(2)}. Report through annual State Bar of Texas filing.`,
    margin,
    y,
    { maxWidth: contentWidth }
  );
  y += 0.4;

  autoTable(doc, {
    startY: y,
    head: [["Category", "Hours"]],
    body: s.byCategory.map((c) => [CATEGORY_LABEL[c.category], c.hours.toFixed(2)] as RowInput),
    theme: "grid",
    headStyles: { fillColor: COLOR_WINE, textColor: 255, font: FONT_BODY, fontStyle: "bold" },
    bodyStyles: { font: FONT_BODY, textColor: COLOR_INK, fontSize: 10 },
    margin: { left: margin, right: margin },
  });
  return (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
}

/* ------------------------------------------------------------------ */
/* Generic fallback                                                    */
/* ------------------------------------------------------------------ */

function renderGenericSection(
  doc: jsPDF,
  s: BarReportSummary,
  y: number,
  margin: number,
  _contentWidth: number
): number {
  doc.setFont(FONT_BODY, "bold");
  doc.setFontSize(11);
  doc.text("HOURS SUMMARY", margin, y);
  y += 0.2;
  autoTable(doc, {
    startY: y,
    head: [["Category", "Hours", "Matters"]],
    body: s.byCategory.map(
      (c) => [CATEGORY_LABEL[c.category], c.hours.toFixed(2), String(c.matterCount)] as RowInput
    ),
    theme: "grid",
    headStyles: { fillColor: COLOR_WINE, textColor: 255, font: FONT_BODY, fontStyle: "bold" },
    bodyStyles: { font: FONT_BODY, textColor: COLOR_INK, fontSize: 10 },
    margin: { left: margin, right: margin },
  });
  return (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
}

/* ------------------------------------------------------------------ */
/* Helpers                                                              */
/* ------------------------------------------------------------------ */

function jurisdictionTitle(jur: JurisdictionCode): string {
  switch (jur) {
    case "US-CA":
      return "STATE BAR OF CALIFORNIA";
    case "US-MD":
      return "MARYLAND COURT OF APPEALS (AIS)";
    case "US-IL":
      return "ILLINOIS ARDC ANNUAL REGISTRATION";
    case "US-DC":
      return "D.C. CAPITAL PRO BONO HONOR ROLL";
    case "US-TX":
      return "STATE BAR OF TEXAS";
    default:
      return jur;
  }
}

function barNumberLabel(jur: JurisdictionCode): string {
  switch (jur) {
    case "US-CA":
      return "Cal. Bar #";
    case "US-MD":
      return "MD Attorney #";
    case "US-IL":
      return "ARDC #";
    case "US-DC":
      return "D.C. Bar #";
    case "US-TX":
      return "TX Bar #";
    case "US-NJ":
      return "NJ Bar ID";
    case "US-MA":
      return "BBO #";
    case "US-NY":
      return "NY Bar #";
    case "US-FL":
      return "FL Bar #";
  }
}

function reportingPeriod(jur: JurisdictionCode, year: number): string {
  if (jur === "US-MD") {
    return `July 1, ${year - 1} – June 30, ${year}`;
  }
  if (jur === "US-FL") {
    return `July 1, ${year - 1} – June 30, ${year}`;
  }
  return `January 1 – December 31, ${year}`;
}

/** Download helper. */
export function downloadPortalHandoff(
  jurisdiction: JurisdictionCode,
  summary: BarReportSummary,
  attorney: AttorneyHeader
): void {
  const doc = renderPortalHandoff(jurisdiction, summary, attorney);
  const surname = attorney.name.split(" ").pop()?.toLowerCase().replace(/[^a-z0-9]/g, "-");
  const filename = `${jurisdiction.toLowerCase()}-portal-worksheet-${summary.reportingYear}${
    surname ? `-${surname}` : ""
  }.pdf`;
  doc.save(filename);
}
